open-io/oio-sds

meta2v2/meta2_server.c

Uses symbols deprecated but still present in ZMQ 4

m2v2: uses ZMQ 3.X instead of ZMQ 4.X

---

tools/sds-bootstrap.py

Hello everyone,
I am setting up Open IO in Docker. In the process, I notice that using `os.getlogin()` does not work if the user that executes the program is not logged in via the `login` command. More generally, it seems like `getlogin()` is not too reliable and `getpwuid(getuid())` seems to be a better way to do the same thing: http://stackoverflow.com/questions/4785126/getlogin-c-function-returns-null-and-error-no-such-file-or-directory
Does this change make sense ? Does `getlogin` do something `getpwuid(getuid())` doesn't do ?
Best regards,
Conrad

replace "os.getlogin()" with "pwd.getpwuid(os.getuid())"

---

metautils/lib/asn_AddrInfo.c
metautils/lib/description.asn
metautils/lib/metatypes.h
metautils/lib/test_addr.c
metautils/lib/utils_resolv.c

In addition, we got rid of a legacy of the redcurrant's early days, where ports were encoded on 4 bytes integers.

ASN.1 addresses simplified

---

rawx-apache2/src/tests/test_rawx.py
tools/sds-bootstrap.py

Hello everyone,
On Debian, the path to the Apache2 binary is not `/usr/sbin/httpd` but `/usr/sbin/apache2`. This caused errors in `syslog` for me on Ubuntu (which is Debian based).
Is there any other weird behaviour I should have noticed ? All I saw were errors in syslog, but I couldn't verify what was actually wrong. What is Apache used for ?
Also, are there any tests I can run before committing and making pull requests ? I'm not sure what the process is for testing.
Best regards,
Conrad

adds support for apache2 binary path on debian

---

python/CMakeLists.txt

Hello everyone :smiley: 
I had some errors about "oio-event-agent" not being found. It seems it was related to a missing binary prefix. This commit seems to fix it.
Feel free to ask any questions :)
Best regards,
Conrad

adds "oio" prefix to "event-agent" binary

---

tools/sds-bootstrap.py

OpenIO internally works like a democracy. A vast majority of the electors expressed their opinion: the nginx endpoint proxying the service must leave.
Might the nginx endpoint be successful outside of OpenIO,
Long live the Democracy!

oio-bootstrap.py: endpoint not deployed

---

tools/rawx-monitor.py

Hello everyone at OpenIO :-)
This avoids the `rawx-monitor.py` if RAWX is not up and running. Instead, this makes it log an error to syslog explaining what is going on.
Let me know if this is OK or not.
Best regards,
Conrad

Adds syslogging when RAWX is unavailable

---

client/c/lib/hc_directory.c
meta1v2/meta1_backend.h
meta1v2/meta1_backend_properties.c
meta1v2/meta1_gridd_dispatcher.c
meta1v2/meta1_remote.c
meta1v2/meta1_remote.h
meta2v2/meta2_backend.c
meta2v2/meta2_gridd_dispatcher.h
proxy/dir_actions.c

This is consistent with meta2 and sqlx : set + flush.
Flushing and setting an empty array give the same result as calling a delete.

m1v2: now able to replace all the properties on a reference with a new set.

---

metautils/lib/metautils_errors.h
proxy/m2_actions.c

The case of a "user created but no service linked" was not managed.

proxy: fixed container's autocreation

---

proxy/dir_actions.c

With the v3.0 routes, URL tokens are not systematically checked.
This has been fixed in several places for the service type.
Fixes #164

proxy: added missing sanity checks

---

meta2v2/generic.c
meta2v2/generic.h
meta2v2/m2gen.py
meta2v2/meta2_backend.c
meta2v2/meta2_filters_action_container.c
meta2v2/meta2_utils.c
metautils/lib/metautils_strings.h
metautils/lib/test_str.c
metautils/lib/utils_strings.c
proxy/.functests
proxy/common.h
proxy/m2_actions.c
sqlx/sqlx_service.c
tools/sds-bootstrap.py

* sqlx: fixed minor one-shot memleak e895a79
* m2v2: fixed memleak when creating containers 26496c9
* m2v2: fixed memleak when purging obsolete aliases eb75f0b
* m2v2: fixed "bean leak" when purging exceeding aliases (properties not removed). 81c1f29
* m2v2: fixed "bean leak" when deleting explicit aliases (properties not removed). 81c1f29
* proxy: Fixed compile-time warnings 81c1f29
* proxy: properties returned in headers when getting objects 81c1f29
* proxy: headers matching now case-insensitive 81c1f29
* proxy: In addition, request handlers returning invariable and dummy outputs (empty lists, empty sets) now return nothing. 81c1f29
* tools: bootstrap doesn't deploy the admin flask (it is destined to disappear in the next release and is already used by no one). 81c1f29

Fixes on 0.8.1

---

meta2v2/m2gen.py
python/bin/oio-account-server
python/bin/oio-blob-auditor
python/bin/oio-blob-mover
python/bin/oio-conscience-agent
python/bin/oio-event-agent
python/oio/account/server.py
tools/account-agent.py
tools/account-monitor.py
tools/rainx-monitor.py
tools/rawx-monitor.py
tools/redis-monitor.py
tools/zk-bootstrap.py
tools/zk-reset.py

This makes it easier to work on systems with multiple versions of python installed.

use /usr/bin/env for python scripts shebangs

---

proxy/transport_http.c
sqliterepo/replication.c

With gcc >= 5.1 and glib2 >= 2.44, a bug appeared in embedded function used outside of the original context of their declaration.

proxy, sqliterepo: fixed odd behavior due to nested functions.

---

tools/sds-bootstrap.py
tools/sds-reset.sh
tools/zk-reset.py

commit 7f4a596809be7ea48f5a84f87e88e4d2e5b87936
tools: oio-reset.sh now cleans the META0 registrations with zk-reset.py
This allows subsequent tests to be ran with the same ZK service.
The META0 registrations were the only permanent nodes created by services in ZK.
commit c559491d5eaf0cfdd5334f18a0c546b37903e86c
tools: zk-reset.py's default action is now to clean the META0 services registered.
For the old-style complete flush, use the -a/--all CLI options.
commit 2748bdfea9d596b42c01fef0547057e9c0993823
tools: oio-bootstrap.py doesn't force the PATH for gridinit.
The path is inherited from the user's env.
This is necessary for python scripts installed in an virtualenv.

Jfs tools fixes 20150810

---

python/test-requirements.txt
python/tests/functional/account/test_backend.py
python/tests/functional/account/test_server.py
python/tests/functional/audit/test_audit_storage.py
python/tests/functional/container/test_container.py
python/tests/functional/reference/test_directory.py
python/tests/utils.py
python/tox.ini

To load config for functional tests, use the `SDS_TEST_CONFIG_FILE` env variable.

refactor functional tests config loading

---

proxy/m2_actions.c

proxy: the "prefixes" array is now always present in the successful output of the container's listing.

proxy: Fixed output when listing containers

---

core/CMakeLists.txt
core/ext.c
core/oioext.h
core/test_ext.c
meta1v2/meta1_prefixes.c
meta1v2/meta1_prefixes.h
meta1v2/meta1_server.c
meta2v2/meta2_server.c
metautils/lib/test_str.c
sqlx/sqlx_service.c

commit aa78a055f7298d3a2bdbd4250a2d1e01c6e9f09a
Speeds up the startup of services.
More agressive delays for:
* LB refresh
* prefix loading in meta1
The period between the iterations is shortened until the first success.
commit 41f6fa1b617b2292d2f9a71d133e098b4689d7f2
core: added features to shuffle and partition arrays.
These will be necessary for the resolvers to manage array of targets:
* shuffling to avoid hitting always the same target
* partioning to prefer services with no known problems.

Jfs improvements 20151015

---

meta2v2/meta2_bean.c

M2V2 beans were allocated with the GLib2 (g_malloc0()) and freed with the glibc (free()).

m2v2: only uses the glibc to alloc/free asn1c structures.

---

meta2v2/meta2_filters_extract.c

Even if the function didn't use its wrapper's context, it failed when compiled with recent GCC.

m2v2: nested func made static

---

tools/sds-bootstrap.py

Fixes a problem of rawx not declared when working with a NS differents from the default.

oio-reset.sh: the bootstrap (config generation) had hardcoded NS

---

core/ext.c
core/internals.h
core/oioext.h
core/sds.c
meta2v2/meta2_server.c
proxy/common.c
proxy/dir_actions.c
proxy/metacd_http.c
resolver/hc_resolver.c
tests/unit/test_ext.c

There were partition/shuffle problems when looping on lists of services.
* the ok/nok qualification of services didn't work (in the resolver)
* the shuffling was potentially broken by a subsequent partition ok ok/nok services.
* both weren't called at all in several cases.
Fixes #306

Fixed several optimisations around up/down services

---

sqlx/sqlx_service.c

Avoids calling zookeeper hooks on closed elections.

sqlx: smoother exit sequence for sqliterepo-based

---

metautils/lib/common_main.h

Compilation failed on 32bits platforms such RaspberryPi.

metautils: fixed 32bits timestamp

---

rawx-apache2/src/rawx_repo_core.c

Everything was unnecessarily encoded.

rawx: fixed attr in replies

---

proxy/metacd_http.c
proxy/transport_http.c
proxy/transport_http.h

To fix #339 , a field has been added before the `req_id`, and it is set to "-" when not set, and set to the `container_id` when meaningful.

Fixes #339 (Log format oioproxy)

---

.gitignore
tools/sds-bootstrap.py
tools/sds-reset.sh

Opensuse users are advised to add /usr/sbin in their PATH environment variable before running oio-reset.sh, even if the script will work without it.

Fix oio-reset.sh for Opensuse

---

core/cs.c

A comma was missing in the generated JSON string.

Fix conscience registration with several tags/stats

---

meta0v2/meta0_backend.c
meta1v2/meta1_backend_services.c
sqliterepo/internals.h
sqliterepo/replication.c
sqliterepo/replication_dispatcher.c
sqliterepo/repository.c
sqliterepo/sqlite_utils.c
sqliterepo/sqlite_utils.h
sqliterepo/sqliterepo.h
tools/oio-tool.c

Only one sqlite transaction is now used when opening a base, even if creating it.
The whole schema setup is sent during this only transaction.
The `admin` table is saved only if it changed, with only one statement valued for each field.

sqliterepo: less I/O when creating bases

---

core/proxy.c
core/url.c
rawx-lib/src/attr_handler.c
sqliterepo/synchro.c
tests/unit/test_url.c

* `ZK` now less verbose at init. This avoids logging anything before calling our zk_main_handler on the first connection change, where we tell to ignore the signals (including the problematic SIGPIPE).
* more checks on `oio_url` passed to the API.

Fixes of the day

---

metautils/lib/common_main.c

Avoids putrefying the process with unmanaged SIGPIPE, when happening in threads not ignoring the signal.

common_main: std{err,out} redirected when syslog'ing, even if not daemon

---

cluster/lib/CMakeLists.txt
cluster/lib/gridcluster.c
cluster/lib/gridcluster.h
core/cs.c
core/cs_internals.h
core/oiocs.h
core/proxy.c
metautils/lib/gridd_client.c
proxy/actions.h
proxy/common.h
proxy/cs_actions.c
proxy/metacd_http.c
proxy/transport_http.c
proxy/transport_http.h
tests/func/test_cs.c
tools/sds-reset.sh

* proxy+cluster: cluster now also uses the proxy to reach the conscience
* proxy feature to avoid logging succesful accesses for "too common" requests. It avoids flooding the log service.
* core/cs: interface slightly changed (score now returned when listing services.)
* core/proxy: reqID lazily set to a random hexstring
* tools/oio-reset.sh: # of meta1 checked before meta0 init
* metautils/gridd_client: redirection error should not be modified

Jfs fixes 20160125

---

server/network_server.c

Some services (e.g. oio-proxy) used to hang when asked to stop.

Proxy restart

---

meta1v2/meta1_server.c
meta2v2/meta2_server.c
sqliterepo/election.c
sqlx/sqlx_server.c
sqlx/sqlx_service.h

Avoids recreate deleted bases.

sqliterepo: fix lack of decache upon a GETVERS error

---

sqlx/oio_events_queue.c

`zmq_ctx_term` replaced by `zmq_term`.

sqlx: Fix zeromq3 compatibility

---

meta0v2/meta0_server.c
meta1v2/meta1_server.c
server/network_server.c
sqlx/sqlx_service.c
sqlx/sqlx_service.h

+ m0v2 doesn't allocate an event queue

Protected init phases in m{0,1}v2

---

core/url.c

Prevents an assertion to be raised.

core: guards hexid computation when fields are missing

---

core/oiocfg.h
proxy/sqlx_actions.c
sqliterepo/election.c
sqliterepo/election.h
sqliterepo/internals.h
sqliterepo/replication.c
sqliterepo/replication_client.c
sqliterepo/synchro.c
sqlx/sqlx_service.c
sqlx/sqlx_service.h
tests/unit/test_sqliterepo_election.c

* Elections organized in per-state lists: attempt to make a better management of staled elections, with a higher priority on timers for pending and failed states.
* better default timeouts on synchronicity requests (from 1s to 4s)
* more warnings on specific error-prone situations

Jfs elections timers

---

sqliterepo/internals.h
sqliterepo/replication.c
sqlx/sqlx_service.c

* report individual errors that happened during replicated commits.
* default delay between gratuitous DB_USE set to 5 seconds when sent by failed elections (instead of 2s, too short for a server that already has problems), and to 15 minutes for established elections (instead of 5min, too short for something "not so useful").
* Limits the number of elections timers to 100 (instead of 1000) per round, because there is 1 round / second and 1000s is way too much.

sqlx: election synchronisation reviewed

---

core/oiocfg.h
meta0v2/meta0_remote.c
sqliterepo/repository.c
tools/oio-reset.sh

* Fixes a wrong DB init in sqliterepo that (currently) only happens in meta0 when the base is opened from the cache, before an election_manager is ready to use. This helps fixing #193 (try this, @racciari )
* Extends the timeout when filling the base.
* allows oio-reset.sh to deploy several meta0

m0v2 init sequence fixed

---

core/oiocfg.h
server/network_server.c
server/network_server.h
sqliterepo/synchro.c
sqliterepo/synchro.h
sqliterepo/zk_manager.c
sqlx/sqlx_service.c
sqlx/sqlx_service.h

* Longer timeout by default (4s -> 8s, helps under heavy loads)
* Upon expired sessions, re-opens a new session, with a brand new ID

Fixes the ability to cleanly reconnect ZooKeeper

---

cluster/conscience/conscience_srvtype.c
core/oiocfg.h

* proxy: expiration of known services set to 5 days
* conscience: check more robust for small clocks
* conscience: scored to 0 instead of service removed

conscience: Better timeout management for service's scores

---

.travis.yml
rainx/mod_dav_rainx.c
rainx/rainx_config.h
rawx-apache2/src/mod_dav_rawx.c
rawx-apache2/src/rawx_config.h
rawx-apache2/src/rawx_repo_core.c
sqliterepo/internals.h
sqliterepo/repository.c
sqliterepo/sqliterepo.h
sqlx/sqlx_service.c
sqlx/sqlx_service.h
tools/oio-bootstrap.py

- rawx: new "grid_fallocate" option (enabled by default), to tell
the server to preallocate the space for the chunk, and
possibly fail at the beginnig of the upload if there is not enough
- m0,m1,m2,sqlx: new "PageSize" commandline option to change the
sqlite database page_size (defaults to 4096 bytes)

rawx,sqlx*: new options to preallocate chunks and databases

---

events/oio_events_queue.c
events/oio_events_queue.h
events/oio_events_queue_beanstalkd.c
rawx-apache2/src/mod_dav_rawx.c
rawx-apache2/src/rawx_config_utils.c
rawx-apache2/src/rawx_event.c
rawx-apache2/src/rawx_event.h
rawx-apache2/src/rawx_internals.c

* events / beanstalkd: better check to detect the queue is empty
* events / beanstalkd: memleak fixed, happened once par queue creation
* rawx: 1 queue / request to force one thread manage its own events
* rawx: minor one-shot memleaks fixed

rawx  + beanstalkd: fixes (design, memleak)

---

core/internals.h
events/CMakeLists.txt
events/oio_events_queue.c
events/oio_events_queue.h
events/oio_events_queue_beanstalkd.c
events/oio_events_queue_buffer.c
events/oio_events_queue_buffer.h
events/oio_events_queue_internals.h
events/oio_events_queue_zmq.c
meta2v2/meta2_backend.c

This will reduce the number of events sent by meta2 to account-server:
maximum one event by container each second.

m2,events: new function send overwritable events with delay

---

core/internals.h
core/oiocfg.h
metautils/lib/lrutree.c
metautils/lib/lrutree.h
proxy/cache_actions.c
proxy/common.c
proxy/common.h
proxy/cs_actions.c
proxy/metacd_http.c
resolver/hc_resolver.c
resolver/hc_resolver.h
resolver/hc_resolver_internals.h
sqliterepo/election.c
sqlx/sqlx_service.c
tests/unit/test_lrutree.c
tests/unit/test_meta2_backend.c

Prior to this set of commits, the LRU cache only managed random accesses in O(log(n)) via a balanced tree, and O(1) to the oldest and earliest items.
There was no "last access time" on items, and such notion has to be managed externally. This was done nearly for every use of the LRU.
So this has been integrated for the sake of simplicity.

Integrates TTL directly into the LRU

---

meta2v2/meta2_backend.c
meta2v2/meta2_backend.h
meta2v2/meta2_backend_internals.h
meta2v2/meta2_server.c
sqliterepo/replication.c
tests/unit/test_meta2_backend.c

This prevents opening the database in most cases, and thus saves IO.

m2: add a cache of DB entries required for M2_PREP

---

cluster/conscience/conscience_srvtype.c

Avoids locking a service known by the conscience when it is stamped with a "tag.first" by a proxy that never saw it. This happened when you stop a proxy, let services expire, start the proxy.

conscience: considers tag.first only if service unknown

---

core/oiocfg.h
meta0v2/meta0_backend.c

Force the meta0 slaves to restore the whole database from the master
which is far quicker than using the standard replication mechanism
when a large part of the database has changed.

m0: speed up replication, increase oio-meta0-init timeout

---

metautils/lib/lb.c

Uses the local PRNG instead of the libc's rand(), with its guarantee on
the uniform distribution over a given range.
This should lead to better random and should fix the apparent preference
for the first item.

metautils/lb: uses the local PRNG, uniform distribution

---

cluster/conscience/conscience_srvtype.c
cluster/conscience/conscience_srvtype.h
cluster/module/module.c
cluster/module/module.h
metautils/lib/utils_strings.c
tools/oio-bootstrap.py

The option is 'lock_at_first_register' and is on by default.
It must be specified per service type, e.g.:
param_service.meta0.lock_at_first_register=false

conscience: option to unlock scores by default (fix #612)

---

core/http_internals.h
core/oio_sds.h
core/proxy.c
core/sds.c
core/tool_roundtrip.c

Allows a client application to know the about how the content has been split. Useful to align ranges on metachunks borders.

core: exposes the metachunks boundaries

---

proxy/common.c

restores the 'noredirect' option when crawling services

proxy: Fixes /admin/status

---

etc/bootstrap-17COPIES.yml
etc/bootstrap-3COPIES-11RAWX.yml
etc/bootstrap-3COPIES-3RAWX.yml
etc/bootstrap-BACKBLAZE.yml
etc/bootstrap-EC.yml
etc/bootstrap-SINGLE.yml
tools/oio-bootstrap.py

When zookeeper is set to 'false', it overrides any zookeeper config from
any other file specified before on the CLI. To avoid giving to much
importance to the order of configs, let's leave zookeeper untouched when
not concerned.

oio-reset.sh: zookeeper untouched when not concerned

---

tests/functional/conscience/test_lb.py

The error was because the proxy shuffle all elements of the list after the conscience return the slots.
Now, the test is testing if there are 3 fast slots and 1 slow slots, not testing only the first and last element port

tests/functional/conscience/test_lb.py : correct test_choose_4_slot

---

oio/common/storage_method.py

This will avoid many object creations,
and reduce impact of a memory leak in PyECLib.
https://bitbucket.org/kmgreen2/pyeclib/issues/65/ecdriver-init-destruct-might-leak-memory

python api: fix StorageMethod cache

---

cluster/lib/gridcluster.c
cluster/lib/gridcluster.h
core/ext.c
core/headers.c
core/oio_sds.h
core/oiocfg.h
core/oioext.h
core/sds.c
etc/bootstrap-SLAVE.yml
etc/bootstrap-WORM.yml
meta2v2/meta2_filters.h
meta2v2/meta2_filters_check.c
meta2v2/meta2_filters_extract.c
meta2v2/meta2_gridd_dispatcher.c
metautils/lib/comm_message.c
metautils/lib/metautils_macros.h
oio/api/base.py
oio/api/object_storage.py
oio/cli/clientmanager.py
oio/cli/shell.py
oio/cli/storage/client.py
oio/common/constants.py
oio/container/client.py
proxy/metacd_http.c
tests/functional/m2_filters/test_filters.py
tools/CMakeLists.txt
tools/oio-bootstrap.py
tools/oio-flush-all.sh
tools/oio-reset.sh
tools/oio-travis-tests.sh

To use admin mode, two methods are available
with the python cli, you can use the --admin param to pass in admin mode
with the C SDK, you can use oio_sds_configure with the OIOSDS_CFG_FLAG_ADMIN flag
to enable worm mode, you must add worm=true inside your oio-reset config file.
to modify the state of the NS (slave or master mode), you must add state='master' or 'slave' inside the oio-reset config file
By default, the state is in stand_alone mode.
This PR add also a new script named oio-flush-all, who flush all caches of meta0, meta1 and meta2.

oio/core: adding master / slave state and admin requests

---

core/http_internals.h
core/proxy.c
core/sds.c

core: The properties indicate in upload are set in the upload_commit step

core: modify set_properties and get_properties to respect new format

---

meta2v2/meta2_backend.c
meta2v2/meta2_macros.h
meta2v2/meta2_utils.c
meta2v2/meta2_utils.h

Count the number of entries in "contents" table of each container
and save it under key "sys.m2.objects" in admin table.
Next step is to count object per storage policy.

m2: implement simple object counter

---

cluster/tools/gridcluster.c
oio/cli/admin/client.py
oio/cli/admin/cluster.py
oio/conscience/client.py
setup.cfg

New commands : 
openio cluster list --local -> show all local services of cluster 
openio cluster unlock <service> <addr> (--score <score>) -> unlock the service given in the command with the score <score> 
openio cluster local conf -> print to stdout the namespace configuration values locally configured
openio clear flush <service> -> flush all services of the service type

oio/cli: add oio-cluster command into openio client

---

cluster/lib/gridcluster.c
core/oio_sds.h
core/sds.c
metautils/lib/metautils_macros.h
oio/api/object_storage.py
oio/cli/admin/client.py
oio/cli/admin/cluster.py
oio/conscience/client.py
setup.cfg
tools/oio-bootstrap.py

* In C API, by default, chunks are shuffled before reading disregarding the score. Now it is possible to start reading the highest scored one.
* In Python API,  when reading a replicated content, we swap the highest scored chunk with one selected by a weighted random algorithm, to avoid harassing the same rawx.
* New `openio cluster lock` command.

Balance reads

---

core/lb.c
etc/bootstrap-3COPIES-11RAWX.yml
etc/bootstrap-EC.yml
etc/bootstrap-SINGLE.yml
etc/bootstrap-SLAVE.yml
etc/bootstrap-WORM.yml
meta1v2/meta1_backend_services.c
metautils/lib/lb.c
metautils/lib/lrutree.c
metautils/lib/metautils_svc_policy.h
metautils/lib/utils_svc_policy.c
oio/api/directory.py
oio/directory/client.py
oio/rdir/client.py
tests/functional/api/test_directory.py
tools/oio-bootstrap.py
tools/oio-rdir-harass.py

There was a problem with the location of the service for which
the load-balancer was queried.
This requires conscience configuration modifications:
* `rdir` pool must require a rawx (`targets=1,rawx;1,rdir`, or just don't define the pool, it will be autoconfigured);
* `service_update_policy` for rdir must be `rdir=KEEP|1|1|user_is_a_service=rawx`.

core,m1: fix 'user_is_a_service' option handling (2)

---

oio/cli/admin/cluster.py
setup.cfg

Now able to wait services to be scored, and to unlock services with given type.
Fixes #690 
(oio)me@home 70 # OIO_NS=OPENIO openio cluster wait -t meta2
+-------+----------------+-------+
| Type  | Service        | Score |
+-------+----------------+-------+
| meta2 | 127.0.0.1:6008 |    86 |
| meta2 | 127.0.0.1:6009 |    86 |
| meta2 | 127.0.0.1:6010 |    86 |
+-------+----------------+-------+

CLI: `openio cluster` completed

---

core/ext.c
tests/unit/CMakeLists.txt
tests/unit/test_core_sysstat.c

* Fixes segfault happening when no cache of major/inor numbers *and* file not found
* Fixes uninitialised variables
* adds a unit test

Fix core's sysstat crash when monitoring a not found directory

---

oio/api/ec.py
tests/unit/api/test_ec.py

this caused ranges in EC to be broken
changed the corresponding unit test to check Range header in GET request
TODO we should tests more ranges

Python API: fix Range header for GET requests in EC

---

cluster/lib/gridcluster.c
core/oiostr.h
core/str.c
core/tool_roundtrip.c
oio/cli/clientmanager.py
oio/cli/storage/obj.py
oio/common/autocontainer.py
tests/unit/test_str.c
tools/oio-bootstrap.py

* Conscience option renamed for beauty purpose: `FLATNS_*` options become `flat_*` options
* C code simplified to ease Python bindings
* NewPython "HashedcontainerBuilder" wrapping the former C code
* New CLI option "--auto" that ignores the given container and computes it with the content name

Autocontainer in the "Flat NS" style

---

oio/cli/clientmanager.py
oio/cli/storage/obj.py
oio/common/autocontainer.py
tests/functional/cli/storage/test_obj.py

* The `<container>` parameter is now optional if `--auto` option is provided.
* It is possible to list all objects put in autocontainers with `openio object list --auto`. `--marker` and `--limit` options are taken into account.

CLI improvements for autocontainers

---

sqliterepo/election.c

We don't know the source of these orphan Zookeeper nodes, but you can test their proper deletion with oio-election-smudge.py on a fresh namespace:
```
openio container create X
oio-election-smudge.py NS meta2 -d `openio reference list X -f value -c Host | head -n 1` &
sleep 5
curl -XPOST "http://localhost:6000/v3.0/NS/admin/leave?ref=X&type=meta2&acct=myaccount"
sleep 1
openio object create X /etc/magic
```
In the logs you should see lines talking about "Rogue ZK node".

Prevent election storm (fix #611)

---

core/oiocfg.h
sqlx/sqlx_service.c
tools/oio-bootstrap.py

A service with the XXX service type now overrides its ZK url (found at `zookeeper` in /etc/oio/sds.conf) with an other value found at `zookeeper.XXX` in /etc/oio/sds.conf. If the specific value is not set, the main value is left untouched.
The main `zookeeper` value is still necessary for the zk-bootstrap.py script to run.

meta{0,1,2},sqlx: allow alternate ZK url in /etc/oio/sds.conf

---

core/oiocfg.h
etc/bootstrap-udp.yml
server/internals.h
server/network_server.c
server/network_server.h
server/slab.h
server/transport_gridd.c
sqliterepo/synchro.c
sqliterepo/synchro.h
sqlx/sqlx_service.c
tools/oio-bootstrap.py

Only enabled when explicitely allowed in the `/etc/oio/sds.conf` files, with en entry like this in the namespace's section
[MyNS]
udp_allowed = true
The goal is to reduce the overall load with a simpler protocol for dummy tasks.

UDP preferred for DB_USE requests

---

CMakeLists.txt
core/oiolog.h
gridd/main/srvalert.c
metautils/lib/comm_converter.c
metautils/lib/gridd_client.c
metautils/lib/utils_addr_info.c
proxy/common.c
proxy/common.h

For once in this project's lifetime, this happens intentionally.
* The enbugging is used to prove the `oio-proxy` can manage the bugs.
* We slow the client operations down when a redirection loop is detected, to let a legit election reach a final state.

Adds bugs, and makes the clients slower

---

BUILD.md
CMakeLists.txt
core/sds.c

Add -DOIO_USE_OLD_FMEMOPEN=1 on cmake commandline to use old fmemopen implementation. This will workaround a bug with glibc >= 2.22, but unfortunately won't compile with stripped glibc.

core: add OIO_USE_OLD_FMEMOPEN to choose fmemopen implementation

---

sqliterepo/gridd_client_pool.c
sqliterepo/gridd_client_pool.h
sqliterepo/synchro.c

**TL;DR** we expect here the queue to be drastically peeled in case of storms, and old RPC immediately avoided.
For invalid peers addresses, we spare computation time and abort the RPC attempt immediately, then avoiding the GError structure to be leaked.
Bounds to 4s the delay in the queue of waiting RPC. After that, there is no RPC attempt, it will be aborted.

sqliterepo: fix a memleak, bound the waiting time

---

sqliterepo/election.c
sqliterepo/synchro.c

Introduces a pause when a change in the list (peers or master) has been detected while in PRELEAD/PRELOST state. We wait all the pending GETVERS are done before re-listing the peers and re-resending GETVERS.

Restrain election storms

---

proxy/cache_actions.c
resolver/hc_resolver_internals.h
sqliterepo/election.c
sqliterepo/internals.h
sqliterepo/synchro.c
sqliterepo/synchro.h
tests/unit/test_sqliterepo_election.c
tools/oio-tool.c

* better management of complete disconnections
* asynchronous management of Zookeeper completion hooks
* enlarged default numbers: bases kept open in cache, timeout for elections retrial, service urls in cache
* new `/forward/info` oio-proxy route

Improve robustness of election FSM

---

meta1v2/meta1_backend_services.c
meta2v2/meta2_server.c
proxy/common.c
proxy/metacd_http.c

Affect `proxy`, `meta1`, `meta2`.
Closes #698

Flush the cache of the resolver on CODE_RANGE_NOTFOUND errors

---

core/ext.c

Avoids as possible to count I/O ops after the monotonic time snapshot.

core: make finer stat.io measurement

---

meta0v2/meta0_server.c
metautils/lib/gridd_client.c
metautils/lib/gridd_client.h
metautils/lib/gridd_client_ext.c

The metautils leak specially affects all the sqliterepo-based services.
It happens under heavy loads, when replication RPC generate timeouts on the client side (e.g. "queued for too long").

Fix memory leaks (meta0, metautils)

---

core/oiourl.h
core/sds.c
meta2v2/meta2_backend.c

- improve `fmemopen()` binary mode workaround
- set size and object count database entries at container creation
- improve some error messages
- add comment on `oio_url_set_id()`

Various fixes required (or not) by oiofs

---

proxy/m2_actions.c
proxy/path_parser.c

The ALREADY_EXISTS erorr while auto-creating a container (during a content creation) is not considered as an error.

Fix the concurrent auto-creation of a container

---

BUILD.md
core/oiocfg.h
metautils/lib/gridd_client.c
metautils/lib/gridd_client.h
server/internals.h
server/network_server.c
sqliterepo/synchro.c

From a default of 2s, use now 0.5s for GETVERS and 0.25s for USE.

sqliterepo: Shorten the cnx timeout for USE and GETVERS requests

---

meta1v2/meta1_backend_internals.c
metautils/lib/gridd_client.c
proxy/common.h
proxy/reply.c

A final token is added on each accesslog linne, stored in the arbitrary part.
```
e={"status":406,"message":"Directory error: no such user"}
```

proxy: Mention the source error in the access log

---

meta2v2/meta2_backend.c

In addition, a bit of harmless renamings.
Fixes #852 and #853.

meta2: Add a check on each container state before handling it.

---

tools/oio-tool.c

http://shinken.readthedocs.io/en/latest/15_development/pluginapi.html
As suggested by @vdombrovski the output is in milliseconds. I can change this to seconds to be coherent with the **check_tcp** plugin.

oio-tool: format output like Shinken plugins (fix #836)

---

oio/cli/admin/client.py
oio/cli/admin/directory.py
oio/cli/admin/volume.py
oio/rdir/client.py
tests/functional/api/test_directory.py

Keep this for a class whose purpose is administration and deployment.
The "link" in the directory (meta1) is supposed already donbe in a "bootstrap" step of the deployment. Only the lazy creation of the rdir DB is performed.
When then avoid any relinking to a (supposedly) rdir service, then avoiding the mistake to link a rawx service. De facto fixes #854 .

oio/rdir: Do not link from the simple rdir client

---

core/oiocfg.h
rawx-apache2/src/mod_dav_rawx.c
rawx-apache2/src/rawx_event.c

Controlled by the "rawx_events" in sds.conf
Disabled by default.

rawx: Allow to turn off the event source

---

bin/oio-blob-rebuilder
oio/blob/rebuilder.py
oio/cli/admin/volume.py
oio/content/content.py
oio/content/ec.py
oio/content/plain.py
oio/rdir/client.py
oio/rdir/server_db.py
setup.cfg
tests/unit/rdir/test_backend.py
tests/unit/rdir/test_server.py

* Create databases just after linking to rawx
* Add `openio volume assignation` subcommand to display current rdir links
* Add option `--max-per-rdir` to `openio volume admin bootstrap` to enforce the maximum number of databases per rdir service
* Keep rdir databases open when they are created
* Allow rebuild of a chunk on the original rawx

Rdir and blob-rebuilder improvements (fix #855)

---

core/ext.c
meta1v2/meta1_backend.h
meta1v2/meta1_backend_services.c
proxy/dir_actions.c
proxy/metacd_http.c

Prior to this pull request, the relinking of a directory entry was broken in both the proxy and the meta1.

proxy: expose the relink of a directory entry

---

sqlx/sqlx_service.c

* Review the sequence of variable de-allocations
* Reduce the timeout to 10s (was 30s)

Improve sqliterepo-based services shutdown sequence

---

oio/blob/rebuilder.py

The periodic report now have that shape: 
> 12697 7F9500C47CD0 log INFO status=127.0.0.1:6008 started=2017-03-09_16:08:14 passes=1 errors=1 chunk/s=109.54 byte/s=0.00 elapsed=0.01 (rebuilder: 0.00%)
The final report has that shape: 
> 12697 7F9500C47CD0 log INFO DONE=127.0.0.1:6008 elapsed=0.02 errors=2 chunk/s=57.69 byte/s=0.00 elapsed=0.01 (rebuilder: 0.39%)
The date is reported in a space-less format, and the volume is now printed on each report line.
Fix #720

oio-blob-rebuilder: name the reported fields in the log

---

tests/functional/conscience/test_lb.py

Explicit refreshes are sent to the proxy instead of waiting in the hope that the periodically scheduled refresh happens.
This will help the tests to pass on Travis-CI.

tests/func: Reduce the adherence to the time

---

oio/api/object_storage.py
oio/cli/storage/container.py
proxy/actions.h
proxy/m2_actions.c
proxy/metacd_http.c
tests/functional/container/test_container.py

The command "openio container create <container>" used to send a request for every
container in the list to create it.
Now the command check the number of containers and use a specific request to ask for the
creation of all the containers.

Add an option to create many containers in on go

---

core/lb.c
core/oiolb.h
meta1v2/meta1_server.c
meta2v2/meta2_server.c
metautils/lib/lb.c
proxy/common.h
proxy/lb_actions.c
proxy/metacd_http.c
sqlx/sqlx_service.c
sqlx/sqlx_service.h
tests/functional/api/test_directory.py
tools/oio-bootstrap.py

Fix #815 
* The `core/lb` feature now has a way to easily expire services that disappear from the conscience
* `meta2` now uses the same code as meta1, both use the expiration feature.
* `proxy` uses a slight variant of that code

Allow the services to expire in the LB pools

---

oio/api/io.py
oio/api/object_storage.py
oio/api/replication.py
tests/unit/api/test_replication.py

Starting now, only the chunks to be saved should be returned by the WriteHandler implementation, and this might depend on the implementation.
Prior to this fix, the filtering of failed chunks was performed whatever the implementation. We now do it in each subclass where it is necessary.

oio: Fix the behavior upon rawx errors.

---

core/http_put.c
core/sds.c

When #919 fixes things in the python API, the current PR fixes them in the C SDK.
Only the chunks that succeeded are now saved in the container.
And it is up to the container to trigger a rebuild action on the content to make it comply with the storage policy.

Improve the management of cnx errors while requesting RAWX.

---

oio/api/object_storage.py
tests/unit/api/test_objectstorage.py

Le's make the python API avoid chunks with dirty attributes (i.e. out of a quorum).

oio: Improve the behavior of download of contents with bad chunks

---

oio/blob/indexer.py
oio/blob/rebuilder.py

Add the date of the start and end of both command.
Add name to the value of the fields of the oio-blob-indexer logs,
like the one oio-blob-rebuilder is using.

Modify log format of oio-blob-rebuilder and oio-blob-indexer (fix #880)

---

core/http_put.c

It has been reported by @fvennetier that libcurl==7.53 poorly manages the TCP_FASTOPEN when it is supported but disabled by a 0 set in /proc/sys/net/ipv4/tcp_fastopen

core: Disable TCP_FASTOPEN toward rawx

---

core/http_put.c
core/sds.c
core/tool_sdk.c

There are use cases of oio_sds_s handles shared among threads. Let's resist and be functional under such circumstances.

core/sds: Make the oio_sds_s handle thread-safe

---

proxy/m2_actions.c

Also, allow empty bodies in the POST /container/create requests.
Fix #915

Default user's autocreation while creating containers

---

tools/oio-travis-tests.sh

Prove useful under certain temporary circumstances, not necessary in the
mainstream conditions.

Travis-CI: Stop dumping the /var/log at exit

---

core/log.c
sqliterepo/repository.c
sqliterepo/sqlite_utils.c
sqliterepo/sqlite_utils.h
sqliterepo/version.c

Better management of modified/deleted entries in the cache of the `admin` table.

sqliterepo: Reduce the amount of IO ops with a smarter cache

---

metautils/lib/utils_sockets.c
sqliterepo/election.c

In addition, also fix the detection of the delay that prevent TFO to be retried too fast after a "not supported" error.

Fix a deadlock when shutting down meta* services

---

meta0v2/meta0_backend.c

meta0: Fix a memory leak happening during the bootstrap

---

core/http_put.c

Let each service manage the signals the way it decided.
Impacts the oio-sds C SDK and the meta* services while they contact the proxy.

core/curl: Avoid intercepting signals upon curl errors

---

core/oiocfg.h
metautils/lib/metautils_sockets.h
metautils/lib/utils_sockets.c
proxy/metacd_http.c
sqlx/sqlx_service.c

TCP_FASTOPEN improved the behavior on small-to-medium loads but it seems to induce some side effects such an extra load when strongly stressing the services. Let's deactivate it by default and continue the job of improving our support.

Add a general trigger around the activiation of TFO

---

metautils/lib/gridd_client.c
metautils/lib/metautils_syscall.h
metautils/lib/utils_sockets.c
metautils/lib/utils_syscall.c
sqliterepo/synchro.c

We don't need the ugly SIGPIPE to be raised, especially if we make the necessary to ignore it.

Prevent SIGPIPE signal when writing to a closed connection

---

core/lb.c
tests/unit/test_lb.c

Check how many unbalanced repartitions we get on platforms where
there is not enough locations to ensure a perfect data securing.
For example, when there is 3 host with 4 services each, and we ask
for 9 services, the load-balancer sometimes returns 4 services from
the first host, 2 from the second and 3 from the third,
whereas we expect 3, 3 and 3.

New LB tests for tight platforms

---

all-requirements.txt
bin/oio-account-server
tests/functional/rdir/test_server.py
tools/CMakeLists.txt
tools/oio-travis-tests.sh
tools/oio-wrap.sh

It avoids restarting processes, and this took a while on Travis.

tests/functional: Rely on the deployed rdir for the tests

---

core/sds.c
metautils/lib/comm_message.c
metautils/lib/metautils_macros.h

When the RPC mode is not set to "admin", don't tell "admin=false"
because this is the default.

Avoid filling the RPC with useless fields

---

oio/api/object_storage.py
proxy/common.h
proxy/m2_actions.c
proxy/reply.c
tests/functional/container/test_container.py

Allow the "good old unitary requests" as a fallback for their respective bulk requests, when unsupported. Also manage batches of excessive size.

Bulk requests: Fixed memleak, easier integration

---

oio/api/ec.py
tests/unit/api/test_ec.py

This failure was manifesting with 'list index out of range' errors
happening in oio/api/ec.py.

Fix EC failure after rawx connection failure

---

oio/api/base.py
oio/api/ec.py
oio/api/object_storage.py
oio/api/replication.py
oio/blob/client.py
oio/cli/storage/obj.py
oio/common/client.py
oio/common/http.py
oio/common/utils.py
oio/container/client.py
oio/content/content.py
oio/content/ec.py
oio/content/factory.py
oio/content/plain.py
proxy/m2_actions.c
tests/functional/m2_filters/test_filters.py
tests/unit/api/test_objectstorage.py

Rework oio/container/client.py so that `headers` is used only where necessary, and `kwargs` are passed where needed.

Python API: fix requests ids and kwargs API traversal

---

oio/api/ec.py
rawx-apache2/src/mod_dav_rawx.c
rawx-apache2/src/rawx_config.h
rawx-apache2/src/rawx_internals.h
rawx-apache2/src/rawx_repo_core.c
rawx-apache2/src/rawx_repository.c
rawx-apache2/src/rawx_req_info.c

* More secure rollback() of uploads
* Atomic chunk creation
* MD5 compared between the request and the local computation: only effective when both are present.
* Local MD5 computation can be siabled by a configuration directive `grid_checksum: on|off|smart` where `smart` activates it when meaningful (i.e. not when managing an EC/ chunk).

rawx: Improvement and fixes around the uploads of chunks

---

bin/oio-blob-registrator
meta2v2/generic.c
meta2v2/generic.h
meta2v2/m2gen.py
meta2v2/meta2_backend.c
meta2v2/meta2_backend.h
meta2v2/meta2_filters_action_container.c
meta2v2/meta2v2_remote.c
meta2v2/meta2v2_remote.h
oio/blob/registrator.py
oio/container/client.py
oio/content/content.py
proxy/m2_actions.c

Prior to this pull request, the oio-blob-register was only able to force the refresh of the chunks in their corresponding container.
Now the operator can choose, on the CLI, between:
* refreshing the chunk (--upgrade) being only effective if the chunk is already registered
* inserting it (--insert) with no effect is yet present
* checking it's presence (not yet implemented)

oio-blob-register: Make the action configurable

---

oio/cli/storage/obj.py

The whole command shouldn't fail at the first error that occurs, if several contents have been specified.

cli: Fix the behavior of `openio object create` upon an error

---

oio/api/base.py
oio/api/object_storage.py
oio/cli/clientmanager.py
oio/cli/shell.py
oio/cli/storage/container.py
oio/cli/storage/obj.py
tests/functional/cli/storage/test_obj.py

* Organize module imports to make the CLI faster to load (not that much).
* Add `--max-versions` option to `openio container create` and `openio container set`.
* Add `--max-versions`, `--quota` and `--storage-policy` options to `openio container unset`.

CLI: organize imports, add versioning options

---

CMakeLists.txt

To use it:
$ cmake -DENABLE_CODECOVERAGE=TRUE ../oio-sds
$ make
$ make coverage_init
$ make test
$ make coverage
Result will be available in coverage_results directory
Heavily inspired from https://cmake.org/pipermail/cmake/2010-March/036063.html
An example of coverage is available at http://www.murlock.org/coverage_results/

Add coverage target for cmake

---

sqlx/sqlx_service.c

This happens in a weird case where the peers saved in a base do not include the service currently serving the base...

Fix segfault in sqliterepo

---

core/internals.h
core/oiostr.h
core/str.c
meta0v2/meta0_server.c
meta1v2/meta1_server.c
meta2v2/meta2_backend.c
metautils/lib/metautils_bits.h
sqliterepo/election.c
sqliterepo/election.h
sqliterepo/replication.c
sqliterepo/replication_dispatcher.c
sqliterepo/repository.c
sqlx/sqlx_service.c

Each time the application locates for peers, whatever the level, ensure...
* the output pointer is set to something
* an array is used when no error occur (even if it is empty)
* NULL is never used to represent an empty list of peers.
* NULL is used when an error returned

sqliterepo: Add a security belt around fetches of the peers

---

.travis.yml
CMakeLists.txt
tests/func/CMakeLists.txt
tools/oio-travis-tests.sh
tox.ini

To achieve Python coverage, a new environment was added in `tox.ini` to have global coverage.
For each Python test, command is set to `coverage run -p` instead of python.

Add Python coverage

---

oio/api/ec.py
oio/api/replication.py
oio/common/green.py
tests/unit/api/test_ec.py
tests/unit/api/test_replication.py

Users of our API don't have to be bothered by eventlet.

Convert eventlet Timeout to OioTimeout

---

CMakeLists.txt

Add variable CODECOV_PATTERN_TO_IGNORE to remove some
autogenerated libs from coverage.
For example:
set(CODECOV_PATTERN_TO_IGNORE ${CMAKE_BINARY_DIR}/core/client_variables.c '${CMAKE_BINARY_DIR}/metautils/lib/*.c')

CMake: add CODECOV_PATTERN_TO_IGNORE

---

.travis.yml
CMakeLists.txt
meta0v2/CMakeLists.txt
meta2v2/CMakeLists.txt
metautils/lib/CMakeLists.txt
metautils/lib/codec.h
sqliterepo/CMakeLists.txt
sqlx/CMakeLists.txt
tests/unit/CMakeLists.txt
tools/oio-reset.sh
tools/oio-travis-tests.sh

Bring the Travis execution from 22 minutes to 9 minutes.
* Split each test suite into a specific Travis job
* Add one specific test suite for code coverage, that is not systematically scheduled because it sequentially run all the test suites
* Remove the log folding because this is not needed anymore

travis: Speed up the test suites

---

oio/account/backend.py
oio/account/server.py
tests/functional/account/test_backend.py
tests/functional/account/test_server.py

Replace the lock/unlock by a script to redis.
Since a script is atomic it should prevent the problem of tilted redis that left lock.

Account: send a lua script to redis to update containers.

---

meta2v2/meta2_utils.c
tests/unit/test_meta2_backend.c

The memory leak was caused by a GSList not freed in each node of sorted_content.metachunks

Meta2: fix memory leak in m2db_check_content

---

core/sds.c
meta0v2/CMakeLists.txt
sqliterepo/CMakeLists.txt
tools/oio-travis-tests.sh

Due to a variable mismatch, only the first chunk of the first metachunk was referenced in meta2 database.

Fix upload with C client with more than one metachunk

---

core/ext.c
core/oiourl.h
core/url.c
meta1v2/meta1_gridd_dispatcher.c
meta2v2/meta2_filters_extract.c
proxy/m2_actions.c
proxy/metacd_http.c
tests/func/test_weird_chars.c
tests/unit/test_url.c

Only core, meta2 and proxy are now protected (I hope, please correct me if I miss something).
Path and version are always checked with oio_url_check.
Namespace is only checked if current one is passed as argument.

Check validity of oio_url_s instance

---

.travis.yml
README.md
test-requirements.txt
tools/oio-travis-tests.sh

This patch enable use of codecov.io with:
- C coverage
- Python coverage
- Badge integration

Enable codecov

---

oio/api/object_storage.py
oio/common/client.py
oio/container/client.py
tests/functional/api/test_objectstorage.py

This patch introduces a new parameter for object_create to support
appending data to an existing object.
If object doesn't exist, it is created, only if container exists as
flag append can not be used at same time with flag autocreate.

oio/api: allow append operations

---

etc/apache2/streaming-apache.conf-sample
etc/wsgi/admin.wsgi-sample
oio/container_streaming/app.py
oio/container_streaming/streaming.py
tests/functional/container_streaming/test_container_streaming.py
tools/oio-bootstrap.py

Allow to download a container with support of HTTP Ranges
Limitations:
- Ranges must be aligned with 512-byte boundaries
- no support of multipart range
- Container is not yet frozen
Still missing:
- support Head with Range
- include versions of object
- include deleted object
Example:
```
$ s3cmd mb s3://test1
$ s3cmd put /etc/passwd s3://test1
$ s3cmd --add-header=UserAdd:value modify s3://test1/passwd
$ ./streaming.py
$ curl -I http://localhost:5001/test1
HTTP/1.0 200 OK
Content-Length: 7168
X-Blocks: 14
Content-Type: application/tar
Accept-Ranges: bytes
Server: Werkzeug/0.12.1 Python/2.7.13
Date: Wed, 07 Jun 2017 14:59:25 GMT
$ curl http://localhost:5001/test1 -H "Range: bytes=0-3583" > a.tar
$ curl http://localhost:5001/test1 -H "Range: bytes=3584-7167" >> a.tar
$ tar --xattrs -xf …
```

Download container as archive

---

meta0v2/meta0_backend.c
meta1v2/meta1_backend_internals.c
proxy/m2_actions.c
proxy/reply.c
sqliterepo/election.c
sqliterepo/internals.h
sqliterepo/replication_dispatcher.c
sqliterepo/repository.c
sqliterepo/sqliterepo.h
sqlx/sqlx_service.c
sqlx/sqlx_service.h

* Systematically reset a timer when restarting an election cycle, the timer that allows the client to detect the election is stalled  
* Avoid leaving uninitialized DB files, erroneously autocreated

Fix elections troubles

---

core/lb.c
tests/functional/container/test_container_backup.py
tests/unit/test_lb.c

Detect when we are in a "tight" situation, where we need to pick more
services than the number of different locations. In such case, disable
the distance checks, and rely only on the theoretical maximum number of
services per location.

Fix load balancing on tight platforms

---

conf.json
core/oiourl.h
core/sds.c
core/url.c
oio/api/object_storage.py
oio/blob/client.py
oio/common/constants.py
oio/common/http.py
oio/content/content.py
oio/content/ec.py
oio/content/factory.py
oio/content/plain.py
oio/ecd/app.py
rawx-apache2/src/rawx_chunk_update.c
rawx-apache2/src/rawx_internals.c
rawx-apache2/src/rawx_repo_core.c
rawx-lib/src/attr_handler.c
rawx-lib/src/rawx.h
tests/functional/audit/test_audit_storage.py
tests/functional/blob/test_blob.py
tests/functional/content/test_content.py
tests/functional/content/test_ec.py
tests/functional/content/test_plain.py
tests/functional/crawler/test_storage_tierer.py
tests/functional/rdir/test_indexer.py
tests/unit/api/test_ec.py
tests/unit/api/test_replication.py

Modify the client to send the header X-oio-chunk-meta-full-path:Acct/Container/Name
Convert the header to the xattr oio.user:Acct/Container/Name=""

Rawx: Add xattr oio_version and full_path fix(#948, #1020)

---

tests/functional/container/test_container_backup.py
tools/oio-bootstrap.py

During tests of range download, Apache configuration was
too short to handle lot of small requests.
oio-bootstrap now add MaxRequestsWorkers to allow Apache to spawn
new children to support charge.
This patch also enforce test by testing HTTP return code when
downloading range.

bootstrap: increase MaxRequestsWorkers

---

.travis.yml
tools/oio-bootstrap.py
tools/oio-travis-tests.sh
tox.ini

Command for coverage for [testenv:func] was skipped.
Also add coverage call for WSGI application but coverage stills missing for some WSGI application, at least they are now in report.
Remove the verbose mode of codecov

coverage: enable it for WSGI and nosetests

---

oio/container/backup.py
tools/oio-travis-tests.sh

Fix a subtile issue with `set -e` and `&&`: some tests were launched with `&&` but `set -e` option didn't stop the script when an intermediate compound failed.

tools: fix travis test

---

tests/functional/blob/test_blob.py

Do not enforce the order of paths in the response header.

tests: relax "full-path" chunk tests

---

all-requirements.txt
oio/account/client.py
oio/api/base.py
oio/cli/admin/client.py
oio/cli/admin/directory.py
oio/cli/shell.py
oio/common/client.py
oio/common/exceptions.py
oio/common/http.py
oio/conscience/agent.py
oio/conscience/checker/http.py
oio/conscience/client.py
oio/container/client.py
oio/directory/client.py
oio/event/consumer.py
oio/event/filters/volume_index.py
oio/rdir/client.py
tests/unit/api/__init__.py
tests/unit/api/test_directory.py
tests/unit/api/test_objectstorage.py
tests/unit/common/test_exceptions.py

To improve the event agent, I change `HttpApi` class. Because `HttpApi` use `requests` only for connections pools. To manage connections pools, `requests` use `urllib3` with `PoolManager`. Now, I call `PoolManager` directly.
With the benchmark `oio-event-benchmark`, we increase the speed by more than 60%.
- before:
```shell
$ ./build/tools/event-benchmark/oio-event-benchmark OPENIO CHUNK_NEW -q
Linking fake rawx address with the fake service address...
Starting the fake service...
Sending 100 fake events
100 events sent (errors: 0) in 0.105229 seconds, 950.308375 events/sec
Sending 950 fake events
950 events sent (errors: 0) in 0.641872 seconds, 1480.045866 events/sec
Sending 1480 fake events
1480 events sent (errors: 0) in 1.021468 seconds, 1448.895120 events/sec
Sending 1448 fake events …
```

HttpApi: Remove 'requests' to use 'urllib3' directly

---

all-requirements.txt

Manages a known problem with python 2.7.13 and eventlet 0.21.0

Update the python requirements (eventlet versions)

---

oio/api/base.py
oio/event/filters/volume_index.py

I change exceptions of `HttpApi` to have a better trace
```
OioNetworkException: HTTPConnectionPool(host=u'127.0.0.1', port=6028): Max retries exceeded with url: /v1/rdir/push?vol=127.0.0.1%3A6022&create=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5eda0d9850>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',))
```

Improve exception handling in HttpApi and event-agent

---

all-requirements.txt
oio/api/ec.py

When computing range download to chunks, results was stored inside
a Dict. This result was used with an iterator and order of chunks was lost.
The fix replace this Dict by a OrderectDict.

oio/api: Fix invalid ranges

---

oio/cli/admin/cluster.py
proxy/cs_actions.c
tests/functional/conscience/test_conscience.py
tests/utils.py

Fix #1091 
Unlocks services 4096 by 4096 (instead of 1 by 1, instead of all at once).

cli: Efficiently unlock batches of services

---

meta1v2/meta1_backend.h
meta1v2/meta1_backend_internals.c
meta1v2/meta1_backend_services.c
meta1v2/meta1_gridd_dispatcher.c
meta1v2/meta1_prefixes.c
meta1v2/meta1_remote.c
meta1v2/meta1_remote.h
proxy/dir_actions.c
proxy/m2_actions.c
tests/functional/container/test_container.py
tests/functional/reference/test_directory.py
tests/unit/test_meta1_backend.c

* backend: Implement the idempotent variant of M1_LINK
* backend: Simplifies the logic
* backend: Drop the support of the DRYRUN flag where it is useless
* remote: adapt to the backend options
* proxy: adapt to the meta2 remote
* test: Add a unit test for the backend
* test: Alter a test to match the new meta1 API (link calls return the
whole set of services,no tthe addition)
* test: More random ids, for less collisions

container sharding: step3, allocate shards in meta1

---

conf.json
oio/api/base.py
oio/common/client.py
oio/common/exceptions.py
server/network_server.c
tests/functional/api/test_proxy_client.py

Catch error 503 from proxy and retry with exponential backoff.
If the proxy is still busy, throws the `ServiceBusy` exception.

Python API: handle ''ServiceBusy" exceptions returned by oio-proxy

---

oio/account/client.py
oio/api/object_storage.py
oio/blob/auditor.py
oio/blob/indexer.py
oio/blob/mover.py
oio/blob/rebuilder.py
oio/blob/registrator.py
oio/common/client.py
oio/conscience/agent.py
oio/container/backup.py
oio/content/content.py
oio/content/factory.py
oio/crawler/storage_tierer.py
oio/event/consumer.py
oio/event/filters/account_update.py
oio/rdir/client.py

Manage loggers to not recreate a logger unnecessarily and to share a logger

Python API: share one logger instance between all classes instances

---

oio/common/autocontainer.py
tests/unit/common/test_autocontainer.py

The `RegexContainerBuilder` class allows to capture parts of an object name to build the name of the container where the object will be uploaded.

Python API: use regex to build container names

---

oio/common/client.py
tests/functional/api/test_proxy_client.py

Add number of attempts for each request in the event of `ServiceBusy`

Python API: allow to set "request_attempts" for each request

---

conf.json
sqliterepo/election.c

Can be triggered back using 'sqliterepo.election.nowait.enable' (managed configuration), false by default until we discover where the transient timer (`when_unstable`) is not reset as expected.

sqliterepo: Inhibit the test on stalled election

---

oio/container/backup.py
tests/functional/container/test_container_backup.py

A regression was introduced during f616a41ec as same var size was
used to store HTTP Content-Length and object uploaded to SDS.
This commit fix that by introducing new variable name (req_size) for
HTTP Content-Length and enforce that total data consumed are now
same size as HTTP.
It also enforce test to ensure all objects put are really restored.
This PR will closes #1143

oio/backup: fix invalid restore

---

oio/cli/admin/volume.py
oio/cli/storage/account.py
oio/cli/storage/container.py
oio/common/utils.py
tests/functional/cli/storage/test_account.py
tests/functional/cli/storage/test_container.py
tests/unit/common/test_utils.py

See #1140 
```
$ openio account show myaccount
+------------+------------+
| Field      | Value      |
+------------+------------+
| account    | myaccount  |
| bytes      | 354.605KB  |
| containers | 7          |
| ctime      | 1503937834 |
| metadata   | {}         |
| objects    | 1          |
+------------+------------+
$ openio container show test
+----------------+--------------------------------------------------------------------+
| Field          | Value                                                              |
+----------------+--------------------------------------------------------------------+
| account        | myaccount                                                          |
| base_name      | 0A826191AEA91051840F917C5AB84187594E012BB33FD600259D271ADBA1B296.1 |
| …
```

CLI: Make 'account/container show' human readable

---

oio/common/client.py
tests/unit/common/test_client.py

See #1151
```
>>> from oio import ObjectStorageApi
>>> storage = ObjectStorageApi("OPENIO", endpoint="127.0.0.1:6000")
>>> storage.container_create("myaccount", "test")
True
>>> storage.object_list("myaccount", "test")
{'prefixes': [], 'objects': [], 'properties': {}, 'system': {'sys.m2.usage': '0', 'sys.peers': '127.0.0.1:6016,127.0.0.1:6015,127.0.0.1:6018', 'sys.type': 'meta2', 'sys.m2.version': '0', 'sys.name': '0A826191AEA91051840F917C5AB84187594E012BB33FD600259D271ADBA1B296.1', 'sys.m2.init': '1', 'sys.ns': 'OPENIO', 'sys.user.name': 'test', 'sys.m2.ctime': '1504172359662371', 'sys.m2.objects': '0', 'sys.account': 'myaccount'}}
>>> storage.container_list("myaccount")
[['06EE0', 0, 0, 0], ['ff54f3f94ea54506a4ffe81b24a8841e', 0, 0, 0], ['test', 0, 0, 0]]
>>> …
```

Python API: Add consistency to the endpoint

---

all-requirements.txt
oio/blob/client.py
oio/common/http.py
tests/functional/conscience/test_conscience.py
tests/functional/conscience/test_lb.py
tests/functional/container/test_container.py
tests/functional/rdir/test_server.py
tests/functional/reference/test_directory.py
tests/utils.py

The requests module in `BlobClient`  is  replaced by urllib3.
It should have been replaced by the `httplib` used by `ChunkReader` but for a first step it was replaced by `urllib3`

Tests, BlobClient: replace requests by urllib3

---

oio/api/object_storage.py
oio/container/backup.py
oio/container/client.py
tests/functional/api/test_objectstorage.py
tests/functional/container/test_container_backup.py

- Rework restore code (split code in several methods of a dedicated object)
- Enforce Unit Test to detect 500 errors when no RAWX is available
- Add lock to avoid concurrency restoration requests
- In case of connectivity issues, store position to allow continue restoration at last know position (more test needed to cover all cases)
- Add support of truncate for Python API
- Add support to overwrite a chunk for Python API (used at this time for truncate use)

Refactor backup restoration code

---

all-requirements.txt

The commit 4e9cb87ad3 has removed requests from `all-requirements.txt` but
`oio/api/backblaze_http.py` still use it. The `test_container_backup.py`
also depends on it at this time but dependency could be moved later in `test-requirements.txt`.
It was unseen during CI as requests is a dependency of codecov.

Requirements: add requests

---

metautils/lib/utils_service_info.c
tests/unit/test_addr.c
tests/unit/test_str.c

The ID of services was truncated, this is now fixed thanks to @fvennetier (commit cherry-picked from 4.x to 4.0.x)

Backport a fix in the generation of ID of services

---

CMakeLists.txt
cache/cache_memcached.c
cache/cache_memcached.h
cache/cache_multilayer.c
cache/cache_redis.c
cache/cache_redis.h
tests/common/test_cache_abstract.c
tests/func/test_cache_memcached.c
tests/func/test_cache_redis.c
tools/CMakeLists.txt
tools/oio-bootstrap.py
tools/oio-flush-all.sh
tools/oio-reset.sh
tools/oio-travis-tests.sh
tools/oio-unlock-all.sh

* Remove the useless management of a configurable prefix to the binary tools
* Fix missing copyright mentions:
* Adds Vincent Vinel in cache related elements.
* Adds Conrad Kleinespel in oio-bootstrap.py

cmake: Get rid of the configurable prefix to CLI tools

---

oio/account/client.py
oio/blob/indexer.py
oio/event/consumer.py

Avoid polluting the log when OioNetworkError exceptions are raised. All the useful information is container in the message (which peer, which protocol library)

Print lighter warnings on network errors

---

rdir/rdir.c
rdir/routes.c
rdir/routes.c.rl
tests/functional/rdir/test_server.py
tests/utils.py

Also log the error that occurs in the configured output, often syslog in production deployments.
But also dump that error on stderr, for an easier diagnosis.

rdir: Stop the rdir when its basedir is absent

---

metautils/lib/metautils_containers.h
metautils/lib/utils_containers.c
server/network_server.c
sqliterepo/election.c

Despite the error returned, the pointer is queued.
Consider reading the implementation [here](https://git.gnome.org/browse/glib/tree/glib/gthreadpool.c#n518) because the documentation is error prone.

Fix the management of the return of g_thread_pool_push()

---

resolver/hc_resolver.c

.. so that by default we keep an unlimited cache.
We already have another variable to mention we don't want to cache items.

resolver: Consider max==0 as the infinity

---

conf.json
core/internals.h
meta1v2/meta1_remote.c
sqlx/sqlx_service.c
tests/unit/CMakeLists.txt
tests/unit/test_variable_period.c

Make the meta* services react to the same set of (recently fixed) rules to expires the items in the cache of the resolver. The items 
Also configure the expiration of the bases in the caches of unused bases in sqliterepo.

Improve the configurability of the cache-related background tasks

---

conf.json
proxy/actions.h
proxy/cache_actions.c
proxy/metacd_http.c
server/transport_gridd.c

Explode each of the `/forward/*` routes into separate routes with the proper verb (POST or GET when meaningful)

proxy: Make a better use of the route parser

---

oio/common/daemon.py
oio/conscience/agent.py
oio/conscience/client.py
oio/conscience/stats/meta.py

During the CI tests, especially when the load is high on large deployments, the tests sometimes fail because the conscience-agent is too slow to exit. It may even take several minutes to do so. It appears it remains sticked on loop-failing HTTP requests to the oio-proxy (that is down), retried periodically.
In this context, we:
* Allowed the proxy to react the same way to more exit signals
* Broke a main "while True" loop with the help of a flag, unset when an exit signal is received
* Forbid urllib3 to do retries when registering services

Speed the exit process of the conscience-agent

---

bin/oio-check-services
oio/check_service/check_meta2.py
oio/check_service/check_rawx.py
oio/check_service/common.py
setup.cfg

Add script to make a `GET/PUT/DELETE` on each service (`rawx` and `meta2`)
```shell
$ oio-check-services OPENIO
RAWX 127.0.0.1:6024 OK
RAWX 127.0.0.1:6023 OK
RAWX 127.0.0.1:6022 OK
META2 127.0.0.1:6015 OK
META2 127.0.0.1:6018 OK
META2 127.0.0.1:6016 OK
META2 127.0.0.1:6017 OK
```
```shell
$ gridinit_cmd -S ~/.oio/sds/run/gridinit.sock -c stop OPENIO-rawx-1
DONE OPENIO-rawx-1        Success
$ oio-check-services OPENIO
RAWX 127.0.0.1:6024 OK
RAWX 127.0.0.1:6023 OK
RAWX 127.0.0.1:6022 FAIL
META2 127.0.0.1:6015 FAIL
META2 127.0.0.1:6018 FAIL
META2 127.0.0.1:6016 FAIL
META2 127.0.0.1:6017 FAIL
```
```shell
$ gridinit_cmd -S ~/.oio/sds/run/gridinit.sock -c stop OPENIO-meta2-1
DONE OPENIO-meta2-1        Success
$ oio-check-services OPENIO
RAWX 127.0.0.1:6024 OK
RAWX 127.0.0.1:6022 OK
RAWX …
```

oio-check-services: Add script to check services

---

meta2v2/meta2_filters_action_content.c

When checking a content is OK, the error message was prepared but not freed when no error is found.

meta2: Fix a memory leak

---

metautils/lib/comm_converter.c
metautils/lib/description.asn
tests/unit/CMakeLists.txt
tests/unit/test_nsinfo.c

Ease the migration from 3.x to 4.1.x with thee reintroduction of obsolete fields in ASN.1 messages, as optional fields.
Attempt to fix #1218

Add missing fields in ns_info

---

metautils/lib/comm_converter.c
metautils/lib/description.asn
tests/unit/CMakeLists.txt
tests/unit/test_nsinfo.c

Partial fix for #1218.
Upgrade path from 3.x to 4.x:
1. migrate the services and the proxy
2. goto 3.
3. migrate the conscience

Allow a proxy >4.1.4 to chat with a conscience <4.0.0

---

sqliterepo/election.c

If `sv` parameter is NULL, we handle it the same way as when it is empty
array: we go to the LEAVING_FAILING state.

sqliterepo: handle zk timeout during LISTING state

---

core/var.c
metautils/lib/gridd_client.c

It frees memory when the process exits and its libraries are unloaded. It helps fixing memory leaks with tools like valgrind.

Implement missing library destructors

---

conf.json
sqliterepo/gridd_client_pool.c
tests/unit/CMakeLists.txt
tests/unit/test_gridd_client_pool.c

Use the same principle as TCP Congestion Control ([RFC5681 Section 3.1](https://tools.ietf.org/html/rfc5681#section-3.1))
- Slow start : finished event doubles the limit
- Congestion avoidance : finished event increases slowly the limit
- Timeout : set the limit to minimum

Change active clients limit according to timeout

---

oio/cli/storage/obj.py

(cherry picked from commit 60ada2a07a5300f20c00e97f45471cd577acd3b0)

CLI: fix object create error handling

---

rawx-lib/src/attr_handler.c
tests/functional/api/test_objectstorage.py

* Fixes #1261 with a new norm for the xattr list of links.
* Ensure the backward compatibility with the 4.1.x branch: allow to read old-style links but only write new links.

Manage long contents paths

---

conf.json
sqliterepo/cache.c

A TTL set to 0 (via `sqliterepo.cache.ttl.hot` or `sqliterepo.cache.ttl.cold`) now means the base won't expire.
We lose no functionnality:
* The default value is now non-zero but so small that the periodic bg task that expires the bases will nearly always expire any base it meets.
* It is still possible to turn the bg-task completely down via `server.periodic_decache.period = 0`

Alter the meaning of TTL=0 on cached DB

---

sqliterepo/replication_dispatcher.c

Fix a possible desynchro. of the rowid value, in the admin table, with a potential overlap with the primary key of that table.

Sqliterepo: Fix replication error on admin table

---

meta2v2/meta2_utils.c
oio/api/object_storage.py
oio/cli/storage/obj.py
proxy/m2_actions.c
tests/functional/api/test_objectstorage.py

When using delimiters, the pagination used to return several times the same prefix, leading to infinite loops in client applications.

Fix object list pagination

---

metautils/lib/gridd_client_ext.c
oio/api/ec.py

Some `CODE_AVOIDED` errors were not properly transmitted in meta1 client, preventing it from looping over replicas.

Fix faulty service avoidance, improve error messages

---

meta2v2/meta2_utils.c
tests/unit/test_meta2_backend.c

This is to prevent a data loss happening when a high-level retry
(from a client) is executed before a low-level retry (from the proxy).

Refuse objects versions older than latest

---

metautils/lib/gridd_client.c
metautils/lib/gridd_client.h
metautils/lib/gridd_client_ext.c
metautils/lib/gridd_client_ext.h
proxy/cache_actions.c
proxy/common.c
proxy/common.h

Also:
* Slight simplification of gridd_client
* Slight code reorg between metautils and proxy (gridd_client_exec_and_concat_string() was only used in the proxy)

Disable the avoidance of faulty peers for the forwarded RPC from the proxy

---

metautils/lib/utils_service_info.c
sqlx/sqlx_service.c

The PR allows the `tag.up` to be well considered by the sqlx/meta* services, to decide which service is down or not.
In addition, fix a possible segfault happening when reloading the list of down peers, that was introduced at commit 5c4ecc2d58baf58e095b3e4d41b05c7e30cbef21. The error diddn't show up because the list was always empty due to a bad parsing of the `tag.up` flag in each service description.

Fix the parsing of boolean service tags

---

all-requirements.txt

The (fairly new, from 2 days ago) plyvel 1.0.0 broke it, so stick with
the working one until further investigated & fixed...
Error was:
plyvel/_plyvel.cpp: In function 'int __pyx_f_6plyvel_7_plyvel_parse_options(leveldb::Options*, bool, bool, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*, PyObject*)':
plyvel/_plyvel.cpp:3341:22: error: 'struct leveldb::Options' has no member named 'max_file_size'
__pyx_v_options->max_file_size = __pyx_t_4;
plyvel 1.0.0 requires leveldb 1.20, and our Travis build installs
libleveldb1 1.15.0 (and there is no superior version in this
distribution), thus we are stuck with plyvel<1.0.0.
We should use plyvel>=0.9,<1.0.0 in case someone creates updates over
the 0.9 version.

Temporarily disable new plyvel versions which don't build

---

metautils/lib/utils_task.c
proxy/common.h
proxy/cs_actions.c
proxy/metacd_http.c
sqliterepo/cache.c
sqliterepo/synchro.c

* Prevent bad values (thaks to @fvennetier in commit 6461c95)
* Ensure a deadline in RPC sent during periodic tasks executions
* Fix the deadlines toward the conscience, from the proxy

Fix the management of deadlines

---

meta2v2/meta2_backend.c
tests/functional/container/test_container.py

When creating a container, status was left unset.
It was only updated when creating a snapshot

Set status field during meta2 database creation

---

conf.json
meta2v2/meta2_backend.c
meta2v2/meta2_backend.h
meta2v2/meta2_filters_action_content.c
meta2v2/meta2_macros.h
meta2v2/meta2_utils.c
meta2v2/meta2_utils.h
oio/cli/container/container.py
oio/common/easy_value.py
tests/functional/content/test_content_versioning.py
tests/unit/test_meta2_backend.c

Delete exceeding versions when adding a new alias

---

Variables.md
conf.json
core/http_put.c
core/oio_sds.h

Allow configuration of connection and overall request timeouts to rawx
services, from sds.conf configuration file.

C API: allow configuration of rawx timeouts

---

oio/api/base.py
oio/common/http.py
tests/functional/rdir/test_server.py

By default, urllib3 doesn't use backoff when retries are
enabled. This commit introduce parameter to update it.
Following urllib3 documentation, backoff is used after second
try and will sleep by using formula:
{backoff factor} * (2 ^ ({number of total retries} - 1))

Python API: expose backoff_factor option

---

oio/common/autocontainer.py
tests/unit/common/test_autocontainer.py

In oio-swift's regexcontainer middleware, we will need to catch an exception coming from the `RegexContainerBuilder` class. Before this patch, the exception was of the generic type `ValueError`.

Python API: create NoMatchFound exception for RegexContainerBuilder

---

sqliterepo/synchro.c

During election, if connection on peer fails, error message is not freed.

sqliterepo: fix small memory leak

---

sqliterepo/election.c

[ 50%] Building C object sqliterepo/CMakeFiles/sqliterepo.dir/election.c.o
cd /build/openio-sds-4.1.13/obj-arm-linux-gnueabihf/sqliterepo && /usr/bin/arm-linux-gnueabihf-gcc  -DG_LOG_DOMAIN=\"oio.sqlite\" -DHAVE_ACCEPT4 -DHAVE_SOCKET3 -DHAVE_SOCKLEN_T -DOIOSDS_PROJECT_VERSION=\"master/4.1\" -DTHREADED -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -D_REENTRANT -Dsqliterepo_EXPORTS -I/build/openio-sds-4.1.13/obj-arm-linux-gnueabihf/sqliterepo -I/build/openio-sds-4.1.13/obj-arm-linux-gnueabihf/metautils/lib -I/build/openio-sds-4.1.13/obj-arm-linux-gnueabihf/metautils/asn1c -I/build/openio-sds-4.1.13/obj-arm-linux-gnueabihf -I/build/openio-sds-4.1.13 -I/build/openio-sds-4.1.13/sqliterepo -I/usr/include/glib-2.0 …

Fix 32 bits build, for example armhf

---

oio/cli/admin/directory.py
tools/oio-reset.sh

- fix logic error in `openio directory bootstrap` command
- improve documentation
- split usage of `openio directory bootstrap` from `oio-reset.sh`

Fix logic error in 'openio directory bootstrap'

---

oio/api/io.py

Python API: display request ID in more warning messages

---

oio/directory/meta0.py

... instead of the type inferred from a JSON message.
Without this, a pure integer service location would raise an exception.

python: Force the location to be instances of 'str'

---

meta0v2/meta0_backend.c
meta1v2/meta1_prefixes.c

Avoid failing miserably on the assertion mentioned in the subsequent backtrace. But it doesn't explain why the meta1 starts serving requests before having a full set of prefixes from a meta0 service. 
```
Thread 1 (Thread 0x7fec9ab9a700 (LWP 15285)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007feca48eaf5d in __GI_abort () at abort.c:90
#2  0x00007feca53a681d in g_assertion_message () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007feca53a68aa in g_assertion_message_expr () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007feca446ca23 in meta0_utils_array_get_urlv (byprefix=0x0, b=0x7fec9ab99636 <incomplete sequence \355>) at /home/jfs/public_git/github.com/jfsmig/oio-sds/meta0v2/meta0_utils.c:133
#5  0x00007feca5862124 in …
```

The the startup of meta1 services

---

oio/conscience/agent.py
oio/conscience/stats/http.py
oio/conscience/stats/meta.py
server/network_server.c
server/network_server.h
server/transport_gridd.c
server/transport_gridd.h
sqliterepo/repository.c
sqlx/sqlx_service.c

* oio-conscience-agent: Consider errors from /stat requests a enough to mark the service down
* server/transpport_gridd.c: Keep track of IO errors/success timestamps, if the last activity is an error or if the timestamp of the last success is not recent (stalled), consider the volume is faulty.
* server/transpport_gridd.c: Deny alll but specific local requests with a code 503 that won't fail the general call, and allow the caller to retry on peers.
* sqlx/sqlx_service.c: Implement a probe in a background thread that periodically checks for directory and file creations.
known limitation: the support of the REQ_PING is really limited in the conscience-agent, the return code is not even checked. We could save the REQ_STAT request if we immediately consider the service is down. then we could …

meta*: Deny requests upon I/O errors

---

sqliterepo/election.c
sqliterepo/replication_dispatcher.c
sqliterepo/repository.c

Avoids spamming DB_GETVERS requests when an election happens on a fresh DB.
Only impacts freshly deployed platforms.

sqliterepo: Ensure a DB exists before kicking the election FSM off

---

oio/api/object_storage.py
tests/unit/api/test_objectstorage.py
tests/unit/content/test_content.py

Before this commit, only files, buffers or bare generators were allowed.

Python API: allow sourcing object data from iterable

---

meta2v2/meta2_backend.c

Decache prepare data when freezing a container.
Bugfix Pull Request
meta2
```
openio 4.1.21.dev8
```
If we do not decache this data, meta2 will accept M2_PREP operations
even if the container is no more managed locally.
Decaching this data will force the next M2_PREP operation to re-cache
it, and this will fail because the container is frozen.

Decache M2_PREP data when freezing a container

---

Variables.md
conf.json
events/oio_events_queue.c
events/oio_events_queue.h
events/oio_events_queue_beanstalkd.c
events/oio_events_queue_buffer.c
events/oio_events_queue_buffer.h
events/oio_events_queue_fanout.c
events/oio_events_queue_zmq.c

Take into account the `events.common.pending.delay` configuration directive that allows to tune the buffering delay for the events. The configuration value is only considered at the startup of the services.
Prior to this patch, the configuration directive existed but was ignored. Its default value has been changed to match the default behaviour, for a seamless upgrade.
Enhancement
`oio_events_queue` that is indirectly used by `oio-meta1-server`, `oio-meta2-server`, `rawx`
```
4.1.21
```

events: Make configurable the buffering delay

---

bin/oio-meta1-rebuilder
bin/oio-meta2-rebuilder
core/ext.c
oio/rebuilder/blob_rebuilder.py
oio/rebuilder/meta1_rebuilder.py
oio/rebuilder/meta2_rebuilder.py
oio/rebuilder/meta_rebuilder.py
oio/rebuilder/rebuilder.py
proxy/common.c

- In the `proxy`, shuffle services if no preferred service
- Accept an input file for `oio-meta1-rebuilder` and `oio-meta2-rebuilder`
- For all rebuilder, reset the number of passes between each report
- `proxy`
```
openio 4.1.22.dev19
```

oio-meta*-rebuilder: Accept an input file

---

oio/cli/admin/directory.py
oio/rdir/client.py

Don't retry upon bootstrap if it's successful.
CLI
```
openio 4.1.22.dev29
```

CLI: Don't retry upon bootstrap success

---

oio/api/base.py
oio/blob/client.py
oio/cli/admin/directory.py
oio/common/http.py
tests/functional/api/test_proxy_client.py

Use only 'urllib3' imported with 'eventlet', otherwise the I/O of 'urllib3' is blocking.
- Python API
```
openio 4.1.22.dev33
```

Use only 'urllib3' imported with 'eventlet'

---

oio/content/content.py
oio/content/factory.py

Use the same blob client, so the same connection pool, for the content factory.
- Improvement Pull Request
- Python API
```
openio 4.1.22.dev34
```

Use the same blob client for the content factory

---

bin/oio-meta1-rebuilder
bin/oio-meta2-rebuilder

Fix the import of 'get_logger'.
```
openio 4.1.22.dev32
```

rebuilder: Fix the import of 'get_logger'

---

oio/api/ec.py
oio/api/io.py
oio/api/object_storage.py
oio/api/replication.py
oio/common/constants.py
tests/unit/api/__init__.py
tests/unit/api/test_ec.py
tests/unit/api/test_replication.py

Allow disabling client-side chunk checksums, to reduce CPU usage during upload.
Python API
```
openio 4.1.22.dev39
```
This modifications prepares a future evolution where the checksum algorithm will be selectable. Only `'md5'` (default) and `None` (disable client-side checksums) are supported at the moment.

Python API: allow disabling client-side chunk checksums

---

.travis.yml

Travis was using coverage on installed files and was ignored by codecov,
our python module will be used with `python setup.py develop` to fix that.
Coverage was not done
Python API
```
openio 4.1.22.dev38
```

tests: run coverage on more files

---

rawx-apache2/src/mod_dav_rawx.c
sqliterepo/election.c

Replace `strncpy` by `g_strlcpy` to avoid warnings with recent versions of GCC.
- rawx
- sqliterepo
```
openio 4.1.22.dev65
```
Errors were like
```
/home/fvennetier/src/public_git/oio-sds/sqliterepo/election.c:1066:3: error: ‘strncpy’ specified bound 65 equals destination size [-Werror=stringop-truncation]
strncpy(member->key, key, sizeof(member->key));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

rawx, sqliterepo: replace strncpy by g_strlcpy

---

.travis.yml
oio/cli/admin/cluster.py
tools/oio-reset.sh
tools/oio-travis-tests.sh
tools/oio-wait-scored.sh

Simplify `oio-reset.sh` to make a better use of `openio`.
Prior to this PR, `oio-reset.sh` used an archaic version of `openio cluster wait`. The rewrite required to adapt `cluster wait` but it now helps debugging the Travis CI with less (but unified) tools that propose a decent verbosity.
Rewrite `oio-wait-scored.sh` on top of the `cluster wait` subcommand of `openio`, for the sake of the backward compliance.
Enhancement
`oio-reset`
`4.1.21`

oio-reset: Simplify without `oio-wait-scored.sh`

---

sqliterepo/synchro.c

Dump the duration of the calls to the zookeeper client API.
Enhancement
`sqliterepo`
`1487a81864d35d17ad8ceee17eb3bfaf3a60719f` (current head of 4.1.x, to appear in the next 4.1.22)
Requires a build in `CMAKE_BUILD_TYPE=Debug` and the live option `server.log_outgoing=true` to be set.

sqliterepo/synchro: Dump the duration of the calls to ZK

---

.travis.yml
oio/api/object_storage.py
tests/unit/api/test_objectstorage.py

Fix kwargs hack in ObjectStorageApi preventing usage of
chunk_checksum_algo keyword.
Python API
```
openio 4.1.23.dev2
```

Python API: fix kwargs hack

---

tools/oio-bootstrap.py
tools/oio-reset.sh

Add an option `oio-reset.sh` and also to `oio-bootstrap.py` that configure a specific directory for the data of the services, instead of `~/.oio/sds/data`.
Enhancement
* `oio-reset` 
* `oio-bootstrap`
`4.1.21`

oio-reset: Allow a specific data directory for the services

---

oio/common/http.py

When `full_path` was a string (instead of a list or tuple), it was split
and re-assembled with commas between letters, triggering the creation of
many extended attributes on each chunk.
Thanks to @AymericDu 🦁
Python API
```
openio 4.1.23.dev13
```

Python API: fix chunk full_path conversion

---

oio/api/object_storage.py
proxy/m2_actions.c
tests/functional/container/test_container.py

Before that commit, the proxy used to return a 403 error code indifferently when a container or an object was missing. It is now returning a 404 error code, and the body of the response is telling if the container is missing (extended code 406) or the object is missing (extended code 420).
This applies to the following oio-proxy routes:
- `content/touch`
- `content/link`
- `content/set_properties`
- `content/del_properties`
- `content/copy`
The other routes were already responding as expected.
- oio-proxy
- Python API
```
openio 4.1.23.dev14
```

proxy, Python API: fix missing object error codes

---

oio/api/object_storage.py
oio/cli/storage/obj.py
oio/container/client.py
tests/functional/api/test_objectstorage.py
tests/functional/cli/storage/test_obj.py

The autocreate feature on API Python was hardcoded
Python API
```
openio 4.1.23.dev20
```
Default value of autocreate option is still True to avoid breaking backward compat

Python API: disable autocreate feature on demand

---

Variables.md
conf.json
core/http_put.c
metautils/lib/gridd_client.c
metautils/lib/gridd_client.h
metautils/lib/utils_sockets.c
metautils/lib/utils_syscall.c
sqliterepo/election.c
sqliterepo/gridd_client_pool.c
sqliterepo/gridd_client_pool.h
sqliterepo/synchro.c
sqliterepo/synchro.h
sqlx/sqlx_service.c
sqlx/sqlx_service.h
tests/unit/test_sqliterepo_election.c

Scratch even more CPU cycle involved in non-necessary code during critical sections:
* use shorter buffers for sockets
* useless pseudo-objects that made the code more complex
* useless debug code based on VTable, now only called in Debug builds
* defer syscalls involved in USE/GETVERS out of the critical sections  
`enhancement`
`metautils`, `sqliterepo`
```4.1.22```
With such a pach

metautils,sqliterepo: cheeseparing around wasted CPU cycles

---

core/ext.c
core/lb.c
core/sds.c
core/var.c
events/oio_events_queue_beanstalkd.c
meta1v2/meta1_backend_services.c
metautils/lib/lb.c
metautils/lib/utils_m1url.c
sqliterepo/hash.c

Avoid the `strcpy` and `strncpy` that do not ensure a trailing NUL character, and rather use `g_strlcpy` or even `memcpy` when the size is known.
`enhancement`
All of them
`4.2.0`

Ensure trailing '\0' when copying strings

---

cluster/module/server.c
proxy/cs_actions.c

Remove abusive assertions in the conscience (they validated input from the network :cry: )
Avoid sending the empty requests (despite being valid) from the proxy.
`bugfix`
`conscience`, `oio-proxy`
`4.2.0`

Conscience: Remove abusive assertions

---

tools/oio-reset.sh

Fix bootstrap of sds:
Restart of meta1 before rdir assignation was not checked before `openio volume boostrap` 
tools/oio-reset.sh
```
4.2.x
```

tools: fix oio-reset.sh with invalid bootstrap

---

tools/oio-travis-tests.sh

Call check tools after bootstrap
Travis tests / Check tools
```
4.2.x
```
Sometime the `oio-reset.sh` fails to bootstrap correctly, calling check tools will force us to fix bootstrap !

Check cluster state after bootstrap

---

tools/oio-reset.sh

Do not forget to clean the files in the data directory.
Prior to this patch, `~/.oio/sds/data` when cleaned even if the data directory was set to a different value.
`enchancement`
`oio-reset`
`4.2.0`

oio-reset: Cleanup the datadir when explicitly configured

---

sqliterepo/synchro.c

Fix a memory leak introduced at commit 0404fa1016b8fdc679970c4f5a1d9e97e4cdf627, when deferring UDP requests.
`bugfix`
`sqlitrepo`
`openio 4.1.23.dev50`

sqliterepo: fix a memory leak

---

sqliterepo/election.c

Ensure a deadline during some operations deferred to a pool of threads.
Sadly, the deadline is transmitted via a thread-local placeholder, the threads are not exclusive to the pool, the deadline was not explicitly set by the hook, thus a wrong deadline (in the past...) was sometimes considered. 
`bugfix`
`sqliterepo`
`openio 4.2.0.0b3.dev42`

sqliterepo/election: Ensure a deadline in background threads

---

sqliterepo/election.c

No need to complicate the logic with a "maybe-cached lookup" of the election peers, when we load the cache. So let's locate them from the reference.
`enhancement`
`sqliterepo`
`openio 4.2.0.0b3.dev42`

sqliterepo/election: Resolve the peers from the reference

---

core/http_put.c
core/sds.c

* Reduce the number of memory copies
* Work with larger buffers
* Only reload data when necessary
* Fix the management of timeouts, previously polled too often
`enhancement`
`core`
`openio 4.1.24`

Improve the throughput of the C client when uploading

---

server/transport_gridd.c

Adds a payload to replies on PING calls. With a marker in it, so that a simple TCP handler can look for that marker: "OK\r\n"
`enhancement` ... though I am not sure what it enhances, the entropy or the features.
`server`
`openio 4.1.24`

server: Ease the integration with prometheus exporters

---

oio/api/object_storage.py
tests/functional/api/test_objectstorage.py

Metadata was copied from original source without possibilities to change them
It is first part that fix modifying ACL of existing object on Swift / S3.
Like S3/Swift, we allow to copy or replace metadata through a dedicated parameter.
OIO
```
4.1.x
```
Behavior to adopt is not clear as API must allow to specify metadata or not (https://developer.openstack.org/api-ref/object-store/index.html#copy-object with `X-Fresh-Metadata` or https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html with `x-amz-metadata-directive`)
And it should not break container snapshot of `4.2`

Set properties when linking objects

---

oio/api/base.py
oio/blob/client.py
oio/common/http.py

Include network location in messages generated after urllib3 errors.
Exemple:
```
WARNING chunk delete failed: ('reqid=9BEC2A0DFCDC2D809092FA49FE2EC374, host=127.0.0.1:6023', '<urllib3.connection.HTTPConnection object at 0x7fcb35639d50>: Failed to establish a new connection: [Errno 111] ECONNREFUSED')
```
- Python API
```
openio 4.1.25.dev6
```

Python API: include netloc in urllib3 errors messages

---

oio/account/client.py

Do not early quote account name, the low-level HTTP client will encode the
whole query string.
Jira: OS-68
- Python API
- CLI
```
openio 4.1.25.dev8
```
Before:
```
> openio account create ?
+------+---------+
| Name | Created |
+------+---------+
| ?    | True    |
+------+---------+
> openio account show ?
+------------+------------+
| Field      | Value      |
+------------+------------+
| account    | %3F        |
| bytes      | 0B         |
| containers | 0          |
| ctime      | 1528709312 |
| metadata   | {}         |
| objects    | 0          |
+------------+------------+
```
After:
```
> openio account create ?
+------+---------+
| Name | Created |
+------+---------+
| ?    | True    |
+------+---------+
> openio account show ?
+------------+------------+ …
```

Python API: fix account client encoding

---

events/oio_events_queue.c
events/oio_events_queue.h
oio/blob/indexer.py
oio/event/evob.py
oio/event/filters/volume_index.py
oio/rdir/client.py
proxy/transport_http.c
rawx-apache2/src/rawx_event.c
rawx-apache2/src/rawx_event.h
rawx-apache2/src/rawx_internals.c

Transfer request ID in chunk events.
- Rawx forwards incoming request ID to outgoing events
- Event-agent uses this request ID when indexing chunks in rdir
- `oio-blob-indexer` identifies itself with a custom request ID header
Relates to #1346
- oio-event-agent
- oio-blob-indexer
- rawx
```
openio 4.1.25.dev6
```
Before:
```
Jun 07 17:32:00.893062 linux-cgzg OIO,NS,event-agent,1[39916]: 39916 7FCB35CBA370 log WARNING chunk delete failed: '<urllib3.connection.HTTPConnection object at 0x7fcb35639d50>: Failed to establish a new connection: [Errno 111] ECONNREFUSED'
```
After:
```
Jun 07 17:32:00.893062 linux-cgzg OIO,NS,event-agent,1[39916]: 39916 7FCB35CBA370 log WARNING chunk delete failed: ('reqid=9BEC2A0DFCDC2D809092FA49FE2EC374, host=127.0.0.1:6023', …
```

Transfer request ID in chunk events

---

core/tool_roundtrip.c
oio/cli/cluster/cluster.py
oio/cli/volume/volume.py
setup.cfg
tests/functional/cli/cluster/test_cluster.py
tools/oio-test-rebuilder.sh

Recent modifications in the C API made some chunk size related tests fail. This pull requests tries to fix them. Besides, the blob rebuilder tests were not using service IDs (mandatory for rdir related operations).
Also implement `openio cluster resolve`  command, necessary for blob rebuilder tests.
- C API
- CLI
- tests
```
openio 4.1.25.dev43
```

Fix chunk size and blob rebuilder tests

---

sqliterepo/election.c
sqliterepo/election.h
sqliterepo/internals.h
sqliterepo/synchro.c
sqliterepo/synchro.h
tests/unit/test_sqliterepo_election.c

During async operations deferred out of the critical section around FSM locks, instead of keeping the key to the election (and then requiring a lookup during the completion hook), we keep the direct pointer to the election member. 
This leads to smaller structures (the pointer is smaller than the name components), less CPU consumed, and requires refcounts to be handled well.
`enhancement`
`sqliterepo`
`openio 4.1.25.dev45`

sqliterepo: Keep pointer on election to avoid lookups

---

proxy/m2_actions.c

Before this commit, the maximum number of items deleted in one request was set by `proxy.bulk.max.create_many` instead of `proxy.bulk.max.delete_many`.
- Proxy
```
openio 4.1.27.dev7
```

proxy: use appropriate configuration for bulk delete

---

rawx-lib/src/attr_handler.c

When removing fullpath from rawx, the FD was not closed
rawx
```
4.2.0c0
```

rawx: close FD after removing fullpath xattr

---

test-requirements.txt
tests/functional/api/test_objectstorage.py
tools/CMakeLists.txt
tools/oio-dump-buried-events.py
tools/oio-travis-tests.sh

Tests using account service and event-agent were broken due to short timeout or trying to launch
test with while low score on account service 
tests
```
4.2.x
```
A new tool has been added to dump buried events on failure.

tests: fix broken tests against account service

---

server/network_server.c
tests/unit/CMakeLists.txt
tests/unit/test_network_server.c

We have seen the `bind_addr` of rdir server be set to `"127.0.0.1"` (with quotes) instead of `127.0.0.1`. In that case, the server is listening on `0.0.0.0` (thus all available network interfaces).
This PR fixes this behavior: an error is now returned.
Jira: OS-76
server
```
openio 4.2.1.dev2
```

Check bind address

---

oio/blob/indexer.py
oio/common/exceptions.py

Log an error, then sleep when no rdir assigned to local volume.
Fix #1512
oio-blob-indexer
```
openio 4.1.27
```

oio-blob-indexer: sleep when no rdir assigned to local volume

---

oio/api/ec.py
oio/api/replication.py

Do not print the whole stack trace on chunk timeout, just print the type and duration of the timeout.
Python API
```
openio 4.2.1.dev25
```

Python API: do not print stack on chunk timeout

---

oio/cli/container/container.py
tests/functional/cli/container/test_container.py

Fix OB-146
Create option to set container status using ``openio container set``
CLI
```
openio 4.2.1.dev25
```

CLI: Add --status option to container set

---

etc/event-handlers.conf-sample
oio/event/filters/webhook.py
setup.cfg

Add a webhook filter to event-agent.
oio-event-agent
Sends HTTP POST to configured endpoint in filter.
Sample
```
{
"eventId": "17",
"eventType": "storage.content.new",
"timestamp": 1530510293897297,
"data": {
"id": "025DE780FB6F050045A4AAFE741AAA9D",
"account": "myaccount",
"container": "1",
"name": "magic",
"md5Hash": "4561FADE4C4FC48E526E72871C470EEC",
"contentType": "application/octet-stream",
"policy": "SINGLE",
"chunkMethod": "plain/nb_copy=1",
"size": 24301,
"creationTime": 1530510293,
"modificationTime": 1530510293,
"version": 1530510293866760,
"metadata": {
"foo": "bar"
}
}
}
```

events: add webhook filter

---

oio/api/object_storage.py
oio/cli/container/container.py
oio/cli/object/object.py
oio/container/client.py
tests/functional/cli/container/test_container.py
tests/functional/cli/object/test_object.py

Allow use CID instead of container name to openio object and container command
Fix OB-143
CLI
```
openio 4.2.1.dev25
```

CLI: Allow CID for object and container commands

---

bin/oio-blob-mover
oio/blob/mover.py
oio/common/utils.py

Add options to `oio-blob-mover`.
- `oio-blob-mover`
```
openio 4.2.2.dev4
```
The mover can be used as a command line.
To run mover as daemon, you can specify `--daemon` option with the interval.
You can also move only some chunk with `--limit` option.
You can specify disk usage target with  `--usage-target` option.
`--generate-config` can be used to edit configuration file or create a new one with the values of other options.

Add options to blob-mover

---

metautils/lib/volume_lock.c

Fixes OS-83
```
openio 4.2.2.dev37
```

Specify expected IP on log when service xattr differ

---

bin/oio-blob-auditor
oio/blob/auditor.py

Change blob-auditor usage
oio-blob-auditor
```
openio 4.2.2.dev37
```
The auditor can be used as a command line.
To run auditor as daemon, you can specify `--daemon` option .
`--generate-config` can be used to edit configuration file or create a new one with the values of other options.

Update blob-auditor usage

---

proxy/common.c
proxy/common.h
proxy/m2_actions.c
proxy/sqlx_actions.c
proxy/transport_http.c
server/network_server.c

Properly reacts to "code=431" errors that indicate stale entries in the local cache of the `resolver` of the `oio-proxy`.
In addition, lowers the verbosity level of 2 traces.
`fix`
`oio-proxy`, `server`
`openio 4.2.2.dev47`

Decache stale entries and retry upon "base not managed" errors

---

server/transport_gridd.c

Allows an operator to inspect access logs of (previously hidden) traces, under DEBUG verbosity.
`enhancement`
`server`
`openio 4.2.2.dev47`

4.2.x access logs

---

oio/api/io.py
oio/common/http.py
oio/conscience/checker/http.py
oio/conscience/stats/http.py

We suspect an abnormal number of connections in `CLOSE_WAIT` state due to the fact that we do not immediately close the chunk connection after getting a 404 error (missing chunk). This pull request aims at fixing this problem.
- Python API
```
openio 4.1.27.dev12
```

Python API: close chunk connection after 404 error

---

CMakeLists.txt
metautils/lib/volume_lock.c
rawx-lib/src/attr_handler.c

libattr 2.4.48 removed `attr/xattr.h`, which contained roughly the same
things as `sys/xattr.h`.
- rawx
- metautils
```
openio 4.2.2.dev57
```

Adapt to recent libattr

---

Variables.md
conf.json
oio/common/http_urllib3.py
oio/conscience/checker/http.py
oio/conscience/stats/http.py
sqlx/sqlx_service.c

Hotfix 2
- conscience-agent: close connection to avoid keepalive issues
- meta*, sqlx: Restore the cache of the resolver
- conscience-agent
- meta*, sqlx
```
4.2.1.1
```

4.2.1.2: hotfix

---

rawx/handler_chunk.go
tools/oio-travis-tests.sh

Return the total size of the chunk in the [Content-Range header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range).
- `rawx`
```
openio 4.2.2.dev133
```

Return the total size in the Content-Range header

---

Variables.md
conf.json
sqlx/sqlx_service.c

In terms of performance, bring the 4.2.x in the row of the 4.1.x
`enhancement`
`sqliterepo`, `resolver`
`openio 4.1.25.dev45`

meta*, sqlx: Restore the cache of the resolver

---

oio/api/io.py
oio/common/storage_functions.py

In the case when the reader does not read data until the end, some connections where never closed.
Fortunately, this happened only when downloading EC objets.
Python API
```
openio 4.2.2.dev73
```

Python API: close chunks download connection

---

oio/common/autocontainer.py

Do not crash RegexContainerBuilder on empty capture groups.
Python API
```
openio 4.2.2.dev74
```

Python API: do not crash RegexContainerBuilder on empty capture groups

---

proxy/cache_actions.c
proxy/metacd_http.c
sqliterepo/replication_dispatcher.c

Reduce the access log volume for sqliterepo-based services and the proxy.
`enhancement`
`sqliterepo`, `oio-proxy`
`openio 4.2.2.dev70`

Reduce the log volume of well-known spammer services

---

sqliterepo/sqlite_utils.c
tests/functional/api/test_objectstorage.py

Check if cache entry is deleted to set a new entry.
Before:
```
$ openio container create toto --property test=1
+------+---------+
| Name | Created |
+------+---------+
| toto | True    |
+------+---------+
$ openio container unset toto --property test
$ openio container set toto --property test=1
$ openio container show toto
+----------------+--------------------------------------------------------------------+
| Field          | Value                                                              |
+----------------+--------------------------------------------------------------------+
| account        | myaccount                                                          |
| base_name      | 8B78B3245B74710F3ACC1BEF4978E621F5E764E01FFB5621D23C4EECA2B7BB3D.1 |
| bytes_usage    | 0B …
```

 sqlx: fix bug when overwriting a deleted property with the same value

---

etc/event-handlers.conf-sample
meta2v2/meta2_backend.c
meta2v2/meta2_backend.h
meta2v2/meta2_filters_action_content.c
meta2v2/meta2_gridd_dispatcher.c
meta2v2/meta2_utils.c
meta2v2/meta2_utils.h
meta2v2/meta2_utils_json_out.c
oio/api/object_storage.py
oio/blob/converter.py
oio/container/client.py
oio/event/filters/account_update.py
oio/event/filters/base.py
oio/event/filters/bury.py
oio/event/filters/content_cleaner.py
oio/event/filters/logger.py
oio/event/filters/notify.py
oio/event/filters/webhook.py
proxy/m2_actions.c
tests/functional/content/test_content.py
tests/unit/test_meta2_backend.c
tools/oio-bootstrap.py

Include object metadata in events for indexing:
- `content.new`: Use the properties in events
- `content.update`: Load the properties with the `webhook` filter (`event-agent`)
* It's a new event type
* It is sent when changing the properties
- `meta2`
```
openio 4.2.2.dev151
```

Include object metadata in events for indexing

---

oio/cli/directory/directory.py
oio/directory/meta0.py

- Accept 'long' base names when meta1_digits < 4.
- Check the number of replicas.
- Make it more verbose by default.
- CLI
```
openio 4.2.3.dev2
```

CLI: fix 'directory decommission'

---

meta2v2/meta2_utils.c
tests/unit/test_meta2_backend.c

If versioning is enabled, allow older versions than current version of object to support parallel
writs on same object for S3 
meta2
```
openio --version
4.2.2dev13
```
Please note that current version has drawback if max_version is 1: latest object written
always be kept even if oldest.

meta2: allow older versions

---

oio/rebuilder/blob_rebuilder.py

- Accept the 'beanstalk://' prefix for the beanstalk IP
- Stop if there is no response
- Check the beanstalk connection
- Reuse the beanstalk connection 
```
openio 4.2.3.dev40
```

oio-blob-rebuilder: Minor fixes

---

oio/account/server.py
oio/cli/object/object.py

Autocontainer object listings were truncated to the objects from the first 1000 containers. This pull request fixes the problem.
Jira: OS-164
- CLI
```
openio 4.2.3.dev7
```

CLI: fix 'openio object list --auto --no-paging'

---

oio/cli/object/object.py

If an error was raised while listing one of the containers, the whole loop on containers was interrupted. Now the listing will continue on the next container, and a message will state that the listing may be incomplete.
- CLI
```
openio 4.2.3.dev8
```

CLI: tolerate errors while listing objects from autocontainers

---

all-requirements.txt

Requests now supports urllib3 v1.24: https://github.com/requests/requests/blob/master/HISTORY.md#2200-2018-10-18
```
openio 4.2.4.dev6
```

Revert "Prevent urllib3 1.24"

---

meta2v2/meta2_utils.c

Fix a meta2 memory leak
meta2
```
4.2.3
```
Previous error was overwritten by next function call
(Please note that it seems that seems always triggered so fixing this may show other errors)

meta2: fix memory leak

---

oio/cli/object/object.py
oio/container/lifecycle.py
tests/functional/cli/lifecycle/test_lifecycle.py
tests/functional/container/test_lifecycle.py
tests/unit/container/test_lifecycle.py

Check the S3 tags instead of checking the properties when applying Lifecycle
- `lifecycle`
- `CLI`
```
openio 4.2.4.dev12
```

lifecycle: Check the S3 tags instead of checking the properties 

---

oio/container/lifecycle.py
tests/functional/container/test_lifecycle.py

- Allow to disable a rule
- Apply actions only to existing objects
- `lifecycle`
```
openio 4.2.4.dev32
```

lifecycle: Improve tests

---

oio/cli/lifecycle/lifecycle.py
oio/common/exceptions.py
oio/container/lifecycle.py
tests/functional/cli/lifecycle/test_lifecycle.py
tests/functional/container/test_lifecycle.py
tests/unit/container/test_lifecycle.py

- Prevent some configurations
* `Date` and `Days` must not be mixed in the same Rule
* `Date` in the Expiration action must be later than `Date` in the Transition action
* `Days` in the Expiration action must be greater than `Days` in the Transition action
* `NoncurrentDays` and `NoncurrentCount` must not be mixed  in the same Rule
* `NoncurrentDays` in the NoncurrentVersionExpiration action must be greater than `NoncurrentDays` in the NoncurrentVersionTransition action
* `NoncurrentCount` in the NoncurrentVersionExpiration action must be greater than `NoncurrentCount` in the NoncurrentVersionTransition action
- Allow multiple Transition and NoncurrentVersionTransition actions
- Apply Expiration and Transition actions only on the current version
- Format the Lifecycle configuration
- Add …

lifecycle: Prevent some configurations

---

.travis.yml
oio/__init__.py
oio/account/client.py
oio/account/server.py
oio/api/base.py
oio/api/object_storage.py
oio/blob/converter.py
oio/blob/indexer.py
oio/cli/account/account.py
oio/common/green.py
oio/event/beanstalk.py
oio/rebuilder/blob_rebuilder.py
test-requirements.txt
tests/functional/api/test_objectstorage.py
tests/functional/blob/test_auditor.py
tests/functional/blob/test_converter.py
tests/functional/blob/test_indexer.py
tests/functional/directory/test_refmapping.py
tests/functional/rdir/test_server.py
tests/utils.py
tools/oio-travis-tests.sh
tox.ini

- Remove an unused class in root package of Python API.
- Explicitly set `Connection: keep-alive` header in requests toward rdir, account and proxy. This should drastically reduce the number of connections made by some tools like `oio-blob-indexer`.
- Share a connection pool between several objects in `oio-blob-indexer`.
- Display each test's duration.
- Improve some tests using events: make them faster and more reliable.
- Python API
- oio-blob-indexer
- CI
```
openio 4.3.1.dev6
```

Clean Python API, improve oio-blob-indexer and some tests

---

meta2v2/meta2_utils.c
oio/api/object_storage.py
tests/unit/test_meta2_backend.c

Don't link a deleted alias to a content.
- `meta2`
```
openio 4.2.4.dev13
```
If the deleted alias is linked to a content, when we delete the object permanently the chunks are not deleted. You must also delete the deleted alias.

Don't link a deleted alias to a content

---

proxy/m2_actions.c

Instead of propagating the deadline error, tell the caller the listing
has been truncated, and let him continue on the next page of results.
Jira: OS-194
- proxy

proxy: handle deadline during long listing requests

---

meta1v2/meta1_backend_services.c
meta1v2/meta1_remote.c
proxy/dir_actions.c
tests/functional/api/test_directory.py
tests/unit/test_meta1_backend.c

The endpoint `/v3.0/reference/show` now returns the account and container names associated with the resolved reference, which would enable resolving the account / container associated with a certain CID.
The changes made are as follows:
- `oio-meta1-server`: The SRV_LIST reply now includes two additional prefixed strings that contain the container and account name.
- `meta1_remote`: The `meta1v2_remote_list_reference_services` functions intercepts the reply, extracts the account and container and fills the `oio_url_s` object accordingly, while returning the usual service list.
- `oio-proxy`: Returns two new fields `account` and `name` representing respectively the account name and the container name.
Before:
```
{
"cid": "D7D9B4A795FBFE86481F432B50BB04E4F9F826D0296A35E30062115651CF5D41", …
```

Resolve CID on reference show and return account and container names

---

oio/account/backend.py

Version 3.0.0 or the redis python sdk breaks code that depends on it.
Version 3.0.0 introduces breaking changes, namely anything passed to a command must be an integer, a bytes or a string. 
Previously, the API coerced True and False values into 'True' and 'False', and None into 'None'.
More changes may be required : [breaking changes list](https://github.com/andymccurdy/redis-py#upgrading-from-redis-py-2x-to-30)
`sdk`, more specifically, `oio/account/backend.py:AccountBackend`
```
openio 4.3.1.dev47
```
```
None
```

Cast boolean value to string representation before passing it on to redis

---

oio/rdir/client.py

When bootstrapping rdir databases for meta2 services, we used to actually create a rawx-oriented rdir database (by using the wrong URL). This is now fixed.
- Python API
```
openio 4.3.1.dev27
```

Python API: fix bootstrap of meta2 rdir databases

---

oio/cli/common/clientmanager.py
oio/cli/object/object.py
tests/functional/cli/__init__.py
tests/functional/cli/object/test_object.py

A namespace can now be used with several flatns configurations on separate account.
This commit allow CLI to interact with account that doesn't use default configuration.
CLI
```
4.2.4dev15
```
```
$ openio object create --auto --flat-bitlength 8 /etc/hosts
+-------+------+----------------------------------+--------+
| Name  | Size | Hash                             | Status |
+-------+------+----------------------------------+--------+
| hosts |  719 | 8408B8BFE97F012FB75067551367AACB | Ok     |
+-------+------+----------------------------------+--------+
$ openio object list --auto --flat-bitlength 8
+------------+------+----------------------------------+------------------+
| Name       | Size | Hash                             |          Version | …
```

CLI: allow to override autocontainer parameters

---

oio/cli/common/clientmanager.py
oio/directory/admin.py
oio/directory/meta.py
oio/directory/meta0.py
tools/oio-bootstrap.py

Fix loading of `meta1_digits` parameter and strengthen the `MetaMapping` code. Try to prevent dubious cases seen when running "directory decommission" operations, when the "old" peer set did not contain any of the previous peers, and thus the "new" peer set was empty.
- Python API
- CLI
```
openio 4.2.5.dev7
```

Strengthen 'directory decommission' operations

---

bin/oio-meta2-mover
oio/directory/meta.py
oio/directory/meta1.py
oio/rdir/client.py

When moving a meta2 database using the oio-meta2-mover, we have to remove the database from the previous meta2 peer's index.
`oio-meta2-mover`
```
openio 4.3.1.dev54
```
```
Nil.
```

Remove index entry when moving a meta2 database with oio-meta2-mover

---

oio/cli/volume/volume.py

We suggested the wrong alternative command to the deprecated one _(typo)_.
CLI
```
openio 4.3.1.dev52
```
```
None.
```

Fix deprecation warning to give correct alternative command

---

oio/api/object_storage.py
tests/functional/api/test_objectstorage.py
tests/unit/api/test_objectstorage.py

A new method will now return obj_metadata after creation of new object, including version.
The current method `object_create` was renamed as `object_create_ext` and return a forth value that represents metadata retrieved through `prepare` method.
A `object_create` has been introduced to kept API compatibility.
Required for OS-239
API
```
4.2.x
```

Python API: new method to create an object and retrieve version

---

oio/api/object_storage.py
oio/common/decorators.py
oio/container/client.py
tests/functional/api/test_objectstorage_properties.py

To be able to answer questions about the size of properties one can set on the different items, implement the following tests:
- Python API
```
openio 4.3.1.dev51
```

Implement tests for account, reference, container and object properties

---

meta2v2/meta2_backend.c
meta2v2/meta2_backend.h
meta2v2/meta2_filters_action_content.c
meta2v2/meta2_filters_extract.c
meta2v2/meta2_utils.c
meta2v2/meta2_utils.h
metautils/lib/metautils_macros.h
oio/api/object_storage.py
oio/cli/object/object.py
oio/container/client.py
oio/container/lifecycle.py
oio/content/factory.py
oio/crawler/storage_tierer.py
proxy/m2_actions.c
proxy/meta2v2_remote.c
proxy/meta2v2_remote.h
tests/functional/api/test_objectstorage.py
tests/functional/audit/test_audit_storage.py
tests/functional/cli/object/test_object.py
tests/functional/container/test_container.py
tests/functional/container/test_lifecycle.py
tests/functional/content/test_content.py
tests/functional/crawler/test_storage_tierer.py
tests/unit/container/test_lifecycle.py

Allow to change the policy of an object:
- must have the same hash and the same size
- keep the same `version`
- keep the same `ctime` and `mtime`
- `meta2`
- `proxy`
- Python API
- CLI
- `lifecycle`
```
openio 4.3.1.dev30
```

Allow to change the policy of an object

---

meta2v2/meta2_filters_action_content.c

Fix invalid events order when replacing an object
Thanks to contributors that exhibit this issue !
Fixes OS-253
meta2
```
4.2.x
```

meta2: fix order of events

---

sqliterepo/repository.c
sqliterepo/sqliterepo.h

Prior to this fix, when a dump fails in the repository and there is a retry in /tmp, the FDof the attempt file in the repository is not closed, thus keeping the file present on the filesystem until the process is stopped.
In addition, an unused function has been removed.
Bugfix!
`sqliterepo`
`openio 4.2.7.dev1`

sqliterepo: Fix a file descriptor leak

---

oio/directory/meta0.py

Check if the meta1 are present when bootstrapping
- Python API
```
openio 4.2.6.dev20
```

Check if the meta1 are present when bootstrapping

---

sqliterepo/repository.c
sqliterepo/sqliterepo.h
sqlx/sqlx_service.c

Clean stale DB dumps at the startup of any sqliterepo-based service, when it owns the lock on the base directory.
Bugfix
`sqliterepo`
`openio 4.2.6`

sqliterepo: Clean stale DB dumps

---

oio/api/ec.py
oio/common/exceptions.py
oio/common/storage_functions.py

When appropriate, raise `ServiceUnavailable` exceptions instead of the more generic `OioException`. This will help client programs trap these exceptions and display appropriate error messages.
- Python API
```
openio 4.2.7.dev16
```

Python API: document and use ServiceUnavailable exception

---

bin/oio-blob-rebuilder
oio/rebuilder/rebuilder.py

Default ratelimit tries to consume all events at start of
every second: when launching a lot of threads/instance, it
creates burst effects on cluster.
This commit introduce an option to add random wait after each chunk
rebuild, that take an argument to perform a [0, arg[ ms wait.
oio-blob-rebuilder
```
4.2.x
```

blob-rebuilder: use random delays to avoid request bursts

---

bin/oio-blob-rebuilder
core/lb.c

A bug might still happen in the `core/lb` logic, when a polling request is executed between the refresh and rehash steps of the update. When we detect it, we send a WARN trace in the journal. 
What we fix here is sending that WARN trace just once per minute.
There is no need to spam the log file.
`enhancement`
`core`
`openio 4.2.7.dev20`

core/lb: Avoid spamming with warnings

---

core/oiourl.h
core/url.c
metautils/lib/metatypes.h

4 small fields are now inlined, to avoid 4 memory alloc/free each time an oio_url_s is used (i.e. all the time in any service).
`enhancement`
`core`
`master` (`openio 4.2.7.dev24`?)

core: Inline small fields of the oio_url_s 

---

.travis.yml
etc/bootstrap-option-webhook.yml
etc/event-handlers.conf-sample
oio/event/consumer.py
oio/event/filters/webhook.py
tests/functional/event/test_webhook.py
tools/CMakeLists.txt
tools/oio-bootstrap.py
tools/oio-travis-tests.sh
tools/oio-webhook-test.py

Webhook was too aggressive on few events, with this PR, webhook will skip retrieving properties on `storage.content.deleted` event.
It also skip `storage.content.append` event due to invalid `content` received and no version available in event data, it is not possible to retrieve properties nor size. 
Fixes OS-235
- event-handler
```
4.3.x
```

Fix webhook and add tests

---

core/lb.c
core/oiolb.h
meta0v2/meta0_backend.c
meta2v2/meta2_backend.c
metautils/lib/lb.c
proxy/metacd_http.c
sqlx/sqlx_service.c
tests/functional/api/test_objectstorage.py
tools/oio-reset.sh

- Fix small memory leak in meta2.
- Rework the way we feed the load balancer with lists of services. Prevent nasty messages like `LB reload not followed by rehash`.
Jira: OS-294
- proxy
- meta2
- metautils
```
openio 4.2.7.dev18
```

Lock the load balancer while reloading a service slot

---

bin/oio-blob-auditor
bin/oio-blob-converter
oio/blob/auditor.py
oio/blob/client.py
oio/blob/converter.py
oio/blob/indexer.py
oio/blob/utils.py
oio/cli/reference/reference.py
oio/common/exceptions.py
oio/common/utils.py
oio/common/xattr.py
oio/container/client.py
oio/crawler/integrity.py
oio/directory/client.py
oio/rdir/client.py
rawx-apache2/src/rawx_repo_core.c
rawx-lib/src/attr_handler.c
tests/functional/blob/__init__.py
tests/functional/blob/test_converter.py
tests/functional/rdir/test_indexer.py

A flaw in the `xfs_repair` tool can remove some chunk extended attributes. This PR aims at updating our various tools to tolerate missing attributes, and regenerate them, especially the famous "fullpath".
- Python API
- `oio-crawler-integrity`
- `oio-blob-auditor`
```
openio 4.2.7.dev24
```

Regenerate missing chunk attributes

---

core/oiourl.h
core/proxy.c
core/tool_roundtrip.c
core/url.c
meta1v2/compound_types.c
meta1v2/compound_types.h
meta1v2/meta1_backend_references.c
meta1v2/meta1_backend_services.c
meta1v2/meta1_server.c
meta2v2/meta2_backend.c
meta2v2/meta2_server.c
meta2v2/meta2_utils.c
metautils/lib/comm_message.c
proxy/m2_actions.c
proxy/metacd_http.c
rawx-apache2/src/rawx_event.c
sqliterepo/sqlite_utils.c
sqliterepo/sqlx_remote.c
sqliterepo/sqlx_remote.h
sqlx/sqlx_client_direct.c
sqlx/sqlx_service.c
tests/functional/event/test_events_emission.py
tests/unit/test_url.c
tools/event-benchmark/event_benchmark.c

The current PR removes that service subtype from objects URL.
The oio_url_s represents the official composite path to a logical entity (either an account, a container or an object). Prior to this PR, is contained a token called "type" that acted as a subtype of the actual service type.
The use case was to allow an end user to have a single `reference` (meta1) but several `containers` (meta2). The problem is that a container (a.k.a. a base on a meta2 service) is identified with the ID ... of the reference (plus a service type and a sequence number). With a subtype we could multiply the number of containers with an action of one element of the identifier tuple.
All the containers of a given reference could be listed easily. But now the notion of account exist and is listable, playing the …

core: Forget the service subtype

---

core/url.c
metautils/lib/metatypes.h
rawx-apache2/src/rawx_repo_core.c
rawx-apache2/src/rawx_repo_core.h
rawx-apache2/src/rawx_repository.c
rawx-lib/src/attr_handler.c
rawx-lib/src/rawx.h

Perform half less syscall when deleting a chunk.
Prior to this PR, all the XATTR were read from the chunk, and the chunk was opened twice. Now the reawx just read the xattr holding the full (logical) path of the object the chunk belongs to, and do everything with the same file descriptor.
`enhancement`
`core`, `rawx`
`openio 4.2.7.dev26`
Let's see if a bot on Twitter will relay this post from OpenIO @open-io, because we talk about #OpenSource #ObjectStorage, and sometimes used bad words like "fuck".

rawx: Upon a DELETE, just read the necessary xattr

---

meta2v2/meta2_backend.c
meta2v2/meta2_backend.h
meta2v2/meta2_filters_action_container.c
meta2v2/meta2_filters_action_content.c
meta2v2/meta2_macros.h
meta2v2/meta2_utils.c
meta2v2/meta2_utils.h
metautils/lib/metautils_macros.h
oio/account/backend.py
oio/account/client.py
oio/account/server.py
oio/api/object_storage.py
oio/cli/container/container.py
oio/cli/events/events.py
oio/container/client.py
oio/event/filters/account_update.py
proxy/m2_actions.c
proxy/meta2v2_remote.c
proxy/meta2v2_remote.h
tests/functional/account/test_backend.py
tests/functional/account/test_server.py
tests/functional/api/test_objectstorage.py
tests/functional/cli/account/test_account.py
tests/functional/cli/object/test_object.py
tests/functional/container/test_container.py
tests/unit/test_meta2_backend.c
tools/event-benchmark/fake_service.c

- Save the number of missing chunks in the meta2 database
- Use the event (`container.state`) to update the account
- Increase the counter to each chunk not uploaded
- Decrease the counter to each deleted object with missing chunks
- Decrease the counter to each rebuilt chunk (chunk not uploaded)
- Recompute the counter of missing chunks
- Python API
- `account`
- `proxy`
- `meta2`
```
openio 4.3.1.dev32
```

Save the number of missing chunks

---

tools/oio-check-copyright.sh

False negatives happened on empty and removed files. The current PR fixes that. Also produces a lighter debug output.
Between `enhancement` and `fix`
`ci`
`openio 4.3.2.dev20`

tools: Improve the check of copyright mentions

---

core/lb.c
core/oiolb.h
tests/functional/directory/test_refmapping.py
tests/unit/api/test_replication.py
tests/unit/test_lb.c

Tolerate weird service pool configurations, with empty targets or trailing separators.
Jira: OS-314
- LB
```
openio 4.2.8.dev18
```

Tolerate weird LB pool configurations

---

core/lb.c
core/oiostr.h
core/str.c
oio/api/io.py
oio/common/configuration.py
oio/container/client.py
oio/directory/admin.py
proxy/common.c
proxy/cs_actions.c
proxy/m2_actions.c
proxy/sqlx_actions.c
sqliterepo/cache.c
sqliterepo/cache.h
sqliterepo/replication_dispatcher.c
sqliterepo/sqlite_utils.h
tests/functional/api/test_objectstorage.py
tests/functional/blob/test_auditor.py
tests/functional/blob/test_converter.py
tests/functional/blob/test_mover.py
tests/functional/blob/test_rebuilder.py
tests/functional/container/test_replication.py
tests/functional/content/test_content.py
tests/functional/content/test_content_perfectible.py
tests/functional/content/test_content_versioning.py
tests/functional/directory/test_admin.py
tests/functional/directory/test_refmapping.py
tests/unit/api/test_objectstorage.py
tests/unit/api/test_replication.py
tests/utils.py
tools/oio-bootstrap.py

- Test the two mechanisms of database restoration: the synchronous one (`DB_RESTORE`) and the asynchronous one (`DB_DUMP`/`DB_PIPEFROM`).
- Include `soft_max` configuration value in the cache statistics (the `hard_max` was displayed as `max`).
- Support 'client specified' peers in some more proxy routes. This allows tests to target a request to a specified peer, and compare the results from different peers.
- Slightly modify `oio-reset.sh` deployment to use comprehensible service IDs.
- sqliterepo
- proxy
```
openio 4.2.7.dev27
```

Test sqliterepo replication

---

oio/cli/directory/directory.py

The `--no-rdir` option still existed in the 4.3.x but triggered a warning.
Now it is not recognized anymore, it is an error to use it, and it should happen in the future 4.4.x
`cleanup`
`cli`
`openio 4.3.2.dev32`

cli: Remove the `--no-rdir` from `directory bootstrap`

---

sqliterepo/election.c
sqliterepo/election.h
sqlx/sqlx_service.c

We do not exit elections but we hard-reset them instead. No need to wait for them.
`Enhancement`
`sqliterepo`
`openio 4.3.2.dev22`

sqliterepo: Faster exit of services

---

sqliterepo/election.c
tests/unit/test_sqliterepo_election.c

Ensure we do not go into the FAILED state of the FSM when the MASTER left the election between the moment we got the list of members and the moment where we asked for the URL of the MASTER.
Instead of going to the LEAVING_FAILING state, and because we are still running the election with a valid node, we list again the group members to check for the new MASTER.
`enhancement`
`sqliterepo`
`openio 4.3.3.dev1`

sqliterepo: React quickly to a MASTER disappearing while ASKING

---

oio/rebuilder/blob_improver.py

Do not spit an ugly traceback when trying to pretty print an item that fails to be handled.
- oio-blob-improver
```
openio 4.3.2.dev44
```

blob-improver: do not crash when fullpath is not encodable

---

etc/blob-indexer.conf-sample
oio/blob/indexer.py

Desable the backup when converting chunks for the `oio-blob-indexer`
- `oio-blob-indexer`
```
openio 4.2.8.dev26
```

oio-blob-indexer: Disable the backup when converting chunks

---

oio/cli/directory/directory.py
oio/directory/meta0.py
tests/functional/container/test_container.py
tests/unit/test_prefixmapping.py

* Brings a fair distribution of the meta1 prefixes over the multiple sites
* At most one replica of any prefix is on a single site
* Requirement that locations have max 4 tokens, with the site coming first.
`enhancement`
`cli`
`openio 4.3.2.dev3`

Improve the `directory bootstrap` fairness on multi-DC

---

proxy/common.c
proxy/common.h
proxy/m2_actions.c

Also decache invalid location entries if clues are present in "group" requests, such the election debug / ping / leave. The PR also fixes a minor memory leak (GError upon a decache) in the proxy.
`bugfix`
`proxy`
`openio 4.2.8.dev33`

proxy: Decache stale service locations more often

---

.travis.yml
CMakeLists.txt
tests/unit/CMakeLists.txt
tools/oio-travis-tests.sh

There are reports of users expecting the SDK_ONLY option of cmake to be functional.
This is now fixed.
`enhancement`
`cmake`, `ci`
`openio 4.3.3.dev11`

cmake,ci: Restore the SDK_ONLY option

---

CMakeLists.txt
cache/CMakeLists.txt
cluster/lib/CMakeLists.txt
core/CMakeLists.txt
events/CMakeLists.txt
meta0v2/CMakeLists.txt
meta1v2/CMakeLists.txt
meta2v2/CMakeLists.txt
metautils/lib/CMakeLists.txt
rawx-lib/src/CMakeLists.txt
rdir/CMakeLists.txt
resolver/CMakeLists.txt
server/CMakeLists.txt
sqliterepo/CMakeLists.txt
sqlx/CMakeLists.txt
tests/func/CMakeLists.txt
tools/event-benchmark/CMakeLists.txt

Prior to this PR, the `0.0.0` ABI version is appended by default to the shared object (.so) files we generate, and the main ABI_VERSION variable was useless.
Now each library might evolve independently, and the starting point is the same `0.0.0` for the sake of backward compliance.
`enhancement`
`*`
`openio 4.4.0.0b1.dev26`

cmake: Explicit the ABI version of each shared library

---

oio/cli/rdir/rdir.py
oio/common/exceptions.py
oio/conscience/client.py
oio/rdir/client.py
proxy/lb_actions.c
tests/functional/api/test_directory.py
tests/unit/common/test_exceptions.py

Implement `--min-dist` option for `openio rdir bootstrap`.
Jira: OS-281
- CLI
- Python API
```
openio 4.4.0.0b1.dev26
```

CLI: add '--min-dist' option to 'rdir bootstrap'

---

core/internals.h
core/oio_sds.h
core/oiolog.h
core/oiourl.h
core/oiovar.h

Ensure each publicly exported `enum` field has an explicit value. It helps avoiding ABI breaks.
`enhancement`
`core`
`4.2.8.dev35`
TODO(jfsmig): We should add a test that forbid the usage of enums without a value.

core: Explicit the value of public enums

---

oio/account/client.py
oio/api/object_storage.py
oio/common/utils.py
oio/conscience/client.py
tests/unit/api/test_objectstorage.py

The `patch_kwargs` functionality was used only on a few `ObjectStorageApi` methods, resulting in the `read_timeout` not being applied on all requeststo oio-proxy. This is now fixed.
Also, if a timeout is provided, a deadline is now computed for internal usage, and a timeout is computed accordingly for each subrequest.
- Python API
```
openio 4.2.8.dev34
```
This PR should fix an issue with oioswift, where `sds_read_timeout` was not applied on all requests.

Python API: forward timeouts, compute a deadline

---

oio/blob/converter.py
tests/functional/blob/__init__.py
tests/functional/blob/test_converter.py

Recreate fullpath  when xattrs 'grid.contant.path' and 'oio:$HASH' are also missing
oio-blob-converter
```
openio 4.2.8.dev36
```

oio-blob-converter: restore fullpath if grid.content.path or  oio:HASH are missing

---

meta2v2/meta2_filters_action_container.c
proxy/m2_actions.c

Object listings using a delimiter are renowned to be slow. This change will help a little.
- oio-proxy
- meta2
```
openio 4.2.8.dev39
```

Optimize object listings using a delimiter

---

meta2v2/meta2_backend.c
meta2v2/meta2_backend.h
meta2v2/meta2_filters_action_container.c
meta2v2/meta2_macros.h
meta2v2/meta2_utils.c
meta2v2/meta2_utils.h
metautils/lib/metautils_macros.h
oio/account/backend.py
oio/account/server.py
oio/api/object_storage.py
oio/cli/container/container.py
oio/container/client.py
oio/event/filters/account_update.py
proxy/m2_actions.c
proxy/meta2v2_remote.c
proxy/meta2v2_remote.h
tests/functional/account/test_backend.py
tests/functional/api/test_objectstorage.py
tests/functional/cli/account/test_account.py
tests/functional/cli/object/test_object.py
tests/functional/container/test_container.py
tools/oio-bootstrap.py
tools/oio-test-rebuilder.sh

* Save the number of damaged objects in the meta2 database
* Use the event (`container.state`) to update the account
* Increase the counter for each chunk not uploaded
* Decrease the counter for each deleted object with missing chunks
* Decrease the counter for each rebuilt chunk (chunk not uploaded)
* Recompute the counter of damaged objects
* Python API
* `account`
* `proxy`
* `meta2`
```
openio 4.4.0.0b1.dev36
```

Save the number of damaged objects

---

oio/blob/indexer.py
oio/common/constants.py
tests/functional/blob/test_indexer.py

* Do not pollute `oio-blob-indexer` logs with dirty messages like:
```
ERROR while updating /mnt/sdi/OPENIO/rawx-7/3A1/3A1810D5BA7EBB77D146E6258923694AEE060DCD0E6CAD9517744139D37D1E15#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/oio/blob/indexer.py", line 73, in safe_update_index#012    self.update_index(path, chunk_id)#012  File "/usr/lib/python2.7/site-packages/oio/blob/indexer.py", line 137, in update_index#012    with open(path) as f:#012IOError: [Errno 2] No such file or directory: '/mnt/sdi/OPENIO/rawx-7/3A1/3A1810D5BA7EBB77D146E6258923694AEE060DCD0E6CAD9517744139D37D1E15'
```
They were due to files seen by the crawler but deleted just before the worker could handle them.
* Do not pollute logs with messages like:
```
WARN Not a chunk …
```

blob-indexer: do not warn on pending or just deleted chunks

---

sqliterepo/election.c

`completion_LISTING` did not check validity of argument before using it.
Also fix a codepath with strrchr could be called on NULL
sqliterepo
```
4.4.0.0b1.dev35
```

sqliterepo: minor fixes

---

sqliterepo/election.c

The size of the buffer was wrong but hopefully, we did not write out of the `id` integer variable because the source hexadecimal string ends early enough.
`bugfix`
`sqliterepo`
`openio 4.4.0.0b1.dev75`

sqliterepo/election: Fix an ugly but harmless memory management

---

tools/oio-reset.sh

Resetting ZK takes a while and is useless.
`enhancement`
`sandbox`
`openio 4.4.0.0b1.dev75`

oio-reset: Stop calling zk-reset.py

---

etc/bootstrap-option-zkmux.yml
sqliterepo/election.c

Allow to change the value of the value of the managed variable `sqliterepo.zk.mux_factor` on a running platform. Only works for platforms that never used a positive value prior to this PR, because it was not possible to modify that value without breaking the election FSM.
`enhancement`
`sqliterepo`
`openio 4.4.0.0b1.dev80`

sqliterepo/election: Be more consistent with sharded/multiplied ZK

---

proxy/dir_actions.c
server/network_server.c

- Fix oio-proxy API documentation.
- Fix the variable used in a warning message from TCP server base.
- oio-proxy
- TCP server base
```
openio 4.4.0.0b2.dev15
```

Fix error messages, document proxy API

---

oio/conscience/checker/beanstalk.py
oio/event/beanstalk.py
setup.cfg
tools/oio-bootstrap.py

Register `proxy` and `beanstalkd` into `conscience`, it will allow us to launch commands on all cluster.
conscience-agent
```
master
```

Register proxy and beanstalkd into conscience

---

CONTRIBUTING.md
oio/api/base.py
oio/common/decorators.py
oio/rdir/client.py
oio/rebuilder/blob_improver.py
tests/functional/content/test_content_perfectible.py

Try to be consistent when using abbreviations. We choose reqid over req_id since it was more common in the existing code base, especially in log messages.
- Python API
```
openio 4.4.0.0b2.dev18
```

Python API: use reqid instead of req_id

---

oio/cli/rdir/rdir.py

Rdir bootstrap returned 0 when there was a partial success.
Deployment needs to be able to check if everything was ok.
So now even on partial success we return 1 but still printing the partial success.
CLI
```
openio 4.4.0.0b2.dev13
```

CLI: return 1 when rdir bootstrap fails

---

oio/account/backend.py
oio/account/client.py
oio/api/object_storage.py

Refactor the container filtering method so it is more readable
and less error-prone.
- account
```
openio 4.4.0
```
Bug has been discovered when trying to integrate https://github.com/open-io/oio-swift/pull/162

account: fix filtering when more than 1000 containers

---

tools/oio-reset.sh

Make sure that meta1 are started before assigning rdir services
- `oio-reset.sh`
```
openio 4.2.9.dev6
```

Make sure that meta1 are started before assigning rdir services

---

oio/cli/admin/service_decache.py
oio/conscience/client.py
oio/directory/admin.py
proxy/metacd_http.c
setup.cfg
tests/functional/cli/__init__.py
tests/functional/cli/admin/test_service_decache.py
tests/functional/cli/object/test_object.py
tests/utils.py

Implement the following commands:
- `openio-admin proxy decache`
- `openio-admin meta1 decache`
- `openio-admin meta2 decache`
- CLI
- Python API
- proxy
```
openio 4.4.2.dev14
```
Some utility code was taken from #1712, and will probably conflict when merging.

CLI: implement 'openio-admin <service_type> decache' commands

---

oio/cli/admin/item_touch.py
setup.cfg

Implement `container touch` in admin CLI
Admin CLI
```
openio 4.4.2.dev12
```
Output has been added and will consume all containers instead of stopping at first error
```
$ openio container touch d1 d2
Directory error: no such user (HTTP 403) (STATUS 406)
$ openio-admin container touch d1 d2
+-----------+-------------------------------------------------------+
| Container | Status                                                |
+-----------+-------------------------------------------------------+
| d1        | ok                                                    |
| d2        | Directory error: no such user (HTTP 403) (STATUS 406) |
+-----------+-------------------------------------------------------+
```

CLI: implement 'openio-admin container touch' command

---

meta2v2/generic.c
meta2v2/meta2_backend.c
meta2v2/meta2_backend.h
meta2v2/meta2_filters_action_content.c
meta2v2/meta2_utils.c
meta2v2/meta2_utils.h
meta2v2/meta2_utils_json_out.c
oio/cli/cluster/cluster.py
proxy/cs_actions.c
proxy/m2_actions.c
tests/functional/cli/__init__.py
tests/functional/cli/object/test_object.py
tests/unit/test_meta2_backend.c
tests/utils.py

Improve `storage.content.update` events, in regards to object properties.
- Send keys and values of properties that have just been set.
- Send keys of properties that have been deleted (with a null value).
- meta2
```
openio 4.4.2.dev1
```

Improve storage.content.update events

---

meta1v2/meta1_backend_services.c
oio/api/object_storage.py
oio/event/filters/dump.py
proxy/m2_actions.c
setup.cfg
tests/functional/api/test_objectstorage.py
tools/oio-bootstrap.py

The snapshot operation did not show the created container in account service:
- the `sys.user.name` and `sys.account` was not updated
- a manual `openio container touch` was not possible due to these erroneous values
Fixes OS-350
CLI
```
openio 4.2.9.dev10
```

Fix container snapshot feature

---

cluster/module/server.c
metautils/lib/metatype_srvinfo.h
metautils/lib/metautils_macros.h
metautils/lib/utils_service_info.c
oio/cli/cluster/cluster.py
tests/functional/conscience/test_conscience.py
tools/oio-bootstrap.py

Create a new `tag.lock` tag telling is the service has been locked by an administrator. This tag is saved (with all other tags) in the conscience persistence file. After a restart, this file is loaded, and the services are locked (or unlocked) again.
- conscience
- CLI
```
openio 4.4.2.dev19
```

Persist service locks after conscience restart

---

oio/rebuilder/meta1_rebuilder.py

The variable meta1_digits was renamed ns.meta1_digits in 4.1.22.
If new variable is missing, we try to load old value
oio-meta1-rebuilder
```
openio 4.4.2.dev27
```
```
```

Python API: do not use the legacy 'meta1_digits' parameter

---

rawx/rawx.go

The header `X-oio-req-id` was mispelled `X-oio-reqid` and it was not possible to trace a full request on rawx level.
go-rawx
```
openio 5.0.0.0a1.dev11
```

rawx: fix mispelled req-id header

---

etc/event-handlers.conf-sample
oio/event/filters/account_update.py

Allow to configure timeouts from the event-agent to the account service.
Also review how we handle errors occurring while removing a container from the account service: the event was dropped, it is now replayed later.
Jira: OS-355
- event-agent
```
openio 4.4.2.dev19
```

event-agent: configure timeouts to the account service

---

rawx/handler_chunk.go
rawx/logger.go

The log emitted by the rawx was not compliant with our documentation:
The ContainerID was missing in emitted log.
The LogOIncoming was not correct, it is now used by PUT operation.
Fixes OS-356
rawx
```
openio 4.4.2.dev27
```
Please note that an update is still required on monitoring stack.

rawx: fix log format

---

oio/api/ec.py
oio/api/io.py
oio/api/replication.py
oio/common/decorators.py
oio/common/http_eventlet.py
tests/functional/conscience/test_conscience.py
tests/functional/container/test_replication.py
tests/unit/api/test_objectstorage.py
tests/utils.py

Track read-after-close operations seen in production, but still not reproduced. Also display request ID in more warning messages to help debugging such operations.
- Python API
```
openio 4.4.2.dev47
```

Track read-after-close operations, improve request ID usage

---

oio/api/object_storage.py
oio/cli/container/container.py
proxy/m2_actions.c
sqliterepo/replication_dispatcher.c
sqliterepo/repository.c
sqliterepo/sqlite_utils.c
sqliterepo/sqlite_utils.h

Container snapshots are now real containers, frozen by default. They can be unfrozen with `openio container set --status enabled`.
- Python API
- oio-proxy
- sqliterepo
```
openio 5.0.0.0a1.dev8
```

Replicate container snapshots

---

oio/cli/cluster/cluster.py
oio/cli/common/clientmanager.py
oio/cli/directory/directory.py
oio/cli/zk/set.py
oio/common/configuration.py

When some parameters are missing from configuration files, and are requested by the CLI, a nice message will be displayed, telling in which file the parameter is supposed to be.
```
> openio zk stat meta2
'zookeeper' not found in configuration files:
/etc/oio/sds.conf.d/NS
/home/fvennetier/.oio/sds.conf
```
- CLI
```
openio 5.0.0.0a1.dev8
```

CLI: display nicer KeyError messages

---

oio/cli/admin/service_list.py
setup.cfg

Build a list of containers:
- hosted by a meta2 service,
- which have chunks stored on a specific rawx service.
Jira: R1904-21
- CLI
```
openio 5.0.0.0a1.dev52
```

CLI: list containers from rawx and meta2

---

etc/bootstrap-option-preserve-events.yml
tests/functional/api/test_objectstorage.py
tests/functional/blob/test_blob.py
tests/functional/content/test_content_perfectible.py
tests/utils.py
tools/oio-bootstrap.py
tools/oio-travis-tests.sh

Implement a facility to wait for a specific event. The event can be specified by type and/or request ID. The purpose of this feature is to speedup tests which previously used `time.sleep()` to ensure an event had been handled.
- tests
```
openio 4.4.3.dev1
```

tests: implement a facility to wait for a specific event

---

bin/oio-meta2-mover
oio/cli/admin/item_move.py
oio/cli/admin/item_repair.py
oio/container/repairer.py
oio/directory/meta2.py
setup.cfg

- Allow to rebuild meta2 databases when the quorum isn't reached
- Implement 'openio-admin container repair' command 
- Admin CLI
- Python API
```
openio 5.0.0.0a1.dev51
```
```
$ openio-admin container repair toto titi
START last_report=2019-04-18T17:49:44 0.00s containers=0 0.00/s errors=0 0.00% start_time=2019-04-18T17:49:44 0.00s total_containers=0 0.00/s total_errors=0 0.00% progress=0/2 0.00%
DONE last_report=2019-04-18T17:49:44 0.19s containers=2 10.28/s errors=0 0.00% start_time=2019-04-18T17:49:44 0.19s total_containers=2 10.28/s total_errors=0 0.00% progress=2/2 100.00%
+-----------------------+--------+
| Object                | Status |
+-----------------------+--------+
| OPENIO|myaccount|toto | OK     |
| OPENIO|myaccount|titi | …
```

Implement 'openio-admin container repair' command 

---

tests/func/test_weird_chars.c
tools/oio-test-mover.sh
tools/oio-test-rebuilder.sh
tools/oio-travis-tests.sh

We often reach the limit of 10000 log lines in our CI tool, and a lot of them are curl progress bars. We don't need them.
- CI
```
openio 5.0.0.0a2.dev1
```
None.

CI: make curl silent when there is no error

---

oio/api/backblaze_http.py
oio/api/object_storage.py
oio/ecd/app.py
oio/event/filters/content_cleaner.py
tools/oio-test-mover.sh
tools/oio-test-rebuilder.sh
tools/oio-test-suites.sh

Try to find why the rebuilder tests are so slow, and fix what is fixable.
- Use a bash associative array to cache results of `openio cluster resolve` (which is rather slow).
- Use variables for commands we use often.
- Call `command -v` instead of `which`.
- tests
```
openio 5.0.0.0a1
```

tests: accelerate some shell scripts

---

.travis.yml
tests/functional/api/test_objectstorage.py
tests/utils.py
tools/oio-test-suites.sh

During test on Travis, some tests were waiting specific events but previous events were used.
We can now add more filter to wait the wanted event.
The single and webhook testsuite was merged
tests
```
5.0.0.0a2.dev17
```

CI: enhance wait_for_event

---

meta2v2/meta2_backend.c

Set `container_new` to `oio_meta2_tube_container_new`
```
openio 5.0.0.0a2.dev18
```

Meta2: Set `container_new` to the right tube

---

.travis.yml
oio/cli/admin/item_check.py
oio/common/tool.py
oio/conscience/client.py
oio/crawler/integrity.py
tools/oio-test-rebuilder.sh

Bring various improvements to `oio-crawler-integrity`, required to make it a daemon later.
- Allow it to check all accounts.
- Fix concurrency issues.
- Load `LbClient` from `ConscienceClient` only when necessary.
- Refactor `Tool` class a little.
- Python API
- CLI
- oio-crawler-integrity
```
openio 5.0.0.0a2.dev24
```

Integrity crawler improvements

---

oio/common/green.py
tests/unit/common/test_ratelimiter.py

Functions to parse hour-based policies for rate limiting, and wrapper around the existing rate limiting method to apply these policies.
`Python API`
```
openio 4.2.6.dev59
```
```
Nil.
```

Python API: Add hour-based rate limiting policies utilities

---

all-requirements.txt

Prevent urllib3 1.25 because some test environments are slower with this version.
- Python API
```
openio 4.2.9.dev14
```

Prevent installation of urllib3 1.25

---

oio/account/rebuilder.py
oio/cli/admin/__init__.py
oio/cli/admin/common.py
oio/cli/admin/item_check.py
oio/cli/admin/item_locate.py
oio/cli/admin/item_move.py
oio/cli/admin/item_repair.py
oio/cli/admin/service_check.py
oio/cli/admin/service_config.py
oio/cli/admin/service_decache.py
oio/cli/admin/service_info.py
oio/cli/admin/service_list.py
oio/cli/admin/service_rebuild.py
oio/cli/common/shell.py
oio/common/tool.py
oio/crawler/integrity.py
tests/functional/cli/admin/test_item_move.py
tests/functional/cli/admin/test_service_decache.py

- Limit speed of distributed dispatcher
- Use the same column `Errors` to display the errors
- Fail the command if there is at least one error
- Set the default verbose level to INFO
- Use common mixin
- Python API
- Admin CLI
```
openio 5.0.0.0a2.dev20
```

Improve Admin CLI

---

rdir/rdir.c

Since they are not mandatory we should just free the error.
- rdir
```
openio 5.0.0.0a2.dev18
```

Rdir: Free error on missing options

---

oio/api/base.py
rawx/rawx.go

Our Python API was duplicating `x-oio-req-id` header when sending a request
The GO Rawx was not limited length of `req-id` to 63 chars and response was replying with deprecated `x-trans-id`
oio
rawx
```
5.0.0.0a2.dev36
```

Few fixes around x-oio-req-id

---

oio/cli/admin/service_check.py
oio/crawler/integrity.py

When `openio-admin rawx check` finds a chunk indexed in rdir but missing from the rawx service, the process stops.
This commit enriches the output with information retrieved from rdir.
OIO
```
openio 5.0.0.0b0
```

crawler: provide informations from rdir to integrity crawler

---

tools/oio-reset.sh

Do not lock/unlock meta1 scores before bootstrap
- `oio-reset.sh`
```
openio 4.2.9.dev15
```

Do not lock/unlock meta1 scores before bootstrap

---

oio/api/io.py
oio/api/object_storage.py
oio/cli/cluster/cluster.py
oio/common/utils.py
tests/unit/api/test_utils.py

At some point in the upload process, we know that the metadata server is fine (it provided us with chunk addresses) and the client is still listening (he just uploaded all data). It seems a good idea to postpone the deadline (because it is computed from the client-provided timeout).
- Python API
```
openio 5.0.0.0b1.dev7
```
This modification will allow slow uploads to take longer than `read_timeout`, provided the client is still sending data from time to time.

Python API: recompute deadline after data upload success

---

core/ext.c
core/oioext.h
sqliterepo/election.c
sqliterepo/synchro.c
sqliterepo/synchro.h
tools/oio-travis-tests.sh

A long time ago, we used to reset all elections on such Zookeeper event. We stopped doing this when we started to use several connections to Zookeeper, because it seemed a bad idea to reset everything on a single connection failure. Unfortunately, this leads to elections staying forever in the same state
while their Zookeeper node has vanished.
Now, after getting an unbound (no path is provided) ZOO_SESSION_EVENT, we will reset all elections in the master state, to avoid any infamous "double master" situations.
- sqliterepo
- core
```
openio 4.4.4.dev5
```

sqliterepo: reset MASTER elections on ZOO_SESSION_EVENT

---

oio/api/ec.py
oio/api/replication.py
oio/cli/common/shell.py
oio/common/http_eventlet.py
tests/unit/__init__.py

- Enable TCP_CORK on sockets towards rawx services.
- Avoid CPU-consuming buffer copies during chunk upload.
- Implement profiling facilities in `openio` CLI.
- Python API
```
openio 4.4.4.dev10
```

Python API: enable TCP_CORK, avoid buffer copies

---

oio/api/ec.py
oio/api/replication.py

Tell eventlet/greenlet to yield at specific moments to ease the computation interleaving.
It helps preventing accumulating huge amount of data in input greenlets, with a better chance of the output greenlets to become active meanwhile.
`enhancement`
`oio`
`openio 4.4.4.dev11`

Python API: better eventlet coordination

---

oio/api/ec.py
oio/api/io.py
oio/api/object_storage.py
oio/api/replication.py

Start small to minimize initial dead time and parallelize early,
then grow to avoid too much context switches.
- Python API
```
openio 4.4.4.dev16
```
Minimum and maximum of the ramp are configurable with `chunk_buffer_min` and `chunk_buffer_max`.

Python API: ramp up upload buffer size

---

oio/common/http_urllib3.py
tests/unit/api/test_utils.py

When using oioswift, some configuration parameters come as strings instead of integers. Unfortunately, the magic cast has disappeared during a refactoring. This PR restores it.
- Python API
```
openio 4.5.0.0b1.dev7
```

Fix get_poolmanager parameters

---

oio/api/ec.py
oio/api/replication.py
oio/common/green.py

Replace `eventlet.Queue` with `eventlet.queue.LightQueue` when sending data
- Python API
```
openio 4.4.4.dev17
```

Python API: Replace Queue with LightQueue when sending data

---

oio/account/client.py
oio/api/base.py
oio/api/ec.py
oio/api/io.py
oio/api/object_storage.py
oio/api/replication.py
oio/blob/client.py
oio/check_service/common.py
oio/cli/common/shell.py
oio/common/client.py
oio/rdir/client.py
tests/functional/api/test_perfdata.py

Enrich perfdata when:
- requesting a service
- reading and writing an object
- Python API
- CLI
```
openio 4.4.4.dev19
```
```
$ openio object create toto /etc/magic --dump-perfdata
+-------+------+----------------------------------+--------+
| Name  | Size | Hash                             | Status |
+-------+------+----------------------------------+--------+
| magic |  111 | 272913026300E7AE9B5E2D51F138E674 | Ok     |
+-------+------+----------------------------------+--------+
Performance data: {
"proxy": {
"meta2": 0.007457,
"resolve": 0.007463,
"total": 0.049264
},
"rawx": {
"ec": 0.000075,
"http://127.0.0.1:6010/DE0E43B2C423D9FF1335B155A818F5E8A18FDAAEDAEBD71366906C148866526B": 0.008854,
"http://127.0.0.1:6011/FE4C3DEBE825832BE78F3B8700DE5511A4BE4610FC88D9FC5 …
```

Enrich performance data display

---

oio/cli/admin/__init__.py

Revert commit a896febd0e49ea78c2fdcbf8a2dc09dbeda4847a because the `openio-admin` commands are too verbose.
- Admin CLI
```
openio 5.0.0.0b2.dev1
```

Revert "Admin CLI: Set the default verbose level to INFO"

---

oio/event/agent.py

Spawn `CPU_COUNT` worker when the number of worker is negative (or equals to 0).
```
openio 4.2.9.dev16
```

event-agent: Always spawn workers

---

oio/common/green.py
oio/crawler/integrity.py

eventlet.Semaphore exists since version 0.20.1: https://github.com/eventlet/eventlet/commit/79292bd16a6a1384d8c3d11bcefa40eb53bbeae4#diff-e8a149cf9a6b76be0526ba05331438c5R42.
But Centos 7 uses version 0.18.4.
- Python API
- CLI
```
openio 5.0.0.0b2.dev1
```

Python API: fix import of eventlet.Semaphore

---

proxy/m2_actions.c

Only perform the location comparison when both the proxy and the service have a location.
`bugfix`
`oio-proxy`
`openio 4.5.1.dev1`

proxy: Fix the location comparison

---

oio/api/ec.py
oio/common/green.py

EC writers used to leak open connections after `SourceReadError` or `SourceReadTimeout` exceptions (when the client unexpectedly closes the connection).
- Python API
```
openio 4.5.1.dev1
```

Python API: close all EC writers, whatever happens

---

oio/api/ec.py

The previous code may have considered as successes some uploads that had failed (removing elements from the list we are iterating on is a bad thing). Now we build a list with only the chunks which do not see any error yet.
Also, parallelize the upload of the trailers, so a slow chunk upload does not block the termination of the other chunk uploads.
- Python API
```
openio 4.5.2.dev4
```

Python API: rework EC upload code

---

meta2v2/meta2_backend.c
meta2v2/meta2_gridd_dispatcher.c
proxy/m2_actions.c
proxy/meta2v2_remote.c
proxy/meta2v2_remote.h
tests/functional/container/test_container.py

This commit bring same mecanism to update sys.m2.policy.versions
from header to content/delete operation: we want to control
if current version of object must be deleted or add a delete marker.
Fixes #OS-373
proxy and meta2
```
openio 4.5.2dev4
`

Update max_versions of container from header (part 2)

---

etc/event-handlers.conf-sample
oio/blob/client.py
oio/common/http_urllib3.py
oio/event/filters/content_cleaner.py
tools/oio-bootstrap.py

Allow to configure the connection pool of the `content_cleaner` filter. This will help reducing the number of persistent connections to one service, while keeping at least one persistent connection to each service. If you see too many persistent connections, set:
- `pool_connections`: high value (ideally one per rawx service);
- `pool_maxsize`: low value (one per coroutine, `concurrency` in the main configuration file).
- event-agent
```
openio 4.5.2.dev6
```

Configure event-agent connection pool

---

confgen.py
core/oiovar.h
core/var.c

Manage well values in /etc/oio/sds.conf files for variables declared as time since EPOCH, in seconds.
Prior to the fix, they were erroneously considered as millisecond values and they received the same modifier as the "monotonic" variables.
`bugfix`
`core`, `conf`
`openio 4.5.4.dev4`

conf: Manage well the modifiers on second-wide (epoch) time variables

---

oio/common/fullpath.py
tests/unit/common/test_fullpath.py

Allow to encode fullpath with UTF-8 args
- Python API
```
openio 4.2.10.dev2
```

Allow to encode fullpath with UTF-8 args

---

sqliterepo/election.c
sqliterepo/replication_dispatcher.c
sqliterepo/repository.c
sqliterepo/synchro.c
sqliterepo/synchro.h
sqliterepo/version.h
tools/benchmark/oio-bench-container-create.py
tools/oio-test-rebuilder.sh
tools/oio-travis-tests.sh

External DB_VERS requests used to create the database, but internal ones did not. This resulted in a meta2 service never being elected master during M2_CREATE requests. Now that the internal requests also create the database, a simple benchmark shows a 3x performance increase (3x more meta2 databases created per second).
Jira: OS-411
- sqliterepo
```
openio 4.2.10.dev2
```

sqliterepo: prevent unneeded loop at election start

---

bin/oio-blob-mover
etc/blob-mover.conf-sample
oio/blob/mover.py

The chunk mover will now use 10 coroutines to move chunks in parallel. This can be changed with the `concurrency` parameter in the configuration file. The rate limiting is global (not per each coroutine).
- oio-blob-mover
```
openio 4.5.4.dev5
```

oio-blob-mover: implement concurrency

---

oio/cli/container/container.py
sqliterepo/replication_dispatcher.c
tests/functional/api/test_objectstorage.py

Allow to delete all container properties.
- `sqliterepo`
- CLI
```
openio 4.6.1.dev2
```

Allow to delete all container properties

---

bin/oio-meta2-mover
core/ext.c
core/oioext.h
oio/cli/election/election.py
oio/directory/admin.py
sqliterepo/election.c
sqliterepo/synchro.c
sqliterepo/synchro.h
tests/functional/api/test_objectstorage.py
tests/unit/test_sqliterepo_election.c
tests/utils.py
tools/oio-test-mover.sh

We recently allowed internal calls `get_version` to create dummy database files, in order to make meta2 database creation faster. But in the case of slow Zookeeper callbacks (few milliseconds vs. few microseconds), coming after actual database removal, this resulted in dummy database staying there forever. Now we check if an election leave order has not been received before calling `get_version`.
Also, a few tools have been developed to help debugging this issue.
- sqliterepo
```
openio 4.6.1.dev2
```

Prevent slow ZK callbacks from creating empty databases

---

bin/oio-blob-rebuilder
oio/cli/volume/client.py
oio/cli/volume/volume.py
oio/rebuilder/blob_rebuilder.py

This new parameter allows to set the timeout for rdir operations. The
default value is 60.0s (was 30s before this commit).
- oio-blob-rebuilder
```
openio 4.2.11.dev12
```

blob-rebuilder: implement --rdir-timeout parameter

---

bin/oio-blob-improver
bin/oio-blob-rebuilder
bin/oio-meta1-rebuilder
bin/oio-meta2-rebuilder
oio/cli/admin/common.py
oio/cli/directory/directory.py
oio/common/tool.py
oio/rebuilder/rebuilder.py
tools/oio-bootstrap.py
tools/oio-test-rebuilder.sh

Rename '--workers' to '--concurrency' to avoid confusion:
- `workers` -> processes
- `concurrency` -> coroutines
- Admin CLI
- `oio-blob-improver`
- `openio directory warmup`
```
openio 5.0.1.dev1
```

Rename '--workers' to '--concurrency'

---

oio/common/constants.py
oio/event/filters/account_update.py

_RDIR is a hidden account and should not be present in the account database.
events
```
openio 4.6.1.dev12
```
```
Jira: OS-246
```

Event: Do not create _RDIR account on reference operations

---

oio/cli/lifecycle/lifecycle.py
oio/common/constants.py
oio/container/lifecycle.py
tests/functional/container/test_lifecycle.py

This PR will allow LifeCycle to be applied on bucket with Container Hierarcht=y
This behavior is triggered by flag on command line.
If set, a container listing will be triggered with `container%2F` as prefix.
The object listing will enrich metadata of objects to contains
original name in current container, computed name (with path)
and current container.
All tests against filter are unchanged, but API calls will use
`org_name` and `container's object`
Python LifeCycle
```
4.6.1dev3
```

Allow lifecycle to work with sharded buckets

---

oio/crawler/integrity.py
tests/functional/crawler/test_integrity_crawler.py

Fix error when `--output-for-blob-rebuilder` is used with only object checking.
oio-crawler-integrity
```
openio 4.6.0
```
```
Jira: OS-423
```

Integrity crawler: fix rebuilder input

---

oio/cli/admin/item_check.py
oio/cli/admin/item_rebuild.py
oio/common/tool.py
oio/crawler/integrity.py
oio/event/beanstalk.py
tests/functional/cli/admin/test_item_check.py
tests/functional/cli/admin/test_item_rebuild.py

Actually report missing chunk positions. These were reported on the standard log, but not in output files. This is now fixed.
Also, check the number of chunks against the quorum before reporting errors, such that missing chunks are potentially reported as irreparable (and not uselessly sent to the blob-rebuilder).
- oio-crawler-integrity
```
openio 4.6.1.dev12
```

oio-crawler-integrity: report missing chunk positions

---

all-requirements.txt

The new `pyparsing` release is not compatible with `cmd2` package.
Python
```
4.6.0dev1
```

Avoid pyparsing 2.4.1

---

all-requirements.txt

The new `pyparsing` release is not compatible with `cmd2` package.
- Python API
```
4.6.0dev1
```

Avoid pyparsing 2.4.1.1

---

bin/oio-blob-mover
oio/blob/mover.py

Allow to move chunks  only if their size is within a configured range.
Also wait for pending movers to complete before exiting a moving round.
enhancement
oio-blob-mover
`openio 4.6.1.dev24`

mover: Allow to move only chunk whose size is in a range

---

Variables.md
conf.json

The default usage is now to focus the read() operations on SLAVE databases.
enhancement
oio-proxy
`openio 4.6.1.dev26`

Set to "on" the default of "proxy.prefer.slave_for_read"

---

oio/account/backend.py
tests/functional/account/test_backend.py

There was an error when damaged_objects or missing_chunks were missing.
This happened when a container is created before oio-sds 18.10 and no object
is created after an update > 18.10.
The fix set the value to 0 but if some object had missing chunks before it will not
be printed and therefore the value would be erroneous.
account
```
openio 4.4.4.dev17
```

Account: Fix account refresh on missing values

---

oio/common/logger.py

Add support for logging to udp with syslog.
All python based daemons.
```
openio 4.6.1.dev57
```
For example, in config file:
```
log_udp_host = 127.0.0.1
log_udp_port = 514 # default
```

add support for logging to udp with syslog

---

oio/api/io.py
oio/common/exceptions.py
oio/conscience/client.py
tests/unit/api/test_ec.py
tests/unit/api/test_replication.py

Raise a ServiceBusy error when writing an object and the quorum of the
chunks is not reached, and this cannot be attributed to a timeout.
Jira: OS-434
- Python API
```
openio 4.6.1.dev26
```

Raise ServiceBusy when chunk quorum is not reached

---

oio/cli/admin/item_vacuum.py
oio/directory/admin.py
proxy/actions.h
proxy/metacd_http.c
proxy/sqlx_actions.c
setup.cfg
sqliterepo/replication_dispatcher.c
sqliterepo/sqlite_utils.h
sqliterepo/sqlx_macros.h
sqliterepo/sqlx_remote.c
sqliterepo/sqlx_remote.h
sqliterepo/sqlx_remote_ex.c
sqliterepo/sqlx_remote_ex.h
tests/functional/directory/test_admin.py

Defragment (call `vacuum`) the database on the master service, then resynchronize it on the slaves. This works for meta0, meta1 and meta2 services, but the CLI only implements it for meta2 services (`openio-admin container vacuum`).
Jira: OS-299
- sqliterepo
- CLI
```
openio 4.6.1.dev25
```

Defragment meta2 databases on demand

---

oio/account/client.py
oio/account/server.py
oio/api/object_storage.py
oio/common/constants.py
oio/common/decorators.py
tests/unit/account/test_accountclient.py

As for `ObjectStorageApi`, apply timeouts passed to the `AccountClient` constructor to all method calls.
- Python API
```
openio 4.6.1.dev53
```

Forward timeout parameters to AccountClient

---

core/ext.c
metautils/lib/comm_message.c
oio/api/object_storage.py
oio/conscience/checker/http.py
oio/conscience/stats/http.py
proxy/metacd_http.c
rdir/rdir.c

Add more prefix for request-id to identify operation
Some debugs logs will be emitted with EXTRA_DEBUG when proxy receives request without reqid or reqid is generated without prefix
sds
```
5.0.1dev4
```
We have still investigate why DB_USE from autocreate operation doesn't reuse reqid from original request.

Set an operation-dependent prefix on request ids

---

oio/blob/converter.py
oio/cli/admin/item_check.py
oio/common/utils.py
oio/crawler/integrity.py
tests/functional/crawler/test_integrity_crawler.py

- Implement new parameters to control when the tool reports problems:
- after a specified number of confirmations,
- after a specified delay.
- Allow the tool to wait between passes.
- Send broken object events to a user-selected queue, for example the input queue of `oio-blob-rebuilder`. It is advised to also specify a delay before sending events, otherwise temporary failures may trigger unwanted chunk rebuilds.
- `oio-crawler-integrity`
```
openio 4.6.1.dev15
```

Better integrity crawler

---

tools/oio-reset.sh

Detect the active socket of gridinit from the kernel instead of the presence of the file (unreliable).
enhancement
oio-reset
`openio 5.1.1.dev38`

oio-reset: Fix the startup detection for gridinit

---

core/ext.c
core/oioext.h
meta2v2/meta2_backend.c
meta2v2/meta2_filters.h
meta2v2/meta2_filters_action_container.c
meta2v2/meta2_filters_extract.c
meta2v2/meta2_gridd_dispatcher.c
meta2v2/meta2_macros.h
meta2v2/meta2_server.c
metautils/lib/comm_message.c
metautils/lib/metacomm.h
oio/event/beanstalk.py
proxy/common.c
proxy/common.h
proxy/m2_actions.c
proxy/meta2v2_remote.c
proxy/meta2v2_remote.h
proxy/sqlx_actions.c
sqliterepo/election.c
sqliterepo/election.h
sqliterepo/replication_dispatcher.c
sqliterepo/repository.c
sqliterepo/sqliterepo.h
sqliterepo/sqlx_remote.c
sqliterepo/sqlx_remote.h
sqliterepo/synchro.c
sqliterepo/synchro.h
sqlx/sqlx_service.c
tests/functional/api/test_objectstorage.py
tests/unit/test_sqliterepo_election.c

Some operations like M2_CREATE, DB_USE and DB_VERS now send the list of peers in the request. In the case where the called service does not have the database already, it is no more forced to call meta1 to get the list.
Jira: OS-374
- oioproxy
- sqliterepo
- meta2
```
openio 5.1.1.dev47
```
When benchmarking this, we should see a decrease of the number of `M1_LIST` calls.

Reduce the number of requests from meta2 to meta1

---

cluster/module/CMakeLists.txt
core/CMakeLists.txt
meta0v2/CMakeLists.txt
meta1v2/CMakeLists.txt
meta2v2/CMakeLists.txt
metautils/lib/CMakeLists.txt
rawx-lib/tools/CMakeLists.txt
sqliterepo/CMakeLists.txt
tools/CMakeLists.txt
tools/event-benchmark/CMakeLists.txt

The tools related to development tasks is only installed if the suite is built with `CMAKE_BUILD_TYPE=Debug`. It will avoid deploying `oio-reset.sh` (and its friends) with any package.
simplification
cmake
`openio 5.1.1.dev58`

cmake: Only install prod-related tools in other build types than Debug

---

rawx-apache2/src/rawx_chunk_update.c
rawx-apache2/src/rawx_repo_core.c
rawx-apache2/src/rawx_repository.c
tools/oio-bootstrap.py

When an error occurs after the rawx has already sent the first response, only this error response appears in the access log. To help debugging these cases, display the first error in the main log file.
Instead of logging the time the request started, be consistent with all other OpenIO SDS services, and log the time the request ended. Also, to help matching log lines that do not carry a request ID, display the time with microseconds.
- rawx
```
5.2.2
```

rawx: log bad requests, enhance log format

---

tests/functional/cli/container/test_container.py
tests/utils.py

Fix the behavior of the `wait_for_score` method when no service has registered yet. Call this method in some tests to make them more reliable.
- tests
```
openio 4.8.1.dev17
```

Make some tests more reliable

---

oio/common/utils.py
oio/directory/indexer.py
tests/functional/cli/container/test_container.py
tests/utils.py

Fix an issue with container list and non-ASCII characters.
- Python API
- CLI
```
openio 4.8.2.dev12
```
The bug manifested itself with something like:
```
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/cliff/app.py", line 401, in run_subcommand
result = cmd.run(parsed_args)
File "/home/fvennetier/src/public_git/oio-sds/oio/cli/__init__.py", line 126, in run
super(Lister, self).run(parsed_args)
File "/usr/lib/python2.7/site-packages/cliff/display.py", line 119, in run
self.produce_output(parsed_args, column_names, data)
File "/usr/lib/python2.7/site-packages/cliff/lister.py", line 82, in produce_output
parsed_args,
File "/usr/lib/python2.7/site-packages/cliff/formatters/table.py", line 101, in emit_list
self.add_rows(x, column_names, data) …
```

CLI: fix container list with non-ASCII characters

---

core/log.c
oio/account/server.py
oio/api/base.py
oio/api/ec.py
oio/api/io.py
oio/blob/client.py
oio/blob/indexer.py
oio/common/decorators.py
oio/common/wsgi.py
oio/event/filters/content_cleaner.py
oio/event/filters/volume_index.py
oio/rdir/client.py
tests/functional/api/test_objectstorage.py
tests/functional/content/test_content_perfectible.py
tests/unit/api/test_objectstorage.py
tests/utils.py

The request ID header name was sometimes written with an upper case 'X', sometimes with a lower case one, until the introduction a constant. Unfortunately, this constant was not used everywhere...
- Python API
- account
```
openio 4.8.2.dev3
```

Python API: fix request ID header name

---

oio/cli/election/election.py
sqliterepo/election.c
sqliterepo/synchro.c
sqliterepo/synchro.h

When calling `openio-admin election debug`, the JSON object will now show the full path to the ZooKeeper node, and the server address. And if the `--human` option is specified, full dates will be printed instead of timestamps.
- CLI
```
openio 4.8.2.dev16
```

Prettier election debug

---

oio/account/backend.py
oio/blob/converter.py
oio/cli/admin/service_decommission.py
oio/cli/admin/xcute.py
oio/cli/container/container.py
oio/common/green.py
oio/common/timestamp.py
oio/common/utils.py
oio/crawler/integrity.py
oio/xcute/client.py
oio/xcute/common/backend.py
oio/xcute/common/exceptions.py
oio/xcute/common/job.py
oio/xcute/common/manager.py
oio/xcute/common/worker.py
oio/xcute/jobs/__init__.py
oio/xcute/jobs/mover.py
oio/xcute/jobs/tester.py
oio/xcute/orchestrator.py
oio/xcute/server.py
tests/functional/account/test_backend.py
tests/functional/account/test_server.py
tools/oio-bootstrap.py

- Stop using pickle
- Send the tasks by batch
- Allow to use ratelimit
- Count the errors by type
- Use python time instead of redis time
- Keep the job in the workers' cache
- `xcute`
```
openio 5.2.2
```

xcute: Send the tasks by batch

---

oio/common/green.py

Fix ratelimit
- Python API
```
openio 4.8.2.dev6
```
Before:
```
loop 1:    run_time = now
loop 1:
loop 1:    run_time' = run_time + time_per_request
loop 1: -> run_time' = now + time_per_request
loop 2:    now' >= now
loop 2:
loop 2: To verify
loop 2:    run_time' - now' > time_per_request
loop 2: -> now + time_per_request - now' > time_per_request
loop 2: -> now - now' > 0
loop 2: -> now > now'
loop 2: => impossible: now' >= now
loop 2: => never sleep
loop 2:
loop 2:    run_time'' = run_time' + time_per_request
loop 2: -> run_time'' = now + time_per_request + time_per_request
loop 2: -> run_time'' = now + (2 * time_per_request)
loop 3:    now'' >= now'
loop 3: -> now'' >= now' >= now
loop 3:
loop 3: To verify
loop 3:    run_time'' - now'' > time_per_request
loop 3: …
```

Python API: Fix ratelimit

---

sqliterepo/election.c
sqliterepo/synchro.c
sqliterepo/synchro.h

Removing watches before deleting ZooKeeper nodes prevents these watches to trigger callbacks after the election is gone (this happens when ZooKeeper is under heavy load).
This modification requires ZooKeeper 3.5. Behavior with older versions is unchanged.
- sqliterepo
```
openio 5.2.3.dev8
```

Remove ZooKeeper watches before deleting nodes

---

metautils/lib/common_main.c
oio/cli/zk/set.py
oio/zk/client.py

Make `openio zk` commands return 1 after an error.
And for several C language commands:
- do not print the usage help twice;
- do not print the usage help when parameters are valid;
- provide tips to find the error log.
Jira: OB-475
- CLI
- meta0
- meta1
- meta2
```
6.0.0.0a1
```

Improve return code and output of some commands

---

oio/api/ec.py

Prevent from writing simultaneously on same socket
- Python API
```
openio 4.8.2.dev8
```
```
Failed to upload /home/test in test-perf: RAWX write failure, quorum not reached (4/5): {"finish: Second simultaneous write on fileno 18 detected.  Unless you really know what you're doing, make sure that only one greenthread can write any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of GreenThread object at 0x7fd7420b2550>; THAT THREAD=FdListener('write', 18, <built-in method switch of GreenThread object at 0x7fd7420b20f0>, <built-in method throw of GreenThread object at 0x7fd7420b20f0>)": …
```

Prevent from writing simultaneously on same socket

---

oio/xcute/orchestrator.py

Keep tasks order to update tasks sent, because the backend must have the tasks in order to know the last task sent
- `xcute`
```
openio 5.2.2
```

xcute: Keep tasks order to update tasks sent

---

proxy/m2_actions.c

Prevent the use of old peers if the container has already existed and is still in the cache
- `proxy`
```
openio 5.2.3.dev1
```

Decache user when creating container

---

core/oiostr.h
core/str.c
oio/directory/admin.py
sqliterepo/election.c
sqliterepo/replication_dispatcher.c
sqliterepo/repository.c
sqliterepo/sqliterepo.h
tests/functional/api/test_objectstorage.py
tests/functional/cli/container/test_container.py
tests/functional/content/test_service_id.py

The tests of the container snapshot feature were flaky. This is because there was a real bug. This pull request aims at fixing this bug. It also reorganizes the tests.
- sqliterepo
```
openio 6.0.1.dev2
```
The usual error message triggered by the bug was:
```
oio.common.exceptions.ServiceBusy: COMMIT failed: (SQLITE_CONSTRAINT) constraint failed [127.0.0.1:6018/470/Remote diff missed] [127.0.0.1:6017/470/Remote diff missed] Not enough successes, no quorum (1/3) (HTTP 503) (STATUS 503)
```

sqliterepo: fix the snapshot feature

---

oio/common/logger.py
tools/oio-crash-logger.py
tools/oio-test-suites.sh

A change in Python 3 (https://bugs.python.org/issue29808)
leads to a stack overflow when /dev/log does not exists.
```
openio 6.0.0
```

Fix logging issue when /dev/log does not exists in Python 3

---

meta2v2/meta2_backend.c
meta2v2/meta2_gridd_dispatcher.c
proxy/m2_actions.c
proxy/meta2v2_remote.c
proxy/meta2v2_remote.h
proxy/metacd_http.c

Allow to force the request on master service.
It was already possible to do this by adding 'proxy.force.master'
in the proxy configuration. But this was applied to all requests.
If we wanted to force the master only on a specific request,
we can add the 'x-oio-force-master' header in the request.
But this header was only used to list the objects in a container.
Now, it is possible to specifically force the master on all meta2 requests.
- `proxy`
- `meta2`
```
openio 5.2.4.dev1
```

proxy: Allow to force the request on master service

---

server/transport_gridd.c
server/transport_gridd.h
sqlx/sqlx_service.c

The error messages emitted after IO errors were detected had different syntaxes, making it difficult to search for them in the logs. This is now fixed.
Also, a new message will now tell is the IO error checking thread is stalled for a long time.
- main server code
- sqliterepo
```
openio 5.2.3
```

server: display better messages after IO errors

---

sqliterepo/repository.c
sqliterepo/sqliterepo.h

Check integrity of database as late as possible
- `sqliterepo`
```
openio 4.8.2.dev10
```

Check the size before the integrity when dumping database

---

oio/event/filters/notify.py

Encode without whitespace when notifying event to make sure not to exceed the maximum size of the event (default: 65535).
Jira: OS-472
```
openio 4.8.2.dev13
```

event-agent: Encode without whitespace when forwarding an event

---

oio/blob/mover.py

Fix usage check interval.
After one hour (default), the check was performed for each chunk.
- `blob-mover`
```
openio 4.8.2.dev15
```

blob-mover: Fix usage check interval

---

oio/cli/directory/directory.py
setup.cfg

During a rebalance operation, check each reference prefix is managed by the right number of meta1 services.
Also implement a new 'openio directory check' command, checking each reference prefix is managed by the right number of meta1 services. This complements 'openio-admin directory check' (which does not check this number).
Jira: OS-470
- CLI
```
openio 5.3.0.dev3
```

CLI: check peer count before actually rebalancing meta1

---

oio/cli/admin/xcute/job.py
oio/xcute/common/backend.py

Improve job information display
- `xcute`
```
openio 5.2.5.dev124
```
```
$ openio-admin xcute job show 20200107131129138805-7cd19983bb0
+--------------------------------+----------------------------------+
| Field                          | Value                            |
+--------------------------------+----------------------------------+
| config.params.end              | 10000                            |
| config.params.error_percentage | 0                                |
| config.params.start            | 0                                |
| config.tasks_batch_size        | 32                               |
| config.tasks_per_second        | 32                               |
| errors.total                   | 0                                |
| …
```

xcute: Improve job information display

---

rawx/chunk_info.go
tests/functional/blob/test_blob.py

When the chunk size extended attribute was missing, the rawx service used to fail while trying to parse an integer from an empty string (`Failed to load xattr: strconv.ParseInt: parsing "": invalid syntax`). Now, when the attribute is missing, it won't try the integer conversion, and simply return the expected code 412.
- rawx
```
6.1.0.0a0-29-gf0b4a00d
```

rawx: fix behavior when chunk size attr is missing

---

rawx/chunk_info.go
tests/functional/blob/test_blob.py

Use another approach to fix the problem described in #1978.
- rawx
```
openio 6.1.0.0a0-30
```

rawx: fix behavior when chunk size attr is missing (again)

---

oio/common/client.py
oio/container/client.py

Do not assume the proxy url is plain text http
We want to use https from the swift proxy to the oio proxy, but using an `https://` url as `sds_proxy_url` in `proxy-server.conf` does not work. This appears to fix the issue.
oio client common
whatever it is master is? tested on 5.2.2
Reproducer steps:
- setup an https frontend to oioproxy (whatever reverse proxy that supports ssl terminaison) and configure `sds_proxy_url` to `https://<ip>:<port>` in `oioswift`'s `proxy-server.conf`
- try to run a request, fails with internal error `No address found`, probably because the https is not stripped properly from the netloc and it cannot resolve it.
- try again with patch, it should work.
Note: there is no SSL certificate validation, I would have assumed that change to fail a …

client: allow https for proxy url

---

oio/cli/admin/xcute/lock.py
oio/xcute/client.py
oio/xcute/common/backend.py
oio/xcute/jobs/tester.py
oio/xcute/server.py
setup.cfg

Add a lock system to xcute to avoid collisions between jobs.
Each job type defines its lock based on its parameters. The lock is taken when the job is created, and released when it finishes or fails.
xcute
Results of the CLI commands:
```
(venv) openio@f12651ea56b2:/tmp/src/oio-sds$ openio-admin xcute lock list
+------+----------------------------------+
| Lock | Job ID                           |
+------+----------------------------------+
| a    | 20200120074545861743-802a3d50197 |
| aa   | 20200120074838579195-f4d429568d3 |
| abb  | 20200120074937560447-51af50063c5 |
| b    | 20200120074547476397-d5c7e58d0af |
+------+----------------------------------+
(venv) openio@f12651ea56b2:/tmp/src/oio-sds$ openio-admin xcute lock show abb …
```

xcute: locks feature

---

oio/xcute/jobs/blob_mover.py

The total task estimation for the xcute task blob mover is approximately twice what it should be.
xcute

xcute: fix total tasks estimation for the blob mover

---

oio/api/base.py
oio/cli/common/clientmanager.py
oio/common/client.py
oio/common/http_urllib3.py
oio/container/client.py

urllib3 request pool does not validate server certificate by default for https connections until version 1.25 (at which point we would want to specify ca_certs anyway)
This just allows infrastructure to pass the option through and add `ca_certs` and `cert_reqs` to parameter whitelist.
common?
This builds on top of #1948, so should only be merged after that.
There is no way to do https without anyway so it won't be missed :)
(also note I didn't test the api/base part as gateway swift only uses ClientManager, but figured I might as well try that..)

Pass options for `ca_certs` and `cert_reqs`

---

oio/account/server.py
proxy/m2_actions.c
rdir/rdir.c

Limit size of lists:
- Python doesn't release the memory when we delete a large object
- The service doesn't stay blocked for too long
Jira: OS-485
- `account`
- `proxy`
- `rdir`
```
openio 4.8.3.dev5
```

Limit size of lists

---

meta1v2/meta1_backend_properties.c
tests/functional/api/test_directory.py

Fix behavior when reference property with empty value is set
- `meta1`
```
openio 5.3.0.0b1.dev7
```

meta1: Fix behavior when reference property with empty value is set

---

oio/common/http_eventlet.py

When a HTTP request is made from Python API, path is always prefixed by `/`:
it has raised an issue when adding package prometheus into rawx where the request
returns a 301 with proper path.
Python internals
```
master
```
```
```

Avoid prefixing http path if / is already set

---

oio/xcute/common/backend.py

When deleting an xcute job, we were deleting its associated lock without checking that the lock was actually held by that job. If a running job had the same associated lock, the lock would wrongly be deleted.
xcute

Fix lock deletion on job deletion

---

oio/cli/admin/service_check.py

- Make variable names intelligible (no more one letter variables).
- Replace some assertions by exceptions, with messages telling what is wrong.
Jira: OS-491
- CLI
```
openio 5.3.0.0b1.dev14
```

Admin CLI improvements

---

sqliterepo/sqlite_utils.c

Sometimes the admin table of meta2 services contains NULL keys.
When this rare condition is met, the meta2 service crashes.
This PR ensures that meta2 services won't crash and will emit a error instead.
```
BUG: Base [30AE0C4B4F4E75E44CBC92465BACCCD87A98CEB39F0C967230D20272019CCB4E.1][meta2] has null keys in admin table.
```
meta2
```
5.2.3
```

sqliterepo: ignore malformed keys in admin table

---

proxy/actions.h
proxy/cs_actions.c
proxy/metacd_http.c
tests/functional/conscience/test_conscience.py

Provide a route to get the score of a single service in `oio-proxy`.
```
{
"addr": "127.0.0.1:6010",
"score": 45
}
```
enhancement
oio-proxy
`openio 5.3.0.0b1.dev31`

proxy: Get the score of a single service registered in ConsciousGrid

---

oio/cli/directory/directory.py
oio/directory/meta0.py
tests/unit/test_prefixmapping.py

Respect minimum distance when rebalancing meta1 databases
- Python API
```
openio 4.8.3.dev5
```

Respect minimum distance when rebalancing meta1 databases

---

oio/api/object_storage.py
oio/common/cache.py
oio/common/storage_functions.py
oio/container/client.py
tests/functional/api/test_objectstorage.py

Allow to cache object metadata
- Python API
```
openio 4.8.3.dev5
```

Python API: Allow to cache object metadata and location

---

rawx/chunk_info.go
rawx/const.go

When a chunk is uploaded in other storage_policy than EC,
the metachunk-size and metachunk-hash is no sent by client.
When rawx read this chunk, it complains about missing xattr.
This PR will ignore only these xattr.
rawx
```
master
```

rawx: ignore errors for few xattr

---

oio/cli/admin/xcute/rawx.py
oio/xcute/common/job.py
oio/xcute/jobs/blob_rebuilder.py
oio/xcute/orchestrator.py

Allow to set incident date when rebuilding
- `xcute`
```
openio 5.3.1.dev10
```

Allow to set incident date when rebuilding

---

rawx/buffer_pool.go
rawx/chunk_info.go
rawx/const.go
rawx/filerepo.go
rawx/handler_chunk.go
rawx/logger.go
rawx/main.go
rawx/notifier.go
rawx/rawx.go

A shared cache for large buffers is used for stream operations (upon uploads)
Another shared cache for small buffers is used for xattr operations.
enhancement
rawx
something like 5.3

rawx: Implement a buffer cache to avoid GC complications

---

bin/oio-meta2-rebuilder

A reference of old parameter `references-per-second` was left in `oio-meta2-rebuilder`
Thanks to @pybt for the report
Closes  #2019
oio-meta2-rebuilder
```
openio 5.3.0
```

Fix meta2 rebuilder

---

sqlx/sqlx_service.c

Add an option to prevent any xattr check.
Welcome in the Danger Zone
sqliterepo
```openio 4.10.1.dev10```

sqliterepo: Restore an option to prevent any lock operation.

---

oio/common/client.py
oio/container/client.py

Refactor the code so we handle oioproxy's URL the same way, whether it comes from the application's configuration object, a keyword parameter, or the namespace configuration file.
If there is no scheme in the URL, consider it is HTTP. If there is a scheme, use it (but only HTTP will work at the moment).
- Python API
```
openio 5.4.0.dev7
```

Python API: fix oioproxy URL parsing

---

oio/cli/common/shell.py
oio/cli/object/object.py

To allow use of `--dump-perfdata` from other tools,
the perdata will be exposed as dedicated columns in output.
The previous output is still available through the `--debug` flag.
You should use format yaml or json for best output
Fixes #OS-520
cli
```
5.x
```
Best display with yaml formatter
```
openio --dump-perfdata object create a /etc/magic -f yaml
- Hash: 272913026300E7AE9B5E2D51F138E674
Name: magic
Perfdata:
data_size: 111
proxy:
meta2: 0.002684
overall: 0.0062420000322163105
resolve: 0.001771
rawx:
http://127.0.0.1:6010/92C08C2F08D20542F462965E0600154179761EA4B2F83B763F9345A4FAC68B14: 0.0006470000371336937
overall: 0.0011420000810176134
Size: 111
Status: Ok
```

cli: expose perfdata as dedicated entry

---

tools/oio-bootstrap.py

Limit the maximum number of databases open simultaneously to avoid using too much RAM
- CI
```
openio 5.5.1.dev2
```

CI: Limit the maximum number of databases open simultaneously

---

rawx/notifier.go

Go back to the default JSON encoder.
Prior to this fix, our method was maybe faster but incomplete due to unescaped characters.
`fix`
`rawx`
`openio 5.5.1.dev6`

rawx: Fix unescaped special characters in JSON events, Events config, beanstalkd concurrency

---

oio/api/object_storage.py
tests/functional/api/test_objectstorage.py

When overwriting an object, it happens that the cache is not cleared. Next read then fails miserably, because it tries to fetch chunks from the former object (which do not exist anymore).
The new code will attempt one retry after the cache has been cleared.
- Python API
```
openio 5.5.1.dev5
```

Python API: retry fetch when clues of dirty cache

---

oio/api/ec.py
oio/api/io.py
oio/api/object_storage.py
oio/api/replication.py
oio/common/http_eventlet.py
oio/common/utils.py
tests/functional/api/test_perfdata.py

- Call the system's monotonic time function instead of the oio-sds wrapper.
- Measure the time taken by the last send() call during uploads.
- Fix the download time and EC computation measurements.
- Python API
```
openio 5.5.2.dev2
```

Improve performance data collection

---

proxy/m2_actions.c

Limit size of object list when there is no max
- proxy
```
openio 5.5.3.dev1
```

proxy: Limit size of object list when there is no max

---

oio/conscience/agent.py
oio/conscience/stats/http.py

It appears that some services may be seen as down by the conscience but
still running: the http stats plugin did not implement timeout on requests.
conscience-agent
```
5.x
```

conscience-agent: add timeout for http stats

---

rawx/handler_chunk.go
rawx/handler_info.go
rawx/handler_stat.go
rawx/rawx.go

When rawx returns an error, there is only few codepath where more info is
logged as error.
I've chosen to always log error when we force connection to be closed instead of
adding LogError before each rr.replyWithError. 
rawx
```
7.0.0.0b2-dev1
```
```
```

rawx: add more logs when replying error

---

rawx/handler_chunk.go
rawx/handler_info.go
rawx/handler_stat.go
rawx/logger.go

With new feature to serve plain or TLS requests,
we should be able to distinguish traffic on monitoring.
This PR add field http or https on access logs:
```
juin 04 03:57:24 E480 OIO,OPENIO,rawx,1[15159]: 15159 access INF - 127.0.0.1:6009 127.0.0.1:36648 DELETE 204 2531 0 0 - create-3CE15D35F4DE0A077FCA1577A /B96C425504555470FAC63DFCA363DFD509DE150A3A982164D09E977FD7703602 http
juin 04 03:57:29 E480 OIO,OPENIO,rawx,1[15159]: 15159 access INF - 127.0.0.1:6010 127.0.0.1:56174 PUT 201 557 0 111 - create-3CF802CBDBE80BBF8F2CB1423 /ACFDCE4232A653A4C1162301F8A2DC4571EE998D7CBE802AB0548D46C0E95223 https
```
Fixes CUS-119
rawx
```
7.0.0.0a3
```

rawx: add tag http or https

---

oio/common/http_eventlet.py

During test, errors previously catch by OS-361 are not more catch when TLS mode is enabled.
Jira: R2004-5
oio
```
7.0.0.0b2-dev4
```
```
```

Python API: protect against read-after-close operations

---

etc/account-server.conf-sample
etc/xcute.conf-sample
oio/common/wsgi.py

when the setproctitle python package exist, gunicorn changes the process title which does not make sens (too generic). It is possible to use a custom title using the `proc_name` settings but it was not passed through (https://docs.gunicorn.org/en/19.3/configure.html#proc-name).
This changes pass through the parameter `proc_name`
- https://openio.atlassian.net/browse/OS-544
common/wsgi
```
openio-6.0.0
```
```
```

pass proc_name setting to guinicorn app

---

oio/common/cache.py
oio/container/client.py
tests/functional/api/test_objectstorage.py

Refresh the rawx scores from cache
Refresh every 30 seconds (default) so as not to request the proxy all the time.
- Python API
```
openio 5.5.3.dev7
```

Python API: Refresh the cached rawx scores

---

oio/xcute/common/backend.py

Fix xcute job listing not working in Python3.
xcute
The problem came from stringifying bytes, which become `b'my_string'` when converting into a string, instead of the wanted `my_string`.

xcute: fix job listing in python3

---

oio/common/storage_functions.py

Sort chunks with weighted random.
Shuffle close scores (less than 10 difference).
- Python API
```
openio 5.5.3.dev7
```

Sort chunks with weighted random

---

oio/conscience/agent.py

For a customer, we need to be able to watch multiple directories. this allow to split `include_dir` in muiltiple directory using the `:` separator. Then each directory is extracting using `glob` for maximizing possibilities.
- conscience-agent
```
openio 7.0.0
```
```
include_dir: "/etc/oio/sds/OPENIO/watch:/data/*/*/etc/OPENIO/watch"
```

allow multiple glob patterns in conscienceagent's include_dir conf

---

oio/cli/account/client.py
oio/cli/container/client.py
oio/cli/lifecycle/client.py

When using interactive CLI with 
```
$ openio --dump-perfdata
(openio) object create cnt /etc/magic
```
the `ObjectStorageAPI` is initialized though `lifeclycle/client.py` instead of `object/client.py`,
the perfdata attrbute is lost.
This PR replace duplicated API_NAME `storage` by `FIXME`
Note:
This PR requires https://github.com/open-io/oio-sds/pull/2033 to allow use of `--dump-perfdata`  in interactive mode.
cli
```
7.0.0.0a3
```

cli: cleanup make_client

---

sqliterepo/election.c

Display election last access and status time in the output of `openio-admin election debug`. This will help to debug election garbage collection.
- sqliterepo
```
openio 5.5.3
```
None.

sqliterepo: display election access time and last status

---

sqliterepo/replication_dispatcher.c

Show sqlite version (with compiled version and runtime version)
```
$ openio-admin meta2 info 127.0.0.1:6016
| sqlite                     | VERSION_COMPILED=3.31.1    |
|                            | VERSION_RUNTIME=3.31.1     |
|                            | COMPILER=gcc-9.3.0         |
|                            | ENABLE_COLUMN_METADATA     |
```
sqliterepo
```
7.0.2dev1
```

Enrich info on meta2 with SQLITE version

---

oio/account/backend.py

For statistics about buckets, `oio-exporter` needs to have access to the entire list of buckets. Currently, we have two options:
- `scan` with a match on `buckets:*` but this is not an option as performances are terrible
- `hscan` over `accounts:` and then for each account, `zscan` over `buckets:$account` but it's too complicated and does not fit well into oio-exporter code as we wish to separate fetching accounts and buckets metrics.
Account
```
7.x
```
Feel free to to use the following script for creating `buckets:` key from `buckets:*` key on existing cluster: https://github.com/open-io/oio-toolkit/blob/master/scripts/updates-buckets:.lua
```
local keys = redis.call("keys", "buckets:*")
for i, key in ipairs(keys) do
if key ~= "buckets:" then
local zrange = …
```

Store the global list of buckets under the "buckets:" key

---

oio/account/backend.py
oio/account/client.py
oio/account/server.py
oio/api/object_storage.py
oio/cli/container/container.py
setup.cfg
tests/functional/cli/container/test_container.py

Refresh account without impacting the bucket counters
- Use the bucket name already registered when it is not given
- Add all totals when a container is not yet associated with its bucket
- Refresh bucket counters
Jira: OS-562
- account
```
openio 5.5.5.dev7
```

account: Refresh account without impacting the bucket counters

---

meta0v2/meta0_client.c
meta0v2/meta0_gridd_dispatcher.c
meta0v2/meta0_remote.c
meta0v2/meta0_remote.h
meta1v2/meta1_prefixes.c
proxy/admin_actions.c
resolver/hc_resolver.c

We have seen services registered in the wrong namespace. But nothing prevented these services to be used. Now some request handlers will compare the input namespace against the configured one, and deny the request is they do not match.
- meta0
```
openio 5.5.5
```
To test the new feature, run this command:
```
OIO_NS="CRAP" oio-meta0-client "$(openio --ns OPENIO cluster list meta0 -c Addr -f value | head -n 1)" list
```
And you should see something like:
```
40113854942 58943 0053 log INF oio.m0v2 Dumping the whole META0
40113855362 58943 0053 log WRN oio.m0v2 META0 request error (418) : Requested CRAP on service running OPENIO namespace
```

Meta0: compare the requested namespace to the locally configured one

---

oio/cli/container/container.py
tests/functional/cli/container/test_container.py

Implement the `--bucket-name` parameter for `openio container set` and `openio container unset` commands.
Jira: OB-572
- CLI
```
openio 5.5.5
```

CLI: allow to set a bucket name on an already created container

---

etc/event-handlers.conf-sample
oio/account/backend.py
oio/account/server.py
oio/common/redis_conn.py
oio/event/filters/replicate.py

Improve the account service API to allow calling the master service even for reads.
Also add a parameter to the event-agent "replicate" filter to enable this feature, and display a message in case of exception while refreshing the "replication_enabled" parameter.
Jira: CUS-142
- Account service
- event-agent
```
oio-sds 5.5.5
```

account: allow to call the master service for reads

---

oio/account/backend.py

Do not try to decode "None" as UTF-8. This error was frequent but unfortunately it was ignored by our tests.
- account
```
openio 7.0.2.dev13
```

account: do not try to decode "None" as UTF-8

---

meta2v2/meta2_utils_lb.c
metautils/lib/utils_service_info.c
proxy/m2_actions.c

Remove few strains of the now-unsupported integration of B2.
With the previous cleanup, a warning was raised that made the compilation fail under specific conditions.
`fix`, `cleanup`
meta2, proxy
`openio 5.5.6.dev26`

Fix the compilation in Release mode

---

core/sds.c
oio/ecd/app.py

Enhance ECD and refresh `reqid for each use of C API.
The ECD did not use the reqid provided in each request, making difficult to investigate error 500. Please note only the EC upload/download has been patched.
On same trend, the C API was using an unique reqid for entire lifetime of `struct oio_sds_s *`, provided by `oio_sds_init`, even if several call of C API was made (`oio_sds_upload_from_buffer`, `oio_sds_upload`, ...). It was impossible to distinguish calls between them.
C API, ECD
```
openio 5.6.1.dev2
```

Enhance ECD and refresh reqid for each use of C API

---

oio/account/backend.py
tests/functional/account/test_backend.py

The compute of refresh for a bucket is now done by batch:
- a lock key is created and will hold ctime, mtime and marker.
- bucket info is set to 0
- a batch will parses at most 10000 containers and will update
stats.
- when a container for this bucket is updated, it will check
if lock key exists. If it exists, the bucket stats will be updated if container name is already parsed by refresh operation
(name is before or equal to marker)
account
```
5.6.1dev2
```

account: rework bucket refresh

---

proxy/cs_actions.c

When the application requests service lists, and these services are in oioproxy's cache, don't forget to set the type in the resulting structures.
The bug has been detected by running `openio container locate`: the "meta0" field remained empty.
- oioproxy
```
openio 5.6.1.dev2
```

proxy: set service type when extracting from cached JSON

---

CMakeLists.txt
core/ext.c
core/oiovar.h
core/var.c
metautils/lib/utils_svc_policy.c
tools/oio-build-with-warnings.sh
tools/oio-travis-failfast.sh

Nested functions require compiler "trampolines", which require the stack to be executable. This is a security issue, and recent compilers advise not to use trampolines.
This pull request adds a test script to count compilation warnings, and fixes some of them.
See #2087.
- core
- CI
```
master
```

Count build warnings, fix some nested functions (trampolines)

---

oio/cli/rdir/rdir.py
oio/rdir/client.py
setup.cfg
tests/functional/api/test_directory.py

Reassign new rdir to a service
These new parameters to the 'openio rdir bootstrap' command are there to help decommission a rdir (see https://github.com/open-io/oio-product-docs/pull/64)
- CLI
```
openio 5.6.2.dev1
```

Reassign new rdir to a service

---

rawx/filerepo.go

Improve error message when the volume XATTRs are wrong
- rawx (Go)
```
openio 5.6.2.dev2
```

rawx: Improve error message when the volume XATTRs are wrong

---

oio/container/client.py

Python3 returns float when a division occurs between two integers 
$ python2
Python 2.7.17 (default, Sep 30 2020, 13:38:04)
>>> 3 / 2
1
$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
>>> 3 / 2
1.5
oio
```
openio 7.1.1.dev4
```
```
```

oio: fix flush with Python3

---

meta2v2/meta2_utils.c

Fix purge deleted aliases
- Use version instead of creation time
- Select the current version to check if object is deleted
- `meta2`
```
openio 5.7.1.dev2
```
This bug is visible with a recent version of sqlite3 (like version 3.31.1).

meta2: Fix purge deleted aliases

---

oio/account/backend.py

When deleting a bucket, some entries were left in the account service. They are now cleaned.
Jira: OBSTO-161
```
openio 7.1.1.dev2
```

account: clean after bucket deletion

---

proxy/reply.c

Some low-level errors like CODE_AVOIDED (8) did not have a particular mapping to high-level errors, and thus triggered the ambiguous Internal Server Error (500) error. We choose to map these error to the Service Unavailable (503) which is better managed by calling applications (they usually retry the request after a delay).
- oio-proxy
```
openio 5.7.1.dev1
```

proxy: map more low-level errors to Service Unavailable (503)

---

oio/cli/container/container.py
oio/cli/election/election.py
sqliterepo/replication_dispatcher.c
sqliterepo/repository.c
sqliterepo/sqlite_utils.c
sqliterepo/sqlite_utils.h
tests/functional/cli/object/test_object.py

This PR will bring:
- some few fixes for CLI
- stats when a sync occurs
- expose sqlite stats through an admin request on `container/get_properties`
sqliterepo, CLI
```
5.x
```
```
$ openio container show big
+----------------------+-----------------------------------------------------------------------------+
| Field                | Value                                                                       |
+----------------------+-----------------------------------------------------------------------------+
| account              | AUTH_88fddfcf6d6c4a85baa1fc27c0ee24bf                                       |
| base_name            | 30AE0C4B4F4E75E44CBC92465BACCCD87A98CEB39F0C967230D20272019CCB4E.1          |
| bucket               | big …
```

Various fixes and enhancements

---

oio/xcute/common/backend.py
oio/xcute/orchestrator.py

Save sent tasks before they are processed.
In some cases, the task was processed before updating the list of sent tasks.
- `xcute`
```
openio 5.7.1.dev8
```

xcute: Save sent tasks before they are processed

---

oio/cli/admin/xcute/job.py
oio/common/easy_value.py
oio/xcute/client.py
oio/xcute/common/backend.py
oio/xcute/common/job.py
oio/xcute/common/worker.py
oio/xcute/server.py
setup.cfg

Allow to update job configuration (only when the job is paused).
- xcute
```
openio 5.7.1.dev8
```
```
$ openio-admin xcute rawx decommission 127.0.0.1:6012 --chunks-per-second 2 --min-chunk-size 112
+------------------------------------+----------------------------------+
| Field                              | Value                            |
+------------------------------------+----------------------------------+
| config.params.excluded_rawx        |                                  |
| config.params.max_chunk_size       | 0                                |
| config.params.min_chunk_size       | 112                              |
| config.params.rawx_timeout         | 60.0                             |
| config.params.rdir_fetch_limit     | 1000 …
```

xcute: Allow to update job configuration

---

oio/cli/admin/xcute/job.py
oio/xcute/client.py
oio/xcute/common/backend.py
oio/xcute/common/job.py
oio/xcute/orchestrator.py
oio/xcute/server.py

Improve job's listing
- Change information visible when listing jobs
- Allow to add filters when listing jobs
- xcute
- CLI
```
openio 5.7.1.dev9
```
```
$ openio-admin xcute job list --date 2020-12-17 --status FINISHED --type rawx-decommission --lock rawx/127.0.0.1:6012
+----------------------------------+----------+-------------------+---------------------+----------+
| ID                               | Status   | Type              | Lock                | Progress |
+----------------------------------+----------+-------------------+---------------------+----------+
| 20201217152503729224-056ec779394 | FINISHED | rawx-decommission | rawx/127.0.0.1:6012 | 100.00%  |
+----------------------------------+----------+-------------------+---------------------+----------+ …
```

xcute: Improve job's listing

---

oio/content/content.py
oio/content/ec.py
oio/content/plain.py

Use one of the rawx with a copy of the chunk to move
- Python API
```
openio 5.7.1.dev8
```

Use one of the rawx with a copy of the chunk to move

---

.travis.yml
etc/bootstrap-option-smallcache.yml
tests/functional/account/test_backend.py
tests/functional/blob/test_mover.py
tests/functional/cli/container/test_container.py
tests/functional/conscience/test_conscience.py
tests/functional/m2_filters/test_filters.py
tools/benchmark/oio-bench-object-create.py
tools/oio-test-unit.sh
tools/oio-travis-failfast.sh
tools/oio-webhook-test.py
tox.ini

Drop Python 2
Since gateway will use Python 3.7, launch tests with Python 3.7
oio
```
master
```

CI: convert remaining tests using python 2 to python 3.6

---

oio/api/io.py
oio/blob/client.py
tests/functional/cli/__init__.py

Do not reiterate data generators when they already yield bytes.
- Python API
```
openio 5.7.1.dev19
```

Do not reiterate data generators when they already yield bytes

---

rawx/chunk_info.go

Don't print error for missing compression attr, because compression is not mandatory
- rawx
```
openio 5.7.1.dev19
```

rawx: Don't print error for missing compression attr

---

rdir/rdir.c

Allow Prometheus to gather statistics directly from applications.
Jira: OB-487
- rdir
```
openio 6.1.0.0a0
```
None.

Export rdir statistics to the Prometheus format
