- client/c/lib/CMakeLists.txt
- client/c/lib/hc.h
- client/c/lib/hc_func.c
- client/c/tools/CMakeLists.txt
- client/c/tools/hc.c
- client/c/tools/hc_help.c
- client/c/tools/hc_help.h
- cluster/lib/config.c
* "oio <command>" debug trace : INFO -> DEBUG
* gridcluster false error DEBUG ->TRACE
* minor code reorganisation (oio help sections)
> Annoying traces removed

- rawx-lib/src/compression.h
- rawx-lib/src/lzo_compress.c
> rawx-lib: Fixes header

- metautils/lib/CMakeLists.txt
- tools/oio-grep.c
tools: oio-grep added.
metautils: fixed installation of missing header.
> Sample code for download

- client/c/lib/grid_client.h
Hi guys / girls :smiley: 
Trying to get started with the C client. I noticed a couple of typos. I hope this helps.
Best regards,
Conrad
> fix typos in grid_client.h

- client/c/lib/containers.c
- client/c/lib/grid_client.h
- tools/oio-grep.c
- tools/oio-roundtrip.c
metautils: fixed installation of missing header.
Conflicts:
client/c/lib/containers.c
> tools: new sample code, oio-grep & oio-roundtip

- python/CMakeLists.txt
- python/etc/event-agent.conf-sample
- python/oio/account/backend.py
- python/oio/account/server.py
- python/oio/common/daemon.py
- python/oio/common/http.py
- python/oio/common/utils.py
- python/oio/sds/event/agent.py
- python/setup.py.in
- python/tests/functional/account/test_backend.py
- python/tests/unit/common/__init__.py
- python/tests/unit/common/test_utils.py
- python/tests/unit/sds/event/__init__.py
- python/tests/unit/sds/event/test_agent.py
- tools/sds-bootstrap.py
WIP account service with redis backend
> event-agent now support async chunk delete

- README.md
- client/c/lib/content_upload.c
- client/c/lib/http_put.c
- client/c/lib/rawx.c
- client/c/lib/rawx.h
Delete from C client has been removed.
The removal feature has been implemented in an asynchronous fashion.
> Useless code removed

- README.md
- client/c/lib/grid_client.h
- cluster/module/module.c
- metautils/lib/utils_service_info.c
- proxy/README.md
- tools/CMakeLists.txt
- tools/oio-grep.c
- tools/oio-roundtrip.c
> Various cleanups.

- python/CMakeLists.txt
- python/bin/account-server
- python/etc/account-server.conf-sample
- python/etc/event-agent.conf-sample
- python/oio/account/backend.py
- python/oio/account/server.py
- python/oio/common/daemon.py
- python/oio/common/utils.py
- python/setup.py.in
- python/tests/functional/account/test_backend.py
- tools/sds-bootstrap.py
account backend now supports listing options (prefix, delimiter, limit, marker, end_marker)
> account-server bin

- README.md
- metautils/lib/hc_url.c
- proxy/common.c
- proxy/cs_actions.c
- proxy/dir_actions.c
- proxy/m2_actions.c
- proxy/metacd_http.c
- proxy/path_parser.c
- proxy/sqlx_actions.c
- sdk/oio_sds.c
- sdk/test_roundtrip.c
Are concerned:
* proxy
* hc_url (metautils)
* sdk
> URI-encoding management

- sdk/oio_sds.c
- server/network_server.c
In addition, the SDK computes the content's checksum upon upload.
> Restored protection on max cnx in the server core.

- client/c/lib/test_properties.c
- proxy/tests/functional/test_conscience.py
- proxy/tests/functional/test_directory.py
- proxy/tests/functional/test_meta2.py
I made a mistake on the python files indentation. I will fix that shortly.
> Client and proxy tests : a few corrections

- proxy/README.md
- proxy/m2_actions.c
The service type was not always ensured to an acceptable default value.
> Fixed container autocreation

- python/oio/common/client.py
- python/oio/common/exceptions.py
- python/oio/conscience/client.py
- python/oio/directory/client.py
directory & conscience client
more to come
> add internal proxy client

- README.md
- client/c/lib/content_upload.c
- meta2v2/meta2_utils_json_in.c
- metautils/lib/lb.c
- metautils/lib/lb.h
- proxy/actions.h
- proxy/cache_actions.c
- proxy/metacd_http.c
- tools/sds-bootstrap.py
* missing dependency documented
* fixed port overlapping in oio-bootstrap
* fixed printf formats
* proxy flush feature
* obsolete symbols replaced
> various fixes

- README.md
- python/requirements.txt
Confusion between xattr and pyxattr module.
> fix python dependency with xattr module

- tools/sds-bootstrap.py
This is enough for sandbox testing environments.
> oio-bootstrap : added /usr/local/bin in default PATH

- python/oio/account/server.py
> account-server: only log exception when using DEBUG log level

- proxy/common.h
- proxy/dir_actions.c
- proxy/m2_actions.c
- proxy/reply.c
- proxy/sqlx_actions.c
> proxy: fixed response status upon code=400 from the backend

- meta2v2/meta2_filters_action_container.c
- proxy/m2_actions.c
- proxy/metacd_http.c
* aliases order is now ascending
* you just get the number of items asked (trimmed to a reasonable value)
* the mex number of items is now well parsed
> m2v2: fixes around listing of contents

- metautils/lib/lb.c
- metautils/lib/lb.h
> lb: WRAND becomes the default algorithm (replacing RR)

- python/tests/functional/account/test_backend.py
- python/tests/functional/account/test_server.py
- tools/sds-bootstrap.py
commit af0a33c015ef3479b80bed163afb0010cbaa646c
func tests : now manage a JSON config
commit 60936b8b81597423206e9f7fd17d68d4a847083e
tools: oio-bootstrap.py also references the redis server in the test descr
> Jfs patch functest 20151012

- python/test-requirements.txt
Use another nose html output plugin (more user friendly) for testing report.
> Require swagger nose html output

- python/tests/functional/blob/test_blob.py
- tools/sds-bootstrap.py
add sds_path in test.conf file generated by oio-bootstrap.py
> fix blob func tests

- client/c/lib/content_upload.c
- core/oio_sds.h
- core/sds.c
- core/tool_roundtrip.c
- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_filters_action_container.c
- meta2v2/meta2_filters_action_content.c
- meta2v2/meta2_gridd_dispatcher.c
- meta2v2/meta2_utils.c
- meta2v2/meta2_utils.h
- meta2v2/meta2v2_remote.c
- meta2v2/meta2v2_remote.h
- meta2v2/test_meta2_backend.c
- meta2v2/test_meta2_dedup.c
- proxy/m2_actions.c
Impacts:
* meta2v2 (remote, backend)
* proxy
* C sdk
> core : explicit content links implemented.

- README.md
- python/oio/common/utils.py
- python/requirements.txt
What the hell is happening with pyxattr/xattr???
> python: use pyxattr

- cluster/lib/gridcluster.c
- metautils/lib/metatype_srvinfo.h
- metautils/lib/metautils_macros.h
- metautils/lib/test_lb.c
- metautils/lib/utils_service_info.c
- sqlx/sqlx_service.c
- svc-monitor/main.c
In addition, useless/unused code has been removed.
> cluster: stat.io restored in service_info descriptions.

- cluster/lib/gridcluster.c
- core/cfg.c
- core/proxy.c
- core/sds.c
- core/tool_roundtrip.c
- core/url.c
- meta1v2/meta1_remote.c
- metautils/lib/comm_message.c
- metautils/lib/description.asn
- metautils/lib/gridd_client.h
- metautils/lib/metacomm.h
- proxy/m2_actions.c
- proxy/metacd_http.c
- proxy/sqlx_actions.c
- sqliterepo/internals.h
- sqliterepo/replication.c
- sqliterepo/replication_client.c
- sqliterepo/replication_dispatcher.c
- sqliterepo/sqlx_remote.c
- sqlx/CMakeLists.txt
- sqlx/sqlx_client.c
- sqlx/test_sqlx_client.c
* pseudo-object implementation of an SQLX client
* partial pseudo-object implementation of a Directory client (meta0, meta1)
* services sub-tyes now managed well
> new feature: sqlx client

- cluster/lib/gridcluster.c
- meta0v2/meta0_utils.c
> Fixed memory pool management

- core/http_internals.h
- core/http_put.c
- core/http_put.h
- core/oio_sds.h
- core/oiocfg.h
- core/oiostr.h
- core/proxy.c
- core/sds.c
- core/str.c
- core/tool_roundtrip.c
- meta2v2/meta2_utils.c
- metautils/lib/metautils_strings.h
- metautils/lib/utils_hashstr.c
- metautils/lib/utils_strings.c
- rainx/rainx_repository.c
- rawx-apache2/src/rawx_repo_core.c
- rawx-apache2/src/rawx_repository.c
- rawx-lib/src/attr_handler.c
- rawx-lib/src/rawx.h
- tests/func/testlib_http.c
* Chunks hashes now computed when no EC used.
* Content hashes now cumputed
* Fixed parallel upload
* Fixed multi-chunks upload
> Many client-related fixes!

- core/oio_sds.h
- core/sds.c
+ Chunks positions parsing failed
> core: upload hook semantics changed

- meta2v2/meta2_filters_action_content.c
Lists longer than 16 items are split into batches.
Attempt to fix #255
> m2v2: events sent never manage more than 16 beans.

- cluster/conscience/conscience_srvtype.c
- core/sds.c
- meta2v2/meta2_utils.c
- proxy/m2_actions.c
- proxy/transport_http.c
- rainx/rainx_repository.c
- rainx/rainx_stats_rrd.c
- rawx-apache2/src/rawx_stats_rrd.c
- rawx-lib/src/compression.c
- server/slab.c
- server/transport_gridd.c
- sqlx/sqlx_service.c
Raised when compiling for 32bit architectures.
> Fixed printf format warnings

- core/sds.c
- core/tool_roundtrip.c
- core/url.c
- meta2v2/meta2_filters_action_container.c
- proxy/m2_actions.c
... makes the `tool_roundtrip` functional.
> Fixed LINK of an alias to content 

- python/oio/content/rain.py
- python/tests/functional/content/test_content.py
- python/tests/functional/content/test_dup.py
- python/tests/functional/content/test_rain.py
- python/tests/functional/rdir/test_rebuilder.py
- rainx/rainx_repository.c
- tools/sds-bootstrap.py
- tools/sds-reset.sh
To upload empty contents without error (core dump), I sent a fix for the librain.
> Fix upload of empty contents

- .travis.yml
Adds a call to core/tool_roundtrip that (at least) checks the most important parts of the C SDK.
> travis: makes the func tests pass

- proxy/m2_actions.c
- resolver/hc_resolver.c
- resolver/hc_resolver.h
- tools/sds-bootstrap.py
In general terms, there is now a better cache management (not decached when not necessary, fed when possible).
In addition, oio-bootstrap.py has been slightly modified to be better PEP8 compliant and generate also the configuration for the Java HTTP gateway.
> Efforts for less requests to m{0,1}v2

- meta0v2/meta0_client.c
- meta0v2/meta0_init.c
- meta1v2/meta1_client.c
- metautils/lib/common_main.c
In addition, stdout/stderr not redirected to /dev/null.
> Fixed return code for m0v2 CLI tools

- meta2v2/meta2_backend.c
- sqliterepo/election.c
- sqliterepo/election.h
- sqliterepo/replication.c
- sqliterepo/replication_dispatcher.c
- sqliterepo/repository.c
- sqliterepo/sqlite_utils.c
- sqliterepo/sqlite_utils.h
- sqliterepo/sqliterepo.h
- tests/unit/test_sqliterepo_election.c
Attempt to simplify the code before re-organizing it into pseudo-objects suitable for tests.
> sqliterepo: interface reduction

- python/etc/service-watch.yml
- python/oio/common/utils.py
- python/oio/conscience/agent.py
- python/oio/conscience/checker/base.py
- python/oio/conscience/stats/http.py
- python/oio/conscience/stats/rawx.py
- python/oio/conscience/stats/system.py
- python/oio/conscience/stats/volume.py
- python/requirements.txt
- python/setup.cfg
- tools/sds-bootstrap.py
Error handling is still missing, and you will get a lot of spam when a rawx shuts down.
> Add rawx statistics in conscience-agent

- tools/sds-bootstrap.py
add IP:PORT as group in gridinit
> bootstrap: clean names for rdir and account services

- .travis.yml
- python/oio/conscience/stats/http.py
- python/oio/sds/event/agent.py
- tools/sds-reset.sh
Try the "-v" option of oio-reset.sh for more information
> oio-reset: execution time limited + lighter output.

- python/oio/account/backend.py
- python/oio/blob/auditor.py
- python/oio/content/rain.py
- python/tests/functional/container/test_container.py
- tools/sds-bootstrap.py
- add missing constructor param to make account test pass again
- add 'score' to the list of fields returned by proxy for chunk requests
> python: fix some tests

- gridd/main/access_log.c
- sqliterepo/election.c
Fixes a format and a type conversion
> Builds on x86_32

- core/cs.c
- core/dir.c
- core/http_internals.h
- core/http_put.c
- core/internals.h
- core/sds.c
- sqliterepo/election.c
* SO_REUSEADDR
* SO_REUSEPORT (if available)
* SO_LINGER (toward proxy)
* TCP_NODELAY (toward proxy)
> core: proper sockopt set

- python/tests/utils.py
This should fix some tests relying on proxy's load balancer.
> Python tests: wait for service cache to reload after flushing it

- sqlx/oio_events_queue.c
The stream is paused at most 1s when the socket is not available (event-agent absent or clogged).
> events: pauses the events stream upon error.

- python/tests/functional/conscience/test_conscience.py
- python/tests/functional/reference/test_directory.py
> Fixes python tests

- python/oio/cli/client.py
- python/oio/cli/rdir.py
- python/oio/common/client.py
- python/oio/common/wsgi.py
- python/oio/rdir/client.py
- python/oio/rdir/server.py
- python/oio/rdir/server_db.py
- python/setup.cfg
add draft cli for rdir interaction
> rdir: explicit database create

- core/oiocfg.h
- rawx-apache2/src/mod_dav_rawx.c
- rawx-apache2/src/rawx_repo_core.c
- tools/sds-bootstrap.py
> rawx: Fixes the fsync() policy

- python/oio/conscience/stats/rawx.py
- python/oio/conscience/stats/volume.py
> oio-conscience-agent: tag.vol added for each monitored volume

- python/oio/account/backend.py
- python/tests/functional/account/test_backend.py
> account: improve container update

- oio/rdir/client.py
This speeds up event-agent by about 25%.
> rdir client: keep a cache of rdir addresses

- events/oio_events_queue_beanstalkd.c
- events/oio_events_queue_zmq.c
- oio/conscience/agent.py
- server/network_server.c
- sqliterepo/cache.c
- sqliterepo/repository.c
- sqliterepo/synchro.c
- sqlx/sqlx_service.c
> Less logs at service startup, less verbose connection errors in conscience-agent

- cluster/conscience/conscience_srvtype.c
- cluster/module/module.c
- core/oiocfg.h
- proxy/cache_actions.c
- proxy/lb_actions.c
- proxy/metacd_http.c
Timeouts, robustness, etc.
"It works on my machine".
> Miscellaneous improvements

- server/transport_gridd.c
> server: log access AFTER answering and log response size

- rawx-apache2/src/rawx_event.c
Currently is beanstalkd the only queue manager. If beanstalkd becomes
down it can lead to the unavailability of all the rawx on the host.
> rawx: makes the event queue asynchronous

- core/str.c
Fixes a memory management error when iterating over an UTF8 strings.
> utf8: fixed encoding

- proxy/m2_actions.c
Destined to replaces the properties in the headers, both are kept for
the transition.
> proxy: when listing, dups the properties in the body

- meta1v2/meta1_backend_services.c
- meta2v2/meta2_backend.c
- meta2v2/meta2_filters_action_content.c
- meta2v2/meta2_macros.h
- oio/event/consumer.py
- rawx-apache2/src/rawx_repo_core.c
- rawx-apache2/src/rawx_repository.c
- "meta1" prefix removed
- "meta2" prefix replaced by "storage"
- "rawx" prefix replaced by "storage"
- "container.create" replaced by "container.new"
- "container.destroy" replaced by "container.deleted"
- "chunk.delete" replaced by "chunk.deleted"
> Change event names

- events/oio_events_queue_beanstalkd.c
> events: better management of beanstalkd connections

- meta1v2/meta1_backend_services.c
- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_utils.c
- meta2v2/meta2_utils_lb.c
- metautils/lib/lb.c
- metautils/lib/lb.h
- proxy/lb_actions.c
- tests/unit/test_lb.c
> lb: better error messages

- .travis.yml
- core/oiostr.h
- core/url.c
- core/url_ext.h
- etc/event-agent.conf-sample
- etc/event-handlers.conf-sample
- events/oio_events_queue.c
- events/oio_events_queue.h
- meta1v2/meta1_backend_services.c
- meta2v2/meta2_backend.c
- meta2v2/meta2_filters_action_content.c
- oio/event/agent.py
- oio/event/beanstalk.py
- oio/event/consumer.py
- oio/event/evob.py
- oio/event/filters/account_update.py
- oio/event/filters/base.py
- oio/event/filters/content_cleaner.py
- oio/event/filters/notify.py
- oio/event/filters/volume_index.py
- oio/event/handlers/base.py
- oio/event/loader.py
- proxy/cache_actions.c
- rawx-apache2/src/rawx_event.c
- setup.cfg
- sqliterepo/sqlite_utils.c
- sqliterepo/sqlite_utils.h
- tools/oio-bootstrap.py
- tools/oio-travis-tests.sh
* fixed format (sender services)
* fixed signal management (event agent)
* fixed deployment for testing purposes
> Events review

- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_utils.c
- meta2v2/meta2_utils_lb.c
- meta2v2/meta2_utils_lb.h
- metautils/lib/lb.c
- metautils/lib/lb.h
- metautils/lib/storage_policy.h
- tests/unit/test_lb.c
- tools/oio-bootstrap.py
- tools/oio-reset.sh
New 'weak' option to data treatments, allowing to relax the distance
requirements if they were not satisfiable. This allows requiring more
chunks than the number of services locations. Note that using this
option may lead to unbalanced situations.
> New 'weak' load balancing option

- cluster/conscience/conscience_srv.c
- core/ext.c
- core/log.c
- core/oiocfg.h
- core/proxy.c
- gridd/main/server.c
- meta2v2/generic.c
- metautils/lib/lb.c
- metautils/lib/utils_service_info.c
- metautils/lib/utils_strings.c
- metautils/lib/utils_svc_policy.c
- proxy/common.h
- proxy/m2_actions.c
- proxy/metacd_http.c
- proxy/transport_http.c
- sqliterepo/replication.c
In addition, here are minor proxy cleanups.
> Benefits from optimized strcmp() when case sensitivity is not worth

- events/oio_events_queue_beanstalkd.c
> events/beanstalkd: fixed `use` command

- proxy/common.c
- proxy/common.h
- proxy/m2_actions.c
add the function 
gboolean _request_get_flag (struct req_args_s *args, const char *header, const char *flag, const gboolean default_value);
> proxy/common.c : add a function to recover flags from url or header

- oio/event/beanstalk.py
- oio/event/consumer.py
- oio/event/filters/notify.py
(cherry picked from commit d4c868e92155f5060fc1efd56314f989602314a4)
> event-agent: beanstalk interaction reviewed

- core/internals.h
- core/oio_sds.h
- core/sds.c
- core/tool_roundtrip.c
> core: more DL tests with ranges

- core/http_internals.h
- core/oio_sds.h
- core/proxy.c
- core/sds.c
- core/tool_roundtrip.c
- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_filters_action_content.c
- meta2v2/meta2_filters_extract.c
- meta2v2/meta2_gridd_dispatcher.c
- meta2v2/meta2_utils.c
- meta2v2/meta2_utils.h
- meta2v2/meta2v2_remote.c
- meta2v2/meta2v2_remote.h
- metautils/lib/metautils_macros.h
- proxy/actions.h
- proxy/m2_actions.c
- proxy/metacd_http.c
- tests/func/testlib_sds.c
This will allow optimized random writes (to change 1 byte, you will
have to download and reupload only 1 metachunk, not the whole content).
> Implement metachunk replacement

- core/CMakeLists.txt
- core/oio_sds.h
- core/sds.c
- core/tool_rawx.py
- core/tool_roundtrip.c
- core/tool_sdk.c
- meta2v2/m2gen.py
- tests/func/test_oiosds.py
* added robustness with invalid chunk positions
* interface reviewed to report typed content "system" properties
* a lot of fixes around buffers management
> C SDK: fixes and improvements

- core/http_put.c
- core/internals.h
- core/log.c
- core/oiolog.h
- sqlx/sqlx_client.c
- sqlx/sqlx_client.h
- tools/oio-bootstrap.py
* sqlx: SQL queries dumped in the abstract client
* core: allows plugging a custom log handler for a better integration with tools providing a custom logging method.
> core + sqlx: more debug when triggered

- CMakeLists.txt
- events/oio_events_queue_beanstalkd.c
- tests/unit/event/CMakeLists.txt
- tests/unit/event/server.c
- tests/unit/event/server.h
- tests/unit/event/test_events_beanstalkd.c
oio/events : verify content received from beanstalkd
tests : adding some tests to verify beanstalkd requests
> events - check response from beanstalkd requests

- oio/api/backblaze_http.py
see https://help.backblaze.com/hc/en-us/articles/224959187-B2-Domain-Migration-Plan for more details
> oio/api/backblaze_http : change api url to match new backblaze api url

- core/lb.c
- meta2v2/meta2_backend.c
- meta2v2/meta2_utils_lb.c
- meta2v2/meta2_utils_lb.h
- metautils/lib/metatype_srvinfo.h
- metautils/lib/utils_service_info.c
- proxy/m2_actions.c
> core,m2: fix spare chunk requests

- core/http_internals.h
- core/oio_sds.h
- core/proxy.c
- core/sds.c
oio_sds_get_usage() is used by oiofs.
> core: fix oio_sds_get_usage()

- metautils/lib/utils_service_info.c
- oio/cli/admin/cluster.py
- oio/cli/clientmanager.py
- oio/cli/shell.py
- proxy/cs_actions.c
- setup.cfg
- tests/functional/conscience/test_conscience.py
- tools/oio-reset.sh
- tools/oio-wait-scored.sh
> cli: add 'openio cluster unlockall' command

- proxy/common.c
- proxy/common.h
- proxy/dir_actions.c
- proxy/m2_actions.c
- proxy/sqlx_actions.c
> proxy: fail on empty properties requests

- tools/oio-bootstrap.py
> rawx: trace follows the oio-sds logging format

- core/lb.c
- metautils/lib/utils_service_info.c
- proxy/actions.h
- proxy/common.h
- proxy/lb_actions.c
- proxy/metacd_http.c
- tests/functional/conscience/test_conscience.py
- tests/utils.py
* core: ceinture
* metautils: bretelles
> Various fixes around LB pools

- oio/api/object_storage.py
Fixes #502
Explicit message telling no account service is available.
> cli: better message when all the services are locked

- oio/api/directory.py
- oio/cli/admin/directory.py
- oio/cli/admin/volume.py
- oio/conscience/agent.py
- oio/conscience/client.py
- oio/directory/meta0.py
- oio/rdir/client.py
- setup.cfg
- tests/functional/api/test_directory.py
- tools/oio-reset.sh
rdir are linked to rawx by `openio directory bootstrap`.
> Better rdir balancing

- cluster/conscience/conscience_srv.c
- cluster/conscience/conscience_srv.h
- cluster/conscience/conscience_srvtype.c
- cluster/module/module.c
- core/dir.c
- core/http_internals.h
- core/oio_sds.h
- core/oiodir.h
- core/proxy.c
- core/sds.c
- oio/api/ec.py
- oio/api/object_storage.py
- oio/common/utils.py
- oio/event/filters/content_cleaner.py
- tools/oio-bootstrap.py
* Implement reference properties in C client.
* Fix container properties reading.
* Factorize code.
> Various fixes and improvements on properties

- etc/bootstrap-container-x3.yml
- etc/bootstrap-directory-x3.yml
- tools/CMakeLists.txt
- tools/oio-bootstrap.py
- tools/oio-echo-server.c
- tools/oio-election-reset.py
- tools/oio-reset.sh
- tools/oio-test-config.py
- tools/oio-tool.c
- tools/zk-bootstrap.py
- tools/zk-reset.py
- tox.ini
In addition, the PEP8 compliance has been improved, tabulations became spaces, etc.
> CLI tools to reset elections at the ZK level

- meta1v2/meta1_gridd_dispatcher.c
- metautils/lib/gridd_client.c
- oio/cli/clientmanager.py
- oio/common/http.py
- oio/conscience/agent.py
- oio/ecd/app.py
- oio/event/evob.py
- oio/event/loader.py
- sqliterepo/synchro.c
- tests/func/test_oiohttp.py
- tests/func/test_oiosds.py
- tests/unit/api/test_backblaze_http.py
- tools/CMakeLists.txt
- tools/oio-election-dump.py
- tools/oio-election-smudge.py
- tools/oio-rdir-harass.py
* meta1: output strings not freed when transaction commits fail
* metautils: error possibly forgotten
* sqliterpo: minor leak when resyncing a DB on the master
> Fix memleaks

- core/cfg.c
- core/oiocfg.h
- rawx-apache2/src/mod_dav_rawx.c
- sqliterepo/election.c
- sqliterepo/synchro.c
- sqliterepo/synchro.h
- sqlx/sqlx_service.c
- tools/oio-bootstrap.py
* ZK Connection string shuffling
* ZK is now configurable for oio-reset.sh (allows to use a cluster instead of a single local node).
* Counters properly reset when re-candidating to an election
> Minor improvements around ZK usage and elections

- server/network_server.c
It prevents a spam of 500-coded errors because of a repository being closed.
> server: drop UDP messages in queue at exit

- sqliterepo/election.c
aborts elections after the ZK disconnects.
> sqliterepo/election: intercepts ZK disconnects

- metautils/lib/metatype_m1url.h
- metautils/lib/utils_m1url.c
- proxy/common.c
- proxy/sqlx_actions.c
> proxy: repair /admin/status and /admin/debug

- oio/rdir/client.py
Fixes #790.
It happened in `openio directory bootstrap` when all the rdir services where unavailable.
> Python API: fix division by zero in rdir client when no service available

- sqliterepo/election.c
- sqlx/sqlx_service.c
This may fix #792 (I didn't reproduce it with or without this commit).
> sqliterepo: review service shutdown sequence

- oio/event/beanstalk.py
- oio/event/consumer.py
- oio/event/filters/account_update.py
- oio/event/filters/notify.py
- tools/oio-bootstrap.py
> event-agent fixes

- oio/api/object_storage.py
- oio/api/replication.py
- oio/cli/storage/obj.py
> API bug fixes

- oio/rdir/server.py
- oio/rdir/server_db.py
oio-rdir-harass.py showed 8% more requests per second
> rdir: slight optimizations in server

- core/lb.c
- oio/cli/admin/client.py
- oio/cli/admin/volume.py
- oio/cli/clientmanager.py
- oio/cli/shell.py
- oio/common/utils.py
- oio/rdir/client.py
> Prevent crash when polling empty service list (fix #828)

- etc/event-handlers.conf-sample
- oio/event/consumer.py
- oio/event/filters/noop.py
- setup.cfg
- tools/oio-bootstrap.py
Does nothing with the input event. Useful if you just want to drop the events.
> event: new noop event filter

- core/oiocfg.h
- etc/event-handlers.conf-sample
- oio/event/consumer.py
- oio/event/filters/noop.py
- rawx-apache2/src/mod_dav_rawx.c
- rawx-apache2/src/rawx_event.c
- setup.cfg
- tools/oio-bootstrap.py
* noop event handler
* rawx events can be disabled
> Events improvements

- core/http_put.c
- core/proxy.c
> Prevent http_proxy environment variable to be considered, enhance error messages

- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_filters_action_content.c
- meta2v2/meta2_utils.c
- meta2v2/meta2v2_remote.c
- meta2v2/meta2v2_remote.h
- proxy/common.c
- proxy/common.h
- proxy/m2_actions.c
- proxy/metacd_http.c
- proxy/sqlx_actions.c
- tests/unit/test_meta2_backend.c
> Allow the proxy to prefer the MASTER

- oio/event/filters/volume_index.py
Connection errors occurs when the peer (rdir) closes the connection. An exception is immediately raised, and retrying saves a buried event or a more complicated beanstalkd "delayed re-queuing".
> oio-event-agent: Allow a few retries on the RPC to the rdir

- sqliterepo/synchro.c
And do a fresh reconnection in such case.
> sqliterepo: detect zookeeper disconnection loops (fix #873)

- oio/api/io.py
Internally we make usage of `io.BufferedReader` objects, which require a subclass of `io.IOBase` as input, thus the need for a wrapper.
> Python API: wrap source stream into IOBase if necessary

- proxy/m2_actions.c
It prevents the properties of a content to be reused for the container. This doesn't happen yet, because both content-wide and container-wide properties are not provided at the same place. But this is ugly and subject to a change for the sake of uniformity.
> proxy: don't look for properties on container autocreation

- meta0v2/meta0_remote.c
- meta0v2/meta0_remote.h
- oio/cli/admin/directory.py
- oio/directory/meta0.py
- proxy/admin_actions.c
- proxy/transport_http.c
- tools/oio-reset.sh
* Fix buffer overflow in proxy when forcing meta0 data
* Factorize meta0-related functions in proxy
* Add `--check` and `--force` options to `openio directory bootstrap` and set timeout to 30s
> Openio directory bootstrap improvements

- proxy/cs_actions.c
> proxy: Avoid losing the (un)lock commands on simple registrations

- cluster/conscience/conscience_srvtype.c
- cluster/conscience/conscience_srvtype.h
- cluster/module/module.c
> Show expired services in the replies from the conscience 

- oio/api/object_storage.py
- oio/api/replication.py
> Improve the resilience toward network/rawx failures

- oio/blob/rebuilder.py
Amends the format of the log emitted by the `oio-blob-rebuilder` while it progresses.
> oio-blob-rebuilder: Fix the progression message

- tools/oio-bootstrap.py
Let's run tests that take the effect of the indexer into account.
> oio-bootstrap.py: Deploy one oio-blob-indexer per rawx

- gridd/main/message_handler.c
- gridd/main/plugin.c
- gridd/main/plugin.h
- gridd/main/server.c
- gridd/main/server_internals.h
Impacts only the central conscience.
Also removes dirty crap not used anymore since several years.
> gridd: fix the recycling of threads

- bin/oio-blob-registrator
- meta2v2/generic.c
- meta2v2/generic.h
- meta2v2/m2gen.py
- meta2v2/meta2_backend.c
- oio/blob/registrator.py
- oio/container/client.py
- setup.cfg
A new tool to refresh the meta2 information about the chunks found in the RAWX volumes.
> Add the oio-blob-registrator

- tools/oio-meta1-rebuilder.sh
- tools/oio-meta2-rebuilder.sh
Add 2 bash scripts, each dedicated to rebuild meta2/meta1 databases.
> Add meta2 and meta1 databases rebuilding scripts

- oio/directory/meta0.py
- tests/functional/directory/test_meta0.py
Add some tests with variable number of meta1 digits, improve the balancing function.
> Improve directory bootstrapping

- meta0v2/meta0_backend.c
- meta0v2/meta0_server.c
- tools/oio-bootstrap.py
- tools/oio-reset.sh
Helps preventing #833 and drops journal entries that help to understand there is a problem.
> Bound the meta0 init time

- oio/blob/indexer.py
A counter of chunks was misleading because it continuously was increased.
Eventually, 10 lines less to do the same...
> oio-blob-indexer: Factorizes the reporting

- .travis.yml
- CMakeLists.txt
- test-requirements.txt
Run test with C coverage enabled.
> Enable coverage with console output for Travis

- events/oio_events_queue_beanstalkd.c
- events/oio_events_queue_zmq.c
Buffered event handling function was called too often.
> Reduce CPU usage when sending events, warn when reaching max queue size

- conf.json
- rdir/CMakeLists.txt
- rdir/rdir.c
- rdir/routes.c
- rdir/routes.c.rl
- rdir/routes.h
> rdir: Fix the maxfd detection, Serve the /config route

- oio/api/replication.py
Use a copy of a list of connections when a remove maybe needed
> replication: fix error on replicated write chunk

- sqliterepo/election.c
> sqliterepo: Remove the 'ABNORMAL 04/LEFT_SELF'

- oio/container/app.py
- tests/functional/container/test_container_streaming.py
When a dump operation is launched, the Manifest is stored as first file of the archive.
Please note that restoration by range must be a multiple of 1 MB, as empty block may be inserted to avoid header split.
When untaring a dump on Linux filesystem, you should provide option --ignore-zeroes to avoid 'A lone zero block at %d' error.
> support restoration of container by range

- tests/functional/container/test_container_streaming.py
Add test for restoration with multi part
Add test to detect replay of multi part
Add test to detect try to initiate restore with invalid part
> tests/functional: more tests for restore

- oio/container/backup.py
Redis connection error was not tested: when this issue was encountered,
a python backtrace was emitted in syslog with a 500 generic error code.
With this patch, service will now return a HTTP 503 error and emit
an appropriate error log.
> oio/container: Test for Redis connection error

- etc/bootstrap-meta1-1digits.yml
- server/network_server.c
- server/slab.c
- server/slab.h
- server/transport_gridd.c
- server/transport_gridd.h
- tools/oio-travis-tests.sh
* manage several `meta1_digits` configurations
* remove dead code
* turn useless paranoid checks into assertions
> Increase the coverage

- core/CMakeLists.txt
- core/tool_sdk_noconf.c
- tools/oio-travis-tests.sh
Illustrates a possible workaround for #1040
> Add a sample code for config less SDK usages

- oio/cli/admin/client.py
- oio/cli/admin/cluster.py
- oio/cli/admin/directory.py
- oio/cli/admin/events.py
- oio/cli/admin/volume.py
- oio/cli/clientmanager.py
- oio/cli/commandmanager.py
- oio/cli/directory/client.py
- oio/cli/directory/reference.py
- oio/cli/shell.py
- oio/cli/storage/account.py
- oio/cli/storage/client.py
- oio/cli/storage/container.py
- oio/cli/storage/obj.py
- oio/cli/utils.py
- oio/container/backup.py
- tests/functional/container/test_container_backup.py
- tests/functional/crawler/test_storage_tierer.py
- tests/functional/event/filters/test_filters.py
Improve the loading of the CLI to load useful imports.
> CLI: Load useful imports

- core/dir.c
- core/tool_roundtrip.c
- core/url.c
> Fix memory leaks

- oio/container/backup.py
Fix issue when reading too much of data instead of real range
Fix issue with uwsgi and LimitedStream not working as expected
> 4.0.x backup fix invalid range

- rdir/rdir.c
> Rdir: Fix error in conditional statement

- oio/api/base.py
- oio/cli/storage/obj.py
- oio/common/http.py
- oio/conscience/agent.py
- Add missing documentation
- Move `get_pool_manager` into `http.py`
> HttpApi : Add documentation and move code

- oio/container/backup.py
- tests/functional/container/test_container_backup.py
Will closes #1090 
Also add parameter to control Redis timeout (default is still 24 hours)
> Backup: accept HEAD requests on /container/restore route

- meta2v2/meta2_filters_action_content.c
- meta2v2/meta2_gridd_dispatcher.c
- server/gridd_dispatcher_filters.h
- server/network_server.c
- server/transport_gridd.c
- sqliterepo/replication_dispatcher.c
- sqliterepo/repository.c
- sqliterepo/sqlite_utils.c
- sqliterepo/sqlite_utils.h
- sqliterepo/sqliterepo.h
- sqlx/sqlx_service.c
- tests/unit/CMakeLists.txt
- tests/unit/test_asn1_message.c
* sqliterepo: Require a sequence number
* meta2: Fix the DRAIN operation
* metautils: slight code simplification
* server: slight code simplification
> container sharding: step4, prepare sqlite to receive sequence numbers

- oio/api/io.py
- tests/functional/cli/storage/test_obj.py
Extract a nested function, log timeout errors.
> Python API: improve rawx timeout handling code

- oio/common/daemon.py
- oio/conscience/agent.py
- oio/conscience/client.py
- oio/conscience/stats/meta.py
Backport #1208 in 4.1.x
Helps with #1223
> Speed the exit process of the conscience-agent

- oio/common/client.py
> oio: Consider the --oio-proxyd-url option to the CLI

- sqliterepo/election.c
(cherry picked from commit fef82ca11af2f74fd7edcb88430f628df5e93336)
> sqliterepo: fix crash when unpausing process

- oio/conscience/checker/http.py
- oio/conscience/stats/http.py
- oio/event/filters/content_cleaner.py
Replace `httplib` with `urllib3` for :
- `HttpChecker`
- `HttpStat`
- `ContentReaperFilter`
See #1087
> Replace 'httplib' with 'urllib3'

- metautils/lib/gridd_client.c
Avoid variables with large scopes, and react to errors as close as possible to the function that raise them.
> Fix the gridd_client logic around net errors

- resolver/hc_resolver.c
Let the caller know it should retry because no resolution was possible because of network errors.:
> Let the resolver return 503 (Retry) upon net errors

- core/oiocfg.h
- core/proxy.c
- oio/api/base.py
- oio/api/ec.py
- oio/api/object_storage.py
- oio/api/replication.py
- oio/blob/client.py
- oio/check_service/check_rawx.py
- oio/cli/account/account.py
- oio/cli/cluster/client.py
- oio/cli/common/clientmanager.py
- oio/cli/common/shell.py
- oio/cli/directory/client.py
- oio/cli/events/client.py
- oio/cli/object/client.py
- oio/cli/object/object.py
- oio/cli/volume/client.py
- oio/common/constants.py
- oio/common/decorators.py
- oio/common/http.py
- oio/common/utils.py
- proxy/common.c
- proxy/common.h
- proxy/m2_actions.c
- tests/functional/api/test_objectstorage.py
- tests/functional/api/test_perfdata.py
- tests/unit/api/test_ec.py
> Keep track of request durations

- cluster/module/server.c
- oio/common/http.py
- oio/common/wsgi.py
- oio/conscience/agent.py
- oio/conscience/checker/http.py
- oio/conscience/checker/tcp.py
- oio/conscience/stats/http.py
- oio/conscience/stats/meta.py
- oio/event/beanstalk.py
- rawx-apache2/src/mod_dav_rawx.c
- rdir/rdir.c
- tests/unit/common/test_http.py
- tools/oio-bootstrap.py
To test with `oio-reset.sh`:
```shell
$ beanstalkd -l ::1 &
$ export ZK=::1:2181
$ oio-reset.sh -f oio-sds/etc/bootstrap-preset-smallrepli.yml -I ::1
```
> Add support for IPv6

- oio/container/backup.py
- oio/container/md5py.py
- tests/functional/container/test_container_backup.py
- tox.ini
Backup now save chunks checksums in manifest.
Restore ensure that each part match checksums.
> Backup/Restore: manage checksums

- oio/conscience/checker/asn1.py
- oio/conscience/checker/tcp.py
- setup.cfg
- tools/oio-bootstrap.py
To be used with meta0, meta1, meta2 and sqlx.
> New "asn1" service checker for conscience-agent

- core/CMakeLists.txt
- core/http_del.c
- core/http_del.h
- core/sds.c
- core/tool_sdk.c
Multiplexed libcurl calls though the curl_multi API.
> C API: Implement the rollback of uploaded chunks

- meta1v2/meta1_backend_references.c
- oio/event/consumer.py
- oio/event/filters/account_update.py
- tests/functional/api/test_directory.py
- tools/oio-bootstrap.py
> Send event when a reference is created

- meta2v2/meta2_filters_action_content.c
- do not send chunks in "storage.content.new" events
- add "part" and "parts" entries in "storage.content.deleted" events,
representing respectively the id of the current part and the total
number of parts of the event.
> Improve meta2 content events

- core/oiostr.h
- core/str.c
- meta2v2/meta2_backend.c
- proxy/m2_actions.c
- tests/functional/container/test_container.py
> Disallow using an unknown storage policy

- .travis.yml
The commit also reorders the `apt-get install` commands: one for custom packages, one for official packages.
> CI: Use up-to-date repositories with Travis

- oio/blob/client.py
There was no cherry on top of the cake.
Now there is one.
Can you feel it?
Yeah, I guess you feel it!
> oio-crawler-integrity: Inhibit xattr checks when asked

- README.md
- TESTING.md
- oio/cli/admin/cluster.py
- tests/functional/cli/admin/test_cluster.py
> 4.1.x cluster wait

- .travis.yml
- tools/CMakeLists.txt
- tools/oio-gdb.py
- tools/oio-travis-tests.sh
If tests aborts, script `oio-gdb.py` will be launched to dump any coredump found.
Gdb will be used with `thread apply all bt` command.
> 4.1.x dump coredump

- metautils/lib/gridd_client.c
- proxy/common.c
An assertion was raised, due to a lack of a prior error check...
> Make the proxy resistant to invalid peers addr

- core/lb.c
- oio/rdir/client.py
- tests/functional/api/test_directory.py
- tests/utils.py
> Allow assignation of an rdir service to a locked rawx service

- tools/oio-travis-tests.sh
Invalid URL was used just after `oio-reset.sh`
> tools: fix invalid URL used by Travis script

- core/sds.c
- meta0v2/zk_manager.c
- sqliterepo/election.c
* Add timestamps in debug logs (milliseconds since Unix epoch).
* Add missing call to `member_unref()`.
> Various improvements in sqliterepo elections

- .travis.yml
- Variables.md
- Variables.md.inc
- tests/func/test_variables.py
- tools/oio-travis-tests.sh
- tox.ini
- Add rawx configurations items in Variables.md.inc
- Add test to ensure that Variables.md is up-to-date
> 4.1.x rawx doc

- core/internals.h
- meta2v2/meta2_backend.c
- meta2v2/meta2_filters_check.c
- meta2v2/meta2_filters_extract.c
- meta2v2/meta2_gridd_dispatcher.c
- meta2v2/meta2_utils.c
- meta2v2/meta2_utils.h
- oio/api/base.py
- oio/common/exceptions.py
- oio/content/factory.py
- proxy/common.h
- proxy/metacd_http.c
- proxy/reply.c
- tests/functional/m2_filters/test_filters.py
WORM mode used to prevent DELETE operations. Now it also prevents PUT operations that could overwrite existing objects.
> Improve WORM mode

- meta1v2/meta1_server.c
Instead, defer this to the next iteration of the task, we force it to execute within the current second, in a BG thread.
> meta1: Avoid contacting M0 upon a reload of the cache

- oio/rdir/client.py
* More error cases managed
* More informational logs for ignored errors
> Fix the asssignation of RDIR services

- oio/api/object_storage.py
- oio/cli/storage/container.py
- setup.cfg
- tests/functional/content/test_content_versioning.py
Purge exceeding object versions
> Python API, CLI: Purge container

- .travis.yml
- tests/functional/cli/admin/test_cluster.py
- tests/functional/container/test_container_backup.py
- tests/utils.py
- tox.ini
> tests/functional: Skip 3 test cases on public CI

- sqliterepo/cache.c
- sqlx/sqlx_service.c
Re-apply the configuration to the existing structures.
> meta*: Fix the max number of bases

- oio/cli/admin/directory.py
- oio/directory/meta0.py
- setup.cfg
Ask the Meta1 services to prepare the elections about all the prefixes DB.
> openio: Implement 'directory warmup'

- oio/event/filters/volume_index.py
These failures will be recovered during the next pass of the `oio-blob-indexer` on that volume.
But we want to avoid retrying delayed events for these failures.
> oio-event-agent: Do not retry failed push/delete to a rdir

- oio/account/server.py
Ugly as hell, but we need that quickly.
> oio-account-server: Minimal access log for read-only requests

- oio/api/ec.py
- oio/api/io.py
- oio/api/replication.py
- oio/common/exceptions.py
- oio/common/green.py
- tests/unit/api/test_ec.py
- tests/unit/api/test_io.py
Improve exception messages.
Never return 'green' timeouts to client applications.
> Python API: improve exception handling

- oio/common/wsgi.py
Rebases #1419 on top of branch 4.1.x.
Closes #1419 
Enhancement
Any WSGI-based service
```
openio 4.1.21.dev3
```
> Rebase and merge #1419

- oio/api/object_storage.py
- oio/blob/auditor.py
- oio/cli/storage/container.py
- oio/cli/storage/obj.py
- oio/container/backup.py
- oio/container/client.py
- oio/crawler/integrity.py
- proxy/m2_actions.c
Fix a bug preventing the decoding of the request when there are too many object properties.
Fixes #1369
Bugfix Pull Request
- Python API
- proxy
```
openio 4.1.21.dev9
```
> Python API: fix property listing

- oio/api/base.py
- oio/blob/client.py
- oio/cli/storage/obj.py
- oio/common/exceptions.py
- oio/common/http.py
- oio/common/utils.py
Fix behavior of `openio object locate --chunk-info` when it's not possible to connect to some rawx services. Also ensure there is a request ID.
CLI
```
openio 4.1.22.dev21
```
> CLI: fix object locate

- oio/content/content.py
- oio/content/factory.py
- oio/rdir/client.py
- oio/rebuilder/blob_rebuilder.py
- oio/rebuilder/meta1_rebuilder.py
- oio/rebuilder/meta2_rebuilder.py
- oio/rebuilder/rebuilder.py
- rebuilder: Add more logs.
- Retry to fetch chunks in the event of network error.
Rebuilder
```
openio 4.1.22.dev29
```
> rebuilder: Add more logs

- oio/blob/indexer.py
Fix the value of the rate.
- `oio-blob-indexer`
```
openio 4.1.22.dev39
```
> oio-blob-indexer: Fix the value of the rate

- meta2v2/meta2_backend.c
- proxy/m2_actions.c
Rollback if the destruction of the container failed so as not to lose the location of the container.
- proxy
```
openio 4.1.22.dev38
```
> Rollback if the destruction of the container failed

- bin/oio-check-directory
- bin/oio-check-master
- oio/zk/admin.py
- setup.cfg
- tools/oio-reset.sh
- tools/zk-bootstrap.py
- tools/zk-reset.py
- tox.ini
* Duplicated code moved moved from `tools/zk-{reset,bootstrap}.py` to `oio/zk/admin.py`
* `tools/oio-directory-check.py` initial release
> Introduce oio-check-directory.py, factorize Zookeeper code into oio/zk/admin.py

- core/oiourl.h
- core/url.c
- meta2v2/meta2_backend.c
- meta2v2/meta2_utils.c
- oio/api/object_storage.py
- oio/container/client.py
- tests/functional/api/test_objectstorage.py
- tests/functional/m2_filters/test_filters.py
Pass the content ID from `content/prepare` to `content/create`.
- Python API
```
openio 4.1.22.dev31
```
> Send the content ID to create an object

- sqliterepo/replication_dispatcher.c
When the ./tmp sub-directory of a sqliterepo basedir has been removed after the startup of the service, the service is now able to recreate it.
`enhancement`
`sqliterepo`
`openio 4.2.0.0b3.dev41`
> sqliterepo: Lazily create $repo/tmp when missing

- .travis.yml
- bin/oio-blob-rebuilder
- bin/oio-meta1-rebuilder
- bin/oio-meta2-rebuilder
- oio/crawler/integrity.py
- oio/rebuilder/blob_rebuilder.py
- oio/rebuilder/rebuilder.py
- tools/oio-test-rebuilder.sh
- tools/oio-travis-tests.sh
Test all rebuilders
- Tests Pull Request
```
openio 4.1.23.dev50
```
> Test oio-{blob,meta1,meta2}-rebuilder

- sqliterepo/replication_dispatcher.c
No need to burden the treatment of replication-related requests with useless calls. Initially imagined to speed-up the starting of elections, they are just useful to take the lock more often.
`enhancement`
`sqliterepo`
`openio 4.2.0.0b3.dev42`
> sqliterepo/dispatcher: Remove useless calls

- etc/bootstrap-option-chunksize-512MiB.yml
- etc/bootstrap-preset-17COPIES.yml
- etc/bootstrap-preset-3COPIES-11RAWX.yml
- etc/bootstrap-preset-3COPIES-3RAWX.yml
- etc/bootstrap-preset-BACKBLAZE.yml
- etc/bootstrap-preset-EC.yml
- etc/bootstrap-preset-MINIMAL.yml
- etc/bootstrap-preset-SINGLE.yml
- etc/bootstrap-preset-fullrepli.yml
- etc/bootstrap-preset-smallrepli.yml
- oio/api/ec.py
- oio/ecd/app.py
- tools/oio-travis-tests.sh
> Permit ECD to work with stream

- oio/directory/admin.py
- oio/rebuilder/meta_rebuilder.py
- proxy/actions.h
- proxy/metacd_http.c
- proxy/sqlx_actions.c
- sqliterepo/replication_dispatcher.c
- sqliterepo/repository.c
- sqliterepo/sqliterepo.h
- sqliterepo/sqlx_remote.c
- sqliterepo/sqlx_remote.h
- tests/functional/directory/test_admin.py
Trigger database replication only for missing bases  for the `oio-meta1-rebuilder` and `oio-meta2-rebuilder`.
- `proxy`
```
openio 4.2.0.0b3.dev61
```
> rebuilder: Trigger database replication only for missing bases

- cluster/module/server.c
Write periodically services status on file.
This file is read when conscience restart for update services.
- Conscience
```
openio 4.1.22.dev70
```
> Persist conscience services status

- sqliterepo/election.c
Fix the detection of Rogue Nodes in the FSM of the elections in sqliterepo.
Prior to the patch, a rogue node caused the election member to never reach the MASTER state, without removing the rogue node.
`bugfix`
`sqliterepo`
`openio 4.1.25.dev9`
> sqliterepo/election: Fix the detection of Rogue nodes

- .travis.yml
- bin/oio-meta2-mover
- oio/directory/admin.py
- oio/directory/meta.py
- proxy/actions.h
- proxy/common.c
- proxy/metacd_http.c
- proxy/sqlx_actions.c
- sqliterepo/replication_dispatcher.c
- sqliterepo/sqlx_macros.h
- sqliterepo/sqlx_remote.c
- sqliterepo/sqlx_remote.h
- tests/functional/directory/test_admin.py
- tools/oio-test-mover.sh
- tools/oio-travis-tests.sh
Automatize tests of `oio-met2-mover`
- `oio-meta2-mover`
```
openio 4.2.0.0b3.dev50
```
> Test oio-meta2-mover

- bin/oio-event-agent
- etc/event-agent.conf-sample
- oio/__init__.py
- oio/common/utils.py
- oio/event/consumer.py
- Update sample configuration file.
- Print a link to the configuration sample when no argument is passed.
- Print a warning when a deprecated option is used.
- oio-event-agent
```
openio 4.1.27.dev7
```
> event: review event-agent configuration options

- oio/rebuilder/meta_rebuilder.py
- sqliterepo/repository.c
- tools/oio-test-rebuilder.sh
Improve the tests for all rebuilders:
- Remove 1 `meta1`, 1 `meta2` and 1 `rawx`
- Restart the services
- Rebuild the `meta1`, the `meta2` and the `rawx`
- `meta2`
```
openio 4.2.0.0b4.dev38
```
> Improve the tests for all rebuilders

- core/lb.c
- tests/unit/CMakeLists.txt
- tests/unit/test_lb.c
Improve load-balancer tests and warning messages.
Core
```
openio 4.1.27.dev9
```
> Improve load-balancer tests and warning messages

- events/oio_events_queue.c
- events/oio_events_queue.h
- events/oio_events_queue_fanout.c
- oio/blob/auditor.py
- rawx-apache2/src/rawx_event.c
- tests/functional/audit/test_audit_storage.py
- tests/functional/blob/__init__.py
- tests/functional/blob/test_auditor.py
- tests/functional/blob/test_blob.py
- tests/functional/blob/test_indexer.py
- tests/functional/blob/test_mover.py
- tests/functional/blob/test_rebuilder.py
- tools/event-benchmark/event_worker.c
- test `oio-blob-indexer` and `oio-blob-auditor`
- `oio-blob-auditor`: compare metachunk size and hash between `meta2` and `rawx`
- `rawx`: fix the sender of events with multiple beanstalk
- `oio-blob-auditor`
- `rawx`
```
openio 4.2.1.dev18
```
> Test oio-blob-{indexer,auditor}

- meta2v2/meta2_filters_action_content.c
Fetch the alias to send an event with the correct URL
- `meta2`
```
openio 4.2.1.dev24
```
> Send an event with the correct URL

- tests/functional/container/test_container.py
Lower score threshold for tests, and avoid infinite wait loop.
Tests
```
openio 4.2.1.dev27
```
> tests: lower score threshold

- oio/api/object_storage.py
- oio/cli/container/container.py
- tests/functional/cli/container/test_container.py
Fix OB-145
Add option to flush container quickly
CLI
```
openio 4.2.1.dev24
```
>  CLI: Add --quickly option to container flush

- oio/cli/container/container.py
- tests/functional/cli/container/test_container.py
Fix flake8 errors
Python API and tests functionnal
```
4.2.x
```
> Fix flake8 warnings

- oio/cli/object/object.py
- setup.cfg
- tests/functional/cli/object/test_object.py
Fix OB-147
Allow copying an object quickly
CLI
```
openio 4.2.1.dev24
```
>  CLI: implement 'object link' subcommand

- core/oio_sds.h
Update ABI
Some functions was renamed and ABI version was not updated.
- core
- 4.2.x
> Update ABI version

- rawx-apache2/src/rawx_repository.c
Specify the mandatory headers
- `rawx`
```
openio 4.2.2.dev8
```
> rawx: Specify the mandatory headers

- bin/oio-blob-converter
- etc/blob-indexer.conf-sample
- oio/blob/auditor.py
- oio/blob/converter.py
- oio/blob/indexer.py
- oio/blob/mover.py
- oio/blob/utils.py
- oio/common/easy_value.py
- oio/common/fullpath.py
- oio/common/xattr.py
- oio/content/content.py
- oio/content/factory.py
- setup.cfg
- tests/functional/blob/__init__.py
- tests/functional/blob/test_auditor.py
- tests/functional/blob/test_blob.py
- tests/functional/blob/test_converter.py
- tests/functional/blob/test_indexer.py
- tests/functional/blob/test_mover.py
- tests/functional/blob/test_rebuilder.py
- Create new tool `oio-blob-converter` to convert old xattr to new xattr
- Integrate the converter in the `oio-blob-indexer`
- `oio-blob-converter`
- `oio-blob-indexer`
```
openio 4.2.2.dev18
```
> Convert old xattr to new xattr

- .indent.pro
- CONTRIBUTING.md
Define the coding style for C and Python. Should help newcomers and trainees.
- Whole project
```
openio 4.2.2.dev36
```
Do not blindly apply `indent` on all C source files, it will modify more than expected.
> Define the coding style for C and Python.

- tools/oio-rebalance-rawx.py
Add script used to rebalance rawx
```
openio 4.2.2.dev8
```
> Rebalance rawx

- metautils/lib/volume_lock.c
- metautils/lib/volume_lock.h
- rawx-apache2/src/mod_dav_rawx.c
- rdir/rdir.c
- sqlx/sqlx_service.c
- sqlx/sqlx_service.h
Fixes OB-176
```
openio-4.2.2
```
> Implement "servicing" mode for directory services

- oio/conscience/checker/http.py
Indicate the URL in the log.
- Log Pull Request
- `conscience`
```
openio 4.2.2.dev46
```
> conscience-agent: log URL of broken HTTP services

- oio/api/ec.py
- oio/api/io.py
- oio/api/replication.py
Reduce log message for socket error.
- Log Pull Request
- Python API
```
openio 4.2.2.dev46
```
> Python API: reduce verbosity of socket errors

- Variables.md
- conf.json
- meta2v2/meta2_backend.c
- sqliterepo/cache.c
- sqliterepo/election.c
- sqliterepo/replication.c
- sqliterepo/replication_dispatcher.c
- sqliterepo/synchro.c
Improve various error messages, to ease debugging.
Fix global configuration documentation.
- Documentation Pull Request
- sqliterepo
```
openio 4.2.2.dev47
```
> Improve some error messages, fix configuration documentation

- oio/common/http_urllib3.py
- oio/conscience/checker/http.py
- oio/conscience/stats/http.py
Close connections to avoid keepalive issues.
When conscience-agent's `check_interval` is set to the same value as rawx' `KeepAliveTimeout` (5s by default), we can see a lot of errors like the following.
```
Sep 10 10:45:31.456685 linux-cgzg OIO,NS,conscience-agent,1[13679]: 13679 7FA97BF9F050 log WARNING ERROR performing http check (127.0.0.1:6031//info): ('Connection aborted.', BadStatusLine("''",))
Sep 10 10:45:31.456777 linux-cgzg OIO,NS,conscience-agent,1[13679]: 13679 7FA97BF9F050 log WARNING rawx|http|127.0.0.1|6031|/info check failed
```
This is due to a bad detection of remotely timed out connections. Now we explicitely close the connections.
Jira: OS-131
- conscience-agent
```
openio 4.2.2.dev66
```
> conscience-agent: close connection to avoid keepalive issues

- CMakeLists.txt
- metautils/lib/volume_lock.c
- oio/api/ec.py
- oio/api/io.py
- rawx-lib/src/attr_handler.c
Close chunk upload connections. There was still a case where chunk upload connections were not explicitly closed.
- Python API
```
openio 4.1.27.dev17
```
> Close chunk upload connections

- .travis.yml
- rawx/beanstalk.go
- rawx/main.go
- rawx/notifier.go
- Implement beanstalkd client
- Remove the dependency to kr/beanstalk
- `rawx`
```
openio 4.2.2.dev135
```
> rawx: Implement beanstalkd client

- rawx/handler_chunk.go
- tests/functional/blob/test_indexer.py
Send event when deleting chunk
- `rawx`
```
openio 4.2.2.dev144
```
> Notify the deleted chunks 

- .travis.yml
- bin/oio-blob-rebuilder
- oio/rebuilder/blob_rebuilder.py
- oio/rebuilder/meta1_rebuilder.py
- oio/rebuilder/meta2_rebuilder.py
- oio/rebuilder/meta_rebuilder.py
- oio/rebuilder/rebuilder.py
- tests/functional/event/filters/test_filters.py
- tools/oio-test-rebuilder.sh
- tools/oio-travis-tests.sh
- Improve log messages of all rebuilders to better track progress
- `oio-blob-rebuilder`: Distribute broken chunks to several beanstalk
```
openio 4.2.2.dev145
```
> Distribute the broken chunks

- meta2v2/meta2_filters_action_content.c
- Select the alias correctly to load the URL with this alias
- Fix the number of parts
- `meta2`
```
openio 4.2.2.dev79
```
> event: Select the alias correctly

- oio/rebuilder/blob_rebuilder.py
Give progress of rebuilt chunks when rebuilding a volume
```
25661 7FCEB9EC7EB0 log INFO START volume=127.0.0.1:6025 last_report=2018-09-27T12:17:46 0.00s chunks=0 0.00/s bytes=0 0.00B/s errors=0 0.00% start_time=2018-09-27T12:17:46 0.00s total_chunks=0 0.00/s total_bytes=0 0.00B/s total_errors=0 0.00% progress=0/1490 0.00%
25661 7FCEB90F22D0 log INFO RUN volume=127.0.0.1:6025 last_report=2018-09-27T12:17:46 10.09s chunks=275 27.25/s bytes=184766464 18307632.15B/s errors=0 0.00% start_time=2018-09-27T12:17:46 10.09s total_chunks=275 27.25/s total_bytes=184766464 18307628.26B/s total_errors=0 0.00% progress=275/1490 18.46%
[...]
25661 7FCEB90F20F0 log INFO RUN volume=127.0.0.1:6025 last_report=2018-09-27T12:18:27 10.29s chunks=271 26.34/s bytes=189318144 18402483.44B/s errors=0 0.00% …
```
> oio-blob-rebuilder: display progress percentage

- rawx-apache2/src/rawx_repository.c
Fix invalid RST format
RAWX
```
4.2.2
```
> rawx: Fix invalid RST

- oio/api/object_storage.py
- oio/cli/container/container.py
Improve documentation about container snapshots.
- Python API
- CLI
```
openio 4.2.3.dev13
```
> Python API, CLI: document container snapshots

- rawx/notifier.go
- Send events to the appropriate tube
- `rawx`
```
openio 4.2.3.dev35
```
> rawx: send events to the appropriate tube

- meta2v2/meta2_backend.c
- meta2v2/meta2_filters_action_content.c
- meta2v2/meta2_utils.c
- meta2v2/meta2_utils.h
- tests/functional/audit/test_audit_storage.py
- tests/functional/container/test_container.py
- tests/unit/test_meta2_backend.c
- Create the correct list of missing chunks when creating an object
- `meta2`
```
openio 4.2.3.dev39
```
> Fix broken content events

- all-requirements.txt
- rawx/chunk_info.go
- rawx/handler_chunk.go
- tests/functional/blob/test_blob.py
Reply the chunk hash and size when putting a chunk
- `rawx`
```
openio 4.2.3.dev62
```
>  rawx: Reply the chunk hash and size when putting a chunk

- tools/oio-bootstrap.py
Fix the path for the coverage
- `rawx`
```
openio 4.2.3.dev65
```
> rawx: Fix the path for the coverage

- all-requirements.txt
- core/oiostr.h
- meta2v2/meta2_utils.c
- oio/cli/object/object.py
- proxy/m2_actions.c
- tests/functional/content/test_content_versioning.py
- `meta2`: Purge exceeding aliases except deleted aliases
- `proxy`: List orphan aliases with all keys
- `meta2`
- `proxy`
```
openio 4.2.4.dev4
```
> Purge exceeding aliases except deleted aliases

- oio/rebuilder/blob_rebuilder.py
Use rebuilder ID to identify the rebuilt chunks when using the distributed mode
```
openio 4.2.3.dev64
```
> oio-blob-rebuilder: Use rebuilder ID to identify the rebuilt chunks

- core/lb.c
- core/oiolb.h
- meta2v2/meta2_utils.c
Fix memory leak
meta2
```
master
```
> meta2: fix memory leak

- tests/functional/cli/account/test_account.py
- tests/functional/cli/container/test_container.py
Fix flake8 warnings
- Python API
```
openio 4.2.4.dev9
```
> tests: Fix flake8 warnings

- oio/container/client.py
- proxy/m2_actions.c
- tests/functional/container/test_container.py
Improve consistency of responses
- `proxy`
- Python API
```
openio 4.2.4.dev18
```
Before:
```
>>> from oio import ObjectStorageApi
>>> api = ObjectStorageApi("OPENIO")
>>> api.object_show("myaccount", "toto", "magic")
{'hash': '272913026300E7AE9B5E2D51F138E674', 'ctime': '1540472065', 'deleted': 'False', 'id': 'CD0F431A0D79050022C4C1B2D37C6731', 'length': '111', 'hash_method': 'md5', 'chunk_method': 'plain/nb_copy=1', 'version': '1540472065691611', 'mtime': '1540472065', 'policy': 'SINGLE', 'properties': {}, 'mime_type': 'application/octet-stream', 'name': 'magic'}
>>> api.object_list("myaccount", "toto")
{'prefixes': [], 'objects': [{'hash': '272913026300E7AE9B5E2D51F138E674', 'name': 'magic', 'deleted': False, 'content': 'CD0F431A0D79050022C4C1B2D37C6731', …
```
> proxy: Improve consistency of responses

- etc/event-handlers.conf-sample
`meta2_index` filter disappears and is replaced by `volume_index`.
- event-agent
> Update event-agent configuration sample

- oio/cli/object/object.py
Fix the CLI parameters and documentation that were ambiguous.
- CLI
```
openio 4.3.0.0b1.dev2
```
> CLI: document 'object link' command

- oio/rdir/client.py
- tests/functional/event/test_events_emission.py
- tests/functional/rdir/test_client.py
- tests/functional/rdir/test_server.py
- tests/unit/api/test_rdir.py
Add tests for the meta2 databases indexing on rdir
```
openio 4.2.3.dev61
```
_None_
> Add tests for the meta2 databases indexing on rdir

- oio/container/lifecycle.py
- tests/functional/container/test_lifecycle.py
Check the current object with the versions
- lifecycle
```
openio 4.3.1.dev20
```
> lifecycle: Check the current object with the versions

- meta2v2/meta2_utils_lb.c
Improve meta2 spare chunk requests (used by oio-blob-rebuilder).
- Improve error messages.
- ...
- meta2
- oio-blob-rebuilder
```
openio 4.3.1.dev43
```
> Improve spare chunk requests

- tools/oio-bootstrap.py
- tools/oio-test-rebuilder.sh
Add `oio-meta2-indexer` to the bootstrap process.
`oio-bootstrap.py`
```
openio 4.3.1.dev52
```
Generate `oio-meta2-indexer` configuration and the corresponding gridinit service configuration for the current deployment.
```
Nil.
```
> Add oio-meta2-indexer to the bootstrap process

- sqliterepo/replication.c
Improve error messages when quorum is not reached
- `sqliterepo`
```
openio 4.2.5.dev11
```
> Improve error messages when quorum is not reached

- oio/blob/client.py
- rawx/handler_chunk.go
Send 200 on rawx HEAD request
- `rawx`
- Python API
```
openio 4.3.1.dev
```
> Send 200 on rawx HEAD request

- .travis.yml
- etc/bootstrap-option-go-rawx.yml
- rawx-apache2/src/rawx_repo_core.c
- tests/functional/blob/__init__.py
- tests/functional/blob/test_auditor.py
- tests/functional/blob/test_blob.py
- tests/functional/blob/test_converter.py
- tests/functional/blob/test_indexer.py
- tests/functional/blob/test_mover.py
- tests/utils.py
- tools/oio-bootstrap.py
- tools/oio-travis-tests.sh
Test both Apache and Go implementation
- `rawx`
```
openio 4.3.1.dev
```
> rawx: Test both Apache and Go implementations

- oio/directory/meta0.py
- Do not try to balance meta1 services when most of them are zero-scored. This will make `openio directory bootstrap` more reliable.
- Get rid of redundant tests about the presence of a logger.
- Python API
```
openio 4.2.6.dev18
```
> Python API: do not try to balance meta1 services when zero-scored

- etc/event-handlers.conf-sample
- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_filters_action_content.c
- meta2v2/meta2_gridd_dispatcher.c
- meta2v2/meta2_utils.c
- meta2v2/meta2_utils.h
- meta2v2/meta2_utils_json_out.c
- oio/container/client.py
- proxy/m2_actions.c
- tests/unit/test_meta2_backend.c
- tools/oio-bootstrap.py
See https://github.com/open-io/oio-sds/pull/1561
- `meta2`
```
openio 4.2.6.dev14
```
> Include object metadata in events for indexing

- meta2v2/meta2_backend.c
Notify properties when creating a container
- `meta2`
```
openio 4.2.6.dev11
```
> Notify properties when creating a container

- core/ext.c
- core/oiocfg.h
- core/oioext.h
- events/oio_events_queue.c
- meta2v2/meta2_filters.h
- meta2v2/meta2_filters_extract.c
- meta2v2/meta2_gridd_dispatcher.c
- metautils/lib/comm_message.c
- metautils/lib/metautils_macros.h
- proxy/metacd_http.c
Add User-Agent in the events
- `proxy`
- `meta2`
```
openio 4.2.6.dev11
```
> Add User-Agent to the events

- oio/common/storage_method.py
- oio/crawler/integrity.py
Detect the irreparable objects and add a note about that in the tool's output.
- `oio-crawler-integrity`
```
openio 4.2.7.dev1
```
> Detect irreparable objects

- etc/blob-indexer.conf-sample
Update the sample of oio-blob-indexer configuration
- `oio-blob-indexer`
```
openio 4.2.7.dev19
```
> Update the sample of oio-blob-indexer configuration

- .travis.yml
- CMakeLists.txt
travis: Update the distribution to Ubuntu Xenial
- Update Pull Request
- Travis
```
openio 4.2.8.dev2
```
>  travis: Update the distribution to Ubuntu Xenial

- rawx/conf_reader.go
- tests/functional/directory/test_refmapping.py
- tests/unit/api/test_replication.py
- tools/oio-check-copyright.sh
In addition to the presence of a copyright header, check that files that have just been modified have the current year in it.
- CI
```
openio 4.3.2.dev4
```
> CI: improve copyright check script

- .travis.yml
Let's parallelize the CI a bit more, when on Travis.
`enhancement`
`ci`
`openio 4.3.2.dev34`
> CI: Split a long job

- Variables.md
- conf.json
This reverts commit fc0229b7ea3f2910ffb6080626909761821f1601.
```
```
```
```
> Revert "core: Set default minimum chunk_size to 0 (check disabled)"

- meta2v2/meta2_utils.c
Fix a memory leak
meta2
```
pre-4.4.0
```
> meta2: fix memleak

- tests/functional/container/test_replication.py
- tests/utils.py
Disable replication test on Travis
tests
```
master
```
> tests: disable meta2 repli test

- test-requirements.txt
- tests/functional/container/test_container.py
- tests/functional/container/test_replication.py
- tools/oio-reset.sh
- tox.ini
Use nosetests' "flaky" module to rerun flaky tests.
- tests
```
openio 4.3.2.dev54
```
> Workaround and fix flaky tests

- resolver/CMakeLists.txt
Fix an error introduced at 76c8e17e9e390b7aa1f5704443d5bf341b9621cb
`fix`
`packaging`
`openio 4.4.0.0b1.dev28`
> resolver: Fix the library name

- oio/account/backend.py
- oio/account/client.py
- oio/account/server.py
- oio/api/object_storage.py
- tests/functional/api/test_objectstorage.py
- tests/unit/api/test_objectstorage.py
Add a parameter to the container listing to get only buckets
* CLI
* Python API
```
openio 4.4.0.0b1.dev15
```
> Permit to only list buckets

- oio/cli/__init__.py
- oio/cli/admin/__init__.py
- oio/cli/common/clientmanager.py
- oio/cli/common/shell.py
- oio/cli/election/client.py
- oio/cli/election/election.py
- oio/cli/rdir/client.py
- oio/cli/rdir/rdir.py
- oio/common/client.py
- oio/common/configuration.py
- oio/rdir/client.py
- setup.cfg
Start implementing the new `openio-admin` command line tool.
Only `election` commands have been implemented at the moment.
Jira: OB-339
- CLI
- Python API
```
openio 4.4.0.0b1.dev25
```
> Start implementing the new 'openio-admin' command line tool

- sqliterepo/replication.c
Detect corrupted databases at the end of the transaction.
- `sqliterepo`
```
openio 4.4.0.0b2.dev13
```
> Detect corrupt databases at the end of transactions

- core/oiourl.h
- oio/event/filters/volume_index.py
- rawx-apache2/src/rawx_repo_core.c
- rawx-apache2/src/rawx_repo_core.h
- rawx-apache2/src/rawx_repository.c
- rawx-lib/src/attr_handler.c
- rawx-lib/src/rawx.h
- tests/functional/blob/test_indexer.py
Load old xattr when deleting chunk.
- `rawx`
```
openio 4.2.9.dev2
```
> Load old xattr when deleting chunk

- sqliterepo/repository.c
No dump if database is corrupt.
- `meta1`
- `meta2`
```
openio 4.2.9.dev6
```
Before:
```
$ openio election status meta2 toto
+----------------+--------+----------------+
| Id             | Status | Message        |
+----------------+--------+----------------+
| 127.0.0.1:6017 |    200 | OK             |
| 127.0.0.1:6018 |    303 | 127.0.0.1:6017 |
| 127.0.0.1:6019 |    303 | 127.0.0.1:6017 |
+----------------+--------+----------------+
$ sqlite3 /home/USER/.oio/sds/data/OPENIO-meta2-2/8B7/8B78B3245B74710F3ACC1BEF4978E621F5E764E01FFB5621D23C4EECA2B7BB3D.1.meta2 "pragma integrity_check"
*** in database main ***
Page 14: btreeInitPage() returns error code 11
Page 16: btreeInitPage() returns error code 11
Page 15: btreeInitPage() returns error code 11
Page 13: …
```
> No dump if database is corrupt

- rawx/chunk_info.go
- tests/functional/blob/test_blob.py
- tests/functional/blob/test_rebuilder.py
Allow to read old chunk with Go rawx
- Go rawx
```
openio 4.4.0.0b2.dev20
```
> Go rawx: Allow to read old chunks

- tools/oio-reset.sh
Fix openio command
- `oio-reset.sh`
```
openio 4.2.9.dev8
```
> oio-reset.sh: Fix openio command

- oio/conscience/checker/http.py
- rawx/beanstalk.go
- rawx/chunk_info.go
- rawx/chunkrepo.go
- rawx/conf_reader.go
- rawx/configuration.go
- rawx/filerepo.go
- rawx/handler_chunk.go
- rawx/handler_info.go
- rawx/handler_stat.go
- rawx/hexa.go
- rawx/limited_reader.go
- rawx/logger.go
- rawx/main.go
- rawx/main_test.go
- rawx/notifier.go
- rawx/rawx.go
- rawx/repo.go
- tools/oio-rawx-harass.go
The PR gathers miscellaneous fixes and improvements of the golang RAWX.
The main optimisation came from the emission of "post-reply notifications", a real asynchronous behavior thanks to a buffered channel and well sized buffers upon download and upload.
In addition, it does less computations, it tries to use memory on the stack instead of the heap, to ease the job of the Garbage Collector.
`enhancement`
`rawx`
`openio 4.4.2.dev26`
A CLI tool to stress a RAWX service, named `oio-rawx-harass`, has been added in the `tools/` directory.
> Rawx: speedup of the golang version

- meta2v2/meta2_backend.c
- tests/functional/conscience/test_conscience.py
- tests/functional/container/test_replication.py
- tests/unit/test_meta2_backend.c
Fix small memory leaks in meta2 service and related tests.
- meta2
```
openio 4.4.2.dev44
```
> Fix memory leaks in meta2 and meta2 tests

- events/oio_events_queue_beanstalkd.c
Emit a warning before retrying to send an event.
Also review some log messages so it's easier to grep them.
- beanstalkd library
- meta2
```
openio 4.4.2.dev51
```
> m2, events: emit a warning before retrying to send an event

- oio/cli/admin/service_rebuild.py
- oio/rebuilder/rebuilder.py
- setup.cfg
- tools/oio-test-rebuilder.sh
Implement 'openio-admin <service-type> rebuild' commands
- Admin CLI
```
openio 5.0.0.0a1.dev51
```
```
$ openio-admin meta1 rebuild --workers 10
START volume=None last_report=2019-04-17T16:15:15 0.00s prefixes=0 0.00/s errors=0 0.00% start_time=2019-04-17T16:15:15 0.00s total_prefixes=0 0.00/s total_errors=0 0.00%
DONE volume=None last_report=2019-04-17T16:15:15 1.65s prefixes=16 9.72/s errors=0 0.00% start_time=2019-04-17T16:15:15 1.65s total_prefixes=16 9.72/s total_errors=0 0.00%
```
```
$ openio-admin meta2 rebuild --workers 10
START volume=None last_report=2019-04-17T16:15:59 0.00s references=0 0.00/s errors=0 0.00% start_time=2019-04-17T16:15:59 0.00s total_references=0 0.00/s total_errors=0 0.00%
DONE volume=None last_report=2019-04-17T16:15:59 5.90s …
```
> Implement 'openio-admin <service-type> rebuild' commands

- oio/api/object_storage.py
- oio/blob/operator.py
- oio/blob/rebuilder.py
- oio/cli/admin/item_locate.py
- oio/cli/admin/item_repair.py
- oio/cli/container/container.py
- oio/content/repairer.py
- setup.cfg
Implement 'openio-admin object repair' command
- Python API
- Admin CLI
```
openio 5.0.0.0a1.dev51
```
```
$ openio-admin object repair toto magic passwd
START last_report=2019-04-18T15:48:11 0.00s objects=0 0.00/s errors=0 0.00% start_time=2019-04-18T15:48:11 0.00s total_objects=0 0.00/s total_errors=0 0.00% progress=0/2 0.00%
DONE last_report=2019-04-18T15:48:11 0.06s objects=2 31.50/s errors=1 50.00% start_time=2019-04-18T15:48:11 0.06s total_objects=2 31.50/s total_errors=1 50.00% progress=2/2 100.00%
+-----------------------------------+-----------------------------------------+
| Object                            | Status                                  |
+-----------------------------------+-----------------------------------------+
| …
```
> Implement 'openio-admin object repair' command

- oio/event/filters/account_update.py
Drop old event when updating account
```
openio 4.4.3.dev4
```
> Drop old event when updating account

- oio/cli/admin/item_check.py
- oio/cli/admin/service_check.py
- setup.cfg
- Checks all rawx chunks with the same tests used in `openio-admin chunk check`.
- Admin CLI
```
openio 5.0.0.0a1.dev51
```
> CLI: implement 'openio-admin check rawx' command

- rawx/filerepo.go
- rawx/handler_chunk.go
- rawx/repo.go
- tests/functional/blob/test_blob.py
Add some more tests to check chunk hash
- Go rawx
```
openio 5.0.0.0a2.dev38
```
> Add some more tests to check chunk hash

- oio/common/exceptions.py
- oio/content/repairer.py
- rawx-apache2/src/rawx_repo_core.c
- rawx-apache2/src/rawx_repository.c
- tests/functional/blob/test_blob.py
Repair corrupted chunk
- CLI
```
openio 5.0.0.0b1.dev3
```
> CLI: Repair corrupted chunk

- oio/blob/converter.py
- oio/cli/admin/common.py
- oio/crawler/integrity.py
- tests/functional/cli/__init__.py
- tests/functional/cli/admin/test_item_check.py
- tests/functional/cli/admin/test_item_move.py
- tools/oio-test-suites.sh
- Test 'openio-admin account check'
- Test 'openio-admin container check'
- Test 'openio-admin object check'
- Test 'openio-admin chunk check'
- Allow to recover object meta when checking a missing chunk
- Admin CLI
```
openio 5.0.0.0b1.dev13
```
> Test 'openio-admin <item> check'

- tests/functional/api/test_objectstorage.py
Wait for events when testing the account service.
- test
```
openio 4.4.4.dev1
```
> Wait for events when testing the account service

- oio/cli/admin/service_check.py
Do not use the stdout within the commands
- Admin CLI
```
openio 5.0.0.0b1
```
> Do not use the stdout within the commands

- tests/functional/cli/admin/test_item_repair.py
Add tests to container repair
- Tests Pull Request
```
openio 5.0.0.0b1.dev10
```
> Add tests to container repair

- oio/cli/admin/item_locate.py
- tests/functional/cli/admin/test_item_locate.py
Add some tests for `openio-admin <item> locate`.
- CLI
```
openio 5.0.0.0b1.dev2
```
> Add some tests for `openio-admin <item> locate` 

- oio/cli/admin/service_config.py
- oio/directory/admin.py
- proxy/cache_actions.c
- server/transport_gridd.c
- tests/functional/cli/admin/test_item_move.py
- tests/functional/cli/admin/test_service_config.py
- Specify the result for each key when setting config
- Add some tests for `openio-admin <service> {g,s}et-config`
- `proxy`
- `metaX`
- Python API
- Admin CLI
```
openio 5.0.0.0b1.dev15
```
> Add some tests for 'openio-admin <service> {g,s}et-config' 

- oio/cli/admin/service_rebuild.py
- tests/functional/cli/admin/test_service_rebuild.py
- Update the docstrings for 'openio-admin <service> rebuild'
- Add some tests for 'openio-admin account-service rebuild'
- Admin CLI
```
openio 5.0.0.0b1.dev23
```
> Add some tests for 'openio-admin account-service rebuild'

- oio/common/exceptions.py
This problem was already fixed on the `master` branch.
- Python API
```
openio 4.4.4.dev17
```
> Python API: fix exception reraise function

- oio/cli/admin/service_list.py
- tests/functional/cli/admin/test_service_list.py
Test meta2|rawx list containers
- Tests Pull Request
CLI
```
openio 5.0.0.0b1.dev11
```
> CLI: test 'meta2 list containers' and 'rawx list containers'

- core/proxy.c
Use the same retry policy as the Python API:
- Don't retry when requesting the `oio-proxy`
- Don't return 421 (content exists) after retrying `POST`
- C API
```
openio 4.2.9.dev17
```
> C API: Use the same retry policy as the Python API

- sqliterepo/election.c
- sqliterepo/synchro.c
- sqliterepo/synchro.h
- tools/oio-travis-tests.sh
This is a backport of #1782, with improvements.
- sqliterepo
```
openio 4.2.9.dev17
```
> Take precautions to prevent "double master" situations

- metautils/lib/lb.c
- oio/api/ec.py
- server/network_server.c
- tests/functional/api/test_objectstorage.py
- tests/utils.py
- Minor upload speed improvement in Python API.
- Allow several slots in LB benchmark files.
- Increase reliability of some tests.
- Python API
- tests
```
openio 5.0.0.0rc1.dev4
```
> Minor improvements

- .travis.yml
- rawx/beanstalk.go
- rawx/conf_reader.go
- rawx/configuration.go
- rawx/handler_chunk.go
- rawx/handler_info.go
- rawx/handler_stat.go
- rawx/hexa.go
- rawx/logger.go
- rawx/main.go
- rawx/notifier.go
- rawx/rawx.go
- rawx/sample-rawx.conf
Miscellaneous fixes in the golang RAWX, for a better management of the program exit, of client timeouts and incomplete requests (when a body was not expected but sent).
TODO: factorisation, configuration
`bugfix`
`rawx`
`openio 4.5.1.dev2`
> rawx: Fix the program exit and the enforcement of timeouts

- oio/api/base.py
- oio/api/ec.py
- oio/api/object_storage.py
- oio/api/replication.py
- oio/blob/client.py
- tests/functional/api/test_perfdata.py
Fix various annoying or ambiguous logs we have seen when debugging a customer's platform.
- Python API
```
openio 4.5.2.dev1
```
> Fix annoying or ambiguous logs

- oio/zk/client.py
- tools/oio-test-suites.sh
Allow not to have a zookeeper to check meta0
- Admin CLI
```
openio 5.0.0.dev1
```
> Allow not to have a zookeeper to check meta0

- etc/bootstrap-option-replication-events.yml
- tools/oio-bootstrap.py
Allow to deploy event-agent with replication
- `oio-bootstrap`
```
openio 4.5.2.dev9
```
> Allow to configure event-agent for asynchronous object replication

- oio/api/ec.py
- oio/api/io.py
- oio/api/replication.py
- oio/common/http_eventlet.py
Few parts of Python API were using unset logger
Any logging operation in these parts were ignored
Python API
```
openio 4.5.2.dev4
```
> Python API: fix logger initialization

- oio/api/ec.py
Because of a recent modification, some errors were reported twice (or more!), and the Python API attempted to commit the same chunk several times. This was fortunately blocked by the meta2 (`Content broken and irreparable (HTTP 500) (STATUS 425)`), and the whole object upload was considered a failure, even though the chunks quorum was reached. This is now fixed.
- Python API
```
openio 4.5.2
```
> Python API: report EC chunks errors only once

- oio/api/ec.py
- oio/api/io.py
- oio/api/object_storage.py
- oio/api/replication.py
This PR allows to use logger from `object_create` / `object_fetch` in low level API
oio
```
openio 4.5.3
```
> Python API: propagate logger instance

- oio/blob/operator.py
Don't raise an exception when chunk rebuild has worked
- Python API
- Admin CLI
```
openio 5.0.0.dev1
```
Jira: OS-386
> Don't raise an exception when chunk rebuild has worked

- bin/oio-blob-rebuilder
- oio/rebuilder/blob_rebuilder.py
- oio/rebuilder/rebuilder.py
Retry failed rebuild jobs, with a delay.
```
openio 4.6.0.dev1
```
> Retry failed rebuild jobs, with a delay

- core/str.c
- etc/event-handlers.conf-sample
- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_server.c
- oio/event/evob.py
- proxy/m2_actions.c
- proxy/sqlx_actions.c
- sqliterepo/internals.h
- sqliterepo/replication_dispatcher.c
- sqliterepo/repository.c
- sqliterepo/sqlite_utils.c
- sqliterepo/sqlite_utils.h
- sqliterepo/sqliterepo.h
- sqliterepo/sqlx_remote.c
- sqliterepo/sqlx_remote.h
- tests/functional/api/test_objectstorage.py
- tools/oio-bootstrap.py
Create a new event `storage.container.update`. This event is sent when changing container properties.
- `sqliterepo`
- `meta2`
- `proxy`
```
openio 4.5.3.dev10
```
> Send event when changing container properties

- bin/oio-blob-mover
- etc/blob-mover.conf-sample
- oio/blob/mover.py
- oio/content/content.py
Allow to exclude some rawx
- `oio-blob-mover`
```
openio 4.6.1.dev10
```
> blob-mover: Allow to exclude some rawx

- metautils/lib/rrd.h
- oio/common/decorators.py
- oio/directory/meta2.py
- proxy/m2_actions.c
Implement a new decorator allowing to generate prefixed request IDs. Use this decorator in meta2 mover and rebuilder.
Also fix a bunch of typos.
- Python API
```
openio 4.6.1.dev13
```
> Better request IDs

- meta0v2/zk_manager.c
The mentioned tool has been replaced.
bugfix
meta0
`openio 4.6.1.dev40`
> Fix the error message indicating the need for a zk bootstrap

- Variables.md
- conf.json
- meta1v2/compound_types.c
- meta1v2/meta1_backend_services.c
- metautils/lib/comm_message.c
- metautils/lib/comm_meta_reply.c
- metautils/lib/metacomm.h
- oio/cli/cluster/cluster.py
- oio/directory/meta.py
- proxy/common.c
- proxy/metacd_http.c
- proxy/transport_http.c
- proxy/transport_http.h
- rdir/rdir.c
- server/transport_gridd.c
- sqliterepo/election.c
- sqliterepo/replication_dispatcher.c
- sqliterepo/repository.c
- sqlx/sqlx_service.c
- sqlx/sqlx_service.h
The current PR targets decaching order that were issued too often (and for wrong reasons).
enhancement
proxy
`openio 4.6.1.dev27`
> Fixes and improvements to reduce the latency of DB operations

- oio/cli/election/election.py
- oio/directory/admin.py
- proxy/actions.h
- proxy/cache_actions.c
- proxy/metacd_http.c
- setup.cfg
- sqliterepo/election.c
- sqliterepo/election.h
- sqliterepo/replication_dispatcher.c
- sqliterepo/sqlx_macros.h
- sqliterepo/sqlx_remote.c
- sqliterepo/sqlx_remote.h
Provides CLI tools and `oio-proxy` routes to balances master elections among services.
Closes #1306 
Feature
proxy, sqliterepo, cli
`openio 5.0.2.dev34`
> Allow to balance masters among services of the same type.

- core/lb.c
- core/loc.c
- core/oioloc.h
- etc/bootstrap-preset-EC21.yml
- etc/bootstrap-preset-ECX21.yml
- tools/oio-bootstrap.py
Apply a mask to detect well the beginning of the section with the local services, in a LB slot.
The bug possibly led to no local service found, then simply applying the local policy.
bugfix
core, proxy
`openio 5.1.1.dev28`
> Fix the allocation of local rawx in the proxy

- core/lb.c
- meta2v2/meta2_utils_lb.c
- meta2v2/meta2_utils_lb.h
- metautils/lib/comm_message.c
- metautils/lib/comm_meta_reply.c
- proxy/m2_actions.c
- sqliterepo/sqlx_remote_ex.c
- tools/oio-bootstrap.py
* Also allow local placement of SPARE chunks (not managed yet!)
* Fix the binary search logic to work on slices of locations more than exact locations
* Add debug messages in TRACE
enhancement
core
`openio 5.1.1.dev40`
> core: Fix the LB on local services

- rawx-apache2/httpd.conf.sample
- rawx-apache2/src/mod_dav_rawx.c
- rawx-apache2/src/rawx_config.h
- rawx-apache2/src/rawx_repo_core.c
- tools/oio-bootstrap.py
Set the upload buffer size to 8MiB
Improvement
rawx-httpd
`openio 5.0.2.dev45`
> rawx: Set the upload buffer size to 8MiB

- rawx-apache2/src/mod_dav_rawx.c
- rawx-apache2/src/rawx_repo_core.c
Oops.
fix
rawx-http
`openio 5.1.1.dev38`
> rawx-httpd: Remove unwanted traces

- cluster/module/server.c
- core/internals.h
- oio/cli/cluster/cluster.py
- proxy/common.c
- proxy/common.h
- proxy/cs_actions.c
- proxy/lb_actions.c
- proxy/reply.c
- sqliterepo/repository.c
- tests/functional/cli/cluster/test_cluster.py
Wait for services even if the proxy and conscience are not ready yet.
- `proxy`
- CLI
```
openio 4.7.0.0rc1.dev7
```
> Wait for proxy and conscience when waiting for services

- rawx-apache2/src/rawx_repo_core.c
- rawx-apache2/src/rawx_repo_core.h
- rawx-apache2/src/rawx_repository.c
Fail when we can not check the existence of chunk
- `rawx`
```
openio 4.7.0.0rc1.dev9
```
> Fail when we can not check the existence of chunk

- bin/oio-blob-rebuilder
- oio/rdir/client.py
- oio/rebuilder/blob_rebuilder.py
Shuffle chunks after fetching them from rdir
```
openio 4.7.0.0rc1.dev9
```
> blob-rebuilder: Shuffle chunks after fetching them from rdir

- rdir/rdir.c
Fix counters when getting status
Before, the 'mtime' was switched with the 'rtime'.
Now, we have to look at both to find the right value.
- `rdir`
```
openio 4.7.1.dev5
```
```
$ cat status.163.172.5.215\:6203.old.rdir | jq .chunk
{
"total": 81816568,
"to_rebuild": 51255766
}
$ cat status.163.172.5.215\:6203.rdir | jq .chunk
{
"total": 81816568,
"to_rebuild": 81816568
}
$ cat status.62.210.157.223\:6202.old.rdir | jq .chunk
{
"total": 74245135,
"to_rebuild": 43529291
}
$ cat status.62.210.157.223\:6202.rdir | jq .chunk
{
"total": 74245135,
"to_rebuild": 74245135
}
```
> rdir: Fix counters when getting status

- metautils/lib/gridd_client.c
- oio/api/object_storage.py
- oio/common/http_urllib3.py
- oio/common/utils.py
- proxy/m2_actions.c
- tests/functional/api/test_objectstorage.py
Retry listing when service is busy
- `proxy`
- Python API
```
openio 4.7.1.dev6
```
> Retry listing when service is busy

- oio/rebuilder/blob_rebuilder.py
Fetch total chunks to rebuild during rebuilding chunks
```
openio 4.7.1.dev6
```
> oio-blob-rebuilder: do not block while counting the number of chunks to rebuild

- bin/oio-blob-rebuilder
- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_filters_action_container.c
- oio/container/client.py
- oio/content/content.py
- oio/content/ec.py
- oio/content/plain.py
- oio/rebuilder/blob_rebuilder.py
- proxy/m2_actions.c
- proxy/meta2v2_remote.c
- proxy/meta2v2_remote.h
- tests/functional/content/test_plain.py
Allow to rebuild chunk in frozen container
- Bug Pull Request
```
openio 4.7.1.dev7
```
> Allow to rebuild chunk in frozen containers

- bin/oio-blob-registrator
- meta2v2/meta2_utils_json_in.c
- oio/blob/registrator.py
- proxy/meta2v2_remote.c
- Insert alias and content in the containers
- Allow to specify containers
- `oio-blob-registrator`
```
openio 4.7.1.dev8
```
> Improve oio-blob-registrator

- rawx-apache2/httpd.conf.sample
- rawx/handler_chunk.go
- rawx/handler_info.go
- rawx/handler_stat.go
- rawx/logger.go
- tools/oio-bootstrap.py
* Only one format and semantics for any access log entry 
* Display both `bytes_in` and `bytes_out` for an easier integration
* Stop displaying the container id.
enhancement
rawx
``
> rawx: Update the log format

- oio/conscience/checker/asn1.py
- oio/conscience/checker/base.py
- oio/conscience/checker/http.py
- oio/conscience/checker/tcp.py
Improve the log when the check of a service has failed
- `conscience-agent`
```
openio 5.2.0.dev1
```
> Improve the log when the check of a service has failed

- etc/event-handlers.conf-sample
- oio/event/beanstalk.py
- tests/func/test_weird_chars.c
- tests/functional/api/test_objectstorage.py
- tests/unit/test_prefixmapping.py
- tools/oio-test-mover.sh
- tools/oio-test-rebuilder.sh
- tools/oio-travis-tests.sh
- make curl silent when there is no error
- make "test_weird_chars" more reliable
- run oio-reset.sh in quiet mode, produce less logs
- Clean buried events after running tests known for producing a lot
- CI
```
openio 4.7.2.dev10
```
> CI: produce less annoying logs

- oio/ecd/app.py
Allow to read metachunk with missing chunks
- ECD
```
openio 4.7.2.dev7
```
> ECD: Allow to read metachunk with missing chunks

- oio/cli/cluster/cluster.py
- oio/conscience/agent.py
- oio/conscience/client.py
- proxy/cs_actions.c
- proxy/reply.c
- setup.cfg
- tests/functional/conscience/test_conscience.py
- tests/utils.py
Deregister specific services
- `proxy`
- Python API
- CLI
```
openio 4.7.2.dev13
```
```
$ openio cluster list rawx -c Type -c Addr
+------+----------------+
| Type | Addr           |
+------+----------------+
| rawx | 127.0.0.1:6012 |
| rawx | 127.0.0.1:6011 |
| rawx | 127.0.0.1:6010 |
+------+----------------+
$ openio cluster deregister rawx 127.0.0.1:6011
$ openio cluster list rawx -c Type -c Addr
+------+----------------+
| Type | Addr           |
+------+----------------+
| rawx | 127.0.0.1:6012 |
| rawx | 127.0.0.1:6010 |
+------+----------------+
```
> Deregister specific services

- oio/cli/lifecycle/lifecycle.py
Remove useless argument for `openio lifecycle apply --recursive`
- `CLI`
```
openio 4.7.2.dev18
```
> CLI: Remove useless argument

- oio/event/consumer.py
- oio/event/filters/notify.py
- oio/event/handlers/base.py
- tests/functional/event/filters/test_filters.py
Some errors were too verbose, especially the ones triggered when stopping the process. Their verbosity has been lowered.
Also fix a bug in the notifier plugin, which prevented chunk events to be forwarded.
- event-agent
```
openio 4.7.2.dev17
```
> Improve event-agent error handling, fix bug in notifier

- oio/event/beanstalk.py
- oio/rebuilder/blob_improver.py
- oio/rebuilder/blob_rebuilder.py
- oio/rebuilder/meta1_rebuilder.py
- oio/rebuilder/meta2_rebuilder.py
- oio/rebuilder/meta_rebuilder.py
- oio/rebuilder/rebuilder.py
Exit gracefully the rebuilders
- `oio-improver`
```
openio 4.7.2.dev21
```
> Exit gracefully the rebuilders

- core/lb.c
- meta2v2/meta2_filters_action_content.c
- oio/event/beanstalk.py
- tests/functional/content/test_content_perfectible.py
- tools/oio-bootstrap.py
Some tests of perfectible content improvement were systematically skipped (:man_facepalming:), and failed when re-enabled. The tests have been fixed, and will now run in some of the tests environments. And then the tested code has been fixed.
- lb
```
openio 4.7.2.dev29
```
> Fix content perfectible tests

- oio/cli/__init__.py
- oio/cli/account/account.py
- oio/cli/cluster/cluster.py
- oio/cli/container/container.py
- oio/cli/directory/directory.py
- oio/cli/election/election.py
- oio/cli/events/events.py
- oio/cli/lifecycle/lifecycle.py
- oio/cli/object/object.py
- oio/cli/rdir/rdir.py
- oio/cli/reference/reference.py
- oio/cli/volume/volume.py
- tests/functional/cli/__init__.py
- tests/functional/cli/cluster/test_cluster.py
Improve some cluster commands to accept multiple services
- `CLI`
```
openio 4.7.2.dev18
```
> Improve some cluster commands to accept multiple services

- etc/account-server.conf-sample
- oio/account/backend.py
- oio/common/redis_conn.py
- oio/container/backup.py
- tests/functional/account/test_backend.py
Allow to set various Redis parameters
Jira: OB-461
- `account`
```
openio 4.7.2.dev19
```
> Allow to set various Redis parameters

- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_server.c
- proxy/sqlx_actions.c
- sqliterepo/internals.h
- sqliterepo/replication_dispatcher.c
- sqliterepo/repository.c
- sqliterepo/sqliterepo.h
Return 404 when the container created but not initiated
- `meta2`
```
openio 4.7.2.dev23
```
> Return 404 when the container created but not initiated

- core/url.c
- etc/event-handlers.conf-sample
- meta2v2/meta2_backend.c
- meta2v2/meta2_backend.h
- meta2v2/meta2_server.c
- oio/event/evob.py
- oio/event/filters/volume_index.py
- proxy/m2_actions.c
- sqliterepo/repository.c
- sqliterepo/sqliterepo.h
- tests/functional/api/test_objectstorage.py
- tests/functional/content/test_content_perfectible.py
- tests/functional/crawler/test_integrity_crawler.py
- tests/functional/event/test_events_emission.py
- tests/utils.py
- tools/oio-bootstrap.py
Send event for each deleted meta2 database
- 1 `storage.meta2.deleted` for each deleted meta2 database
- 1 `storage.container.deleted` for each deleted container
- `sqliterepo`
- `meta2`
- `proxy`
```
openio 4.7.2.dev28
```
> Send event for each deleted meta2 database

- oio/common/tool.py
- oio/event/beanstalk.py
Exit gracefully the tools
- Admin CLI
```
openio 5.2.2.dev12
```
> Exit gracefully the tools

- meta1v2/meta1_backend.c
- meta1v2/meta1_backend.h
- meta1v2/meta1_server.c
- proxy/common.c
- tests/unit/test_meta1_backend.c
Decache when deleting meta1 database or when the base is not managed.
Jira: OS-437
- `meta1`
- `proxy`
```
openio 4.7.2.dev41
```
> Decache meta1 database

- oio/directory/meta0.py
- proxy/admin_actions.c
- tests/functional/directory/test_prefixmapping.py
Fix prefixes of meta0 list
- `proxy`
- Python API
```
openio 4.7.2.dev42
```
> Fix prefixes of meta0 list

- oio/rebuilder/blob_rebuilder.py
Fix reuse of beanstalkd connections
```
openio 4.7.2.dev41
```
> blob-rebuilder: Fix reuse of beanstalkd connections

- oio/api/object_storage.py
- oio/common/storage_functions.py
- oio/content/ec.py
- oio/content/plain.py
- tests/unit/api/test_objectstorage.py
Allow to read object with duplicated position
- `Python API`
```
openio 4.8.1.dev5
```
> Allow to read object with duplicated position

- oio/api/ec.py
- oio/api/io.py
- oio/api/object_storage.py
Improve error message aggregation on failed EC downloads. Do not display only the latest error message, but all of them.
Jira: OB-214
- Python API
```
openio 4.8.2.dev14
```
> Python API: improve error message aggregation on failed EC download

- oio/ecd/app.py
Close the stream after reading a metachunk
- ECD
```
openio 4.8.2.dev2
```
> ECD: Close the stream after reading a metachunk

- oio/crawler/integrity.py
Fixes an endless listing loop in the integrity crawler.
crawler
> oio/crawler: fix endless listing loop

- oio/cli/admin/service_decommission.py
- oio/cli/admin/xcute.py
- oio/xcute/common/backend.py
- oio/xcute/common/job.py
- oio/xcute/common/manager.py
- oio/xcute/jobs/mover.py
- oio/xcute/jobs/tester.py
- oio/xcute/orchestrator.py
- oio/xcute/server.py
Allow to pause and resume job
- `xcute`
```
openio 5.2.2
```
> xcute: Allow to pause and resume job

- oio/account/backend.py
Use redis slave to read
`account`
```
openio 4.8.2.dev6
```
> Use slave Redis services for read operations

- oio/xcute/common/worker.py
- oio/xcute/jobs/mover.py
Prefix request ID with job ID
- xcute
```
openio 5.2.2
```
> xcute: Prefix request ID with job ID

- oio/cli/admin/service_decommission.py
- oio/cli/admin/service_rebuild.py
- oio/cli/cluster/cluster.py
- oio/cli/container/container.py
- oio/common/easy_value.py
- oio/container/client.py
- oio/directory/indexer.py
- oio/xcute/common/job.py
- oio/xcute/jobs/__init__.py
- oio/xcute/jobs/blob_rebuilder.py
- oio/xcute/jobs/mover.py
- oio/xcute/jobs/tester.py
- oio/xcute/server.py
Implement blob rebuilder
- `xcute`
```
openio 5.2.2
```
> xcute: Implement blob rebuilder

- oio/cli/__init__.py
- oio/cli/admin/service_info.py
- oio/cli/admin/xcute/job.py
- oio/cli/admin/xcute/rawx.py
- oio/xcute/jobs/__init__.py
- oio/xcute/jobs/blob_mover.py
- oio/xcute/jobs/blob_rebuilder.py
Fix marker to list chunks with rdir
- `xcute`
```
openio 5.2.2
```
> xcute: Fix marker to list chunks with rdir

- sqliterepo/synchro.c
Fix compilation warning
- `sqliterepo`
```
openio 5.2.2
```
> Fix compilation warning

- oio/xcute/common/backend.py
Fix redis commands for Redis < 4.0.0
- `xcute`
```
openio 5.2.2
```
> xcute: Fix redis commands for Redis < 4.0.0

- etc/xcute.conf-sample
- tools/oio-bootstrap.py
Add sample configuration
- `xcute`
```
openio 5.2.2
```
> xcute: Add sample configuration

- oio/xcute/common/backend.py
- oio/xcute/orchestrator.py
Check if tasks are already processed
- `xcute`
```
openio 5.2.2
```
> xcute: Check if tasks are already processed

- oio/xcute/common/backend.py
- oio/xcute/server.py
- Convert all redis errors to excetions
- Catch all backend errors in the server
- `xcute`
```
openio 5.2.2
```
> xcute: Improve error messages

- tests/unit/test_sqliterepo_election.c
When running along with ZooKeeper 3.5, some more actions are performed. The tests have been adapted to take these actions into account.
- tests
```
openio 6.0.0.0a2.dev22
```
> Fix sqliterepo election tests with ZooKeeper 3.5

- oio/blob/auditor.py
- oio/common/http.py
- oio/common/xattr.py
- tests/functional/audit/test_audit_storage.py
- tests/functional/blob/__init__.py
- tests/functional/blob/test_blob.py
- tests/functional/blob/test_converter.py
- tests/functional/blob/test_mover.py
- tests/functional/blob/test_rebuilder.py
- tox.ini
Another batch of Python 3 fixes.
- Python API
- tests
```
openio 6.0.0.0a2.dev28
```
> Python API, tests: another batch of Python 3 fixes

- oio/cli/zk/set.py
Some platforms (e.g. openio/sds docker image) are deployed without ZooKeeper. Trying to generate the bash-completion file on such platforms was not possible. The present modification delays to loading of the ZooKeeper Python API dependency, allowing to load the definition of commands without it.
Jira: R1910-35
- CLI
```
openio 6.1.0.0a1.dev3
```
> CLI: lazily load zookeeper dependency

- sqlx/sqlx_service.c
Check directory/file creation without depending on network.
- `sqlx`
```
openio 5.2.4.dev1
```
> Check directory/file creation without depending on network

- etc/xcute.conf-sample
- oio/xcute/orchestrator.py
Improve loadbalancing strategy
- xcute
```
openio 5.2.2
```
> xcute: Improve loadbalancing strategy

- bin/oio-xcute
- oio/xcute/orchestrator.py
Handle backend errors
- `xcute`
```
openio 5.2.4.dev114
```
> xcute: Handle backend errors

- oio/event/consumer.py
- oio/event/evob.py
- oio/event/filters/xcute.py
- oio/xcute/common/worker.py
- oio/xcute/orchestrator.py
Retry later when the worker can't reply
- `xcute`
```
openio 5.2.3.dev1
```
> xcute: Retry later when the worker can't reply

- sqliterepo/replication.c
When replication of dabase fails, errors doesn't contains reqid
meta2
```
4.8.1
```
```
```
> Enhance replication error with reqid

- sqliterepo/election.c
Show SYNC_KO on failed PIPEFROM
- sqliterepo
```
openio 4.8.2.dev11
```
> Show SYNC_KO on failed PIPEFROM

- oio/account/backend.py
- oio/common/redis_conn.py
Implement a new decorator to catch Redis server errors (especially `BusyLoadingError`) and transform them into the more friendly `ServiceBusy` exception.
- Python API
- Account service
```
openio 4.8.2.dev12
```
> Catch Redis errors

- oio/common/tool.py
Fix a typo
- Typo Pull Request
- Python API
```
openio 5.2.5.dev1
```
> Python API: Fix a typo

- oio/cli/admin/xcute/rawx.py
- oio/xcute/jobs/blob_mover.py
Allow to partially decommission a rawx
- `xcute`
```
openio 5.2.5.dev134
```
> xcute: Allow to partially decommission a rawx

- oio/xcute/common/backend.py
Keep estimated total in Redis.
- Improvement Pull Request
- `xcute`
```
openio 5.2.5.dev134
```
> xcute: Keep the estimated total number of tasks in Redis

- rawx/chunk_info.go
- rawx/handler_chunk.go
- tests/functional/api/test_directory.py
- tests/functional/blob/test_blob.py
Improve missing xattr error messages
- rawx
```
openio 6.0.2.dev1
```
> rawx: Improve missing xattr error messages

- core/lb.c
Improve error message when policy is not satisfiable.
- LB
```
openio 4.8.3.dev2
```
> Improve error message when policy is not satisfiable

- oio/xcute/orchestrator.py
The xcute orchestrator is currently using all the beanstalkd available, instead of only using the ones with the `oio-xcute` tube. This can lead to tasks that will never be treated and hence never-ending jobs.
xcute
> Xcute: fix the orchestrator using all the beanstalkd

- CONTRIBUTING.md
Define oio-sds merge strategy, give tips about creating a pull request.
- None
```
master
```
> Define oio-sds merge strategy

- rawx/handler_chunk.go
Enhance LogError with reqid
rawx
```
master
```
> Include request ID in rawx error messages

- meta1v2/meta1_backend_properties.c
- meta2v2/meta2_backend.c
- meta2v2/meta2_macros.h
- oio/account/backend.py
- oio/account/client.py
- oio/account/server.py
- oio/api/object_storage.py
- oio/cli/container/container.py
- oio/common/constants.py
- oio/event/filters/account_update.py
- proxy/m2_actions.c
- setup.cfg
- tests/functional/account/test_backend.py
- tests/functional/api/test_objectstorage.py
- tests/functional/cli/__init__.py
- tests/functional/cli/account/test_account.py
- tests/functional/cli/container/test_container.py
Jira: OB-501
- Python API
- oio-proxy
- meta2
```
openio 5.3.0.0b1.dev9
```
> Aggregate bucket statistics

- oio/account/backend.py
- oio/account/client.py
- oio/account/server.py
- oio/cli/container/container.py
- setup.cfg
- tests/functional/cli/container/test_container.py
Jira: OB-501
- CLI
```
openio 5.3.0.0b1.dev16
```
> Implement 'openio bucket show' command

- oio/xcute/jobs/blob_mover.py
Ignore chunks that no longer exist when decommissioning rawx.
- `xcute`
```
openio 5.3.0.0b1.dev12
```
> Ignore chunks that no longer exist when decommissioning rawx

- oio/xcute/common/job.py
- oio/xcute/jobs/blob_mover.py
- oio/xcute/jobs/blob_rebuilder.py
- oio/xcute/orchestrator.py
Allow enough time to process the tasks batch.
- `xcute`
```
openio 5.3.0.0b1.dev18
```
> Allow enough time to process the tasks batch

- oio/cli/admin/xcute/__init__.py
- oio/cli/admin/xcute/meta2.py
- oio/cli/admin/xcute/rawx.py
- oio/xcute/jobs/__init__.py
- oio/xcute/jobs/blob_mover.py
- oio/xcute/jobs/blob_rebuilder.py
- oio/xcute/jobs/common.py
- oio/xcute/jobs/container_mover.py
- oio/xcute/jobs/meta2_decommissioner.py
- oio/xcute/jobs/meta2_rebuilder.py
- setup.cfg
Add meta2 decommissioning & rebuilding xcute jobs.
xcute
```
(venv) [root@ns3118434 xcute]# openio container locate test_container                                                                                                           
+-----------------+--------------------------------------------------------------------+                                                                                        
| Field           | Value                                                              |                                                                                        
+-----------------+--------------------------------------------------------------------+                                                                                        
| …
```
> xcute: Meta2 decommissionner + rebuilder

- oio/cli/admin/xcute/meta2.py
- oio/xcute/common/backend.py
- oio/xcute/orchestrator.py
- Start one job at a time
- Keep the launch of a job safe
- `xcute`
```
openio 5.3.0.0b1.dev21
```
> Keep the launch of a job safe

- oio/rebuilder/blob_rebuilder.py
- rdir/rdir.c
- tests/functional/api/test_rdir.py
Log when the incident date is missing
- oio-blob-rebuilder
```
openio 4.8.3.dev6
```
> blob-rebuilder: Log when the incident date is missing

- tools/benchmark/oio-bench-object-create.py
Improve the object creation benchmark to make it measure the object listing speed before deleting all the objects/
- tools
```
openio 5.3.0.0b1.dev34
```
> tools: measure listing time after object creation rate

- bin/oio-blob-converter
- oio/blob/converter.py
- oio/blob/utils.py
- oio/common/xattr.py
- tests/functional/blob/test_converter.py
Reinforce the verification of the chunk ID when converting old chunks.
- `oio-blob-converter`
```
openio 4.8.3.dev3
```
> converter: Reinforce the verification of the chunk ID

- oio/common/http_eventlet.py
- oio/conscience/checker/base.py
- oio/content/content.py
- oio/xcute/common/backend.py
- oio/xcute/common/worker.py
- Stop using deprecated 'message' attribute in Exception
- Improve Python3 compatibility for `xcute`
- `xcute`
- Python API
```
openio 7.0.0.dev1
```
> Improve Python3 compatibility

- etc/event-handlers.conf-sample
- oio/account/backend.py
- oio/account/client.py
- oio/account/server.py
- oio/cli/container/container.py
- oio/common/constants.py
- oio/event/evob.py
- oio/event/filters/replicate.py
- setup.cfg
- tests/functional/cli/account/test_account.py
- tests/functional/cli/container/test_container.py
- tests/functional/conscience/test_conscience.py
- tests/functional/event/filters/test_filters.py
- tools/oio-bootstrap.py
Jira: OB-477
- event-agent
```
openio 5.3.0.0b1.dev31
```
> Enable or disable replication for each bucket

- oio/common/redis_conn.py
- oio/common/wsgi.py
Reduce the verbosity of some known errors, prevent them from filling the logs with stack traces.
Jira: OS-505
```
5.4.0.0b0-17-gd8d2a1f2
```
> account: make known errors less verbose

- rawx/beanstalk.go
- rawx/buffer_pool.go
- rawx/chunk_info.go
- rawx/chunkrepo.go
- rawx/conf_reader.go
- rawx/configuration.go
- rawx/const.go
- rawx/filerepo.go
- rawx/handler_chunk.go
- rawx/handler_info.go
- rawx/handler_stat.go
- rawx/hexa.go
- rawx/logger.go
- rawx/main.go
- rawx/main_test.go
- rawx/notifier.go
- rawx/rawx.go
- rawx/repo.go
Backport RAWX changes in 19.04
- Backport Pull Request
rawx
```
5.4.0dev1
```
> Backport rawx

- proxy/m2_actions.c
Complete the documentation about the `content/create` route from oioproxy services.
Jira: OS-513
- oioproxy
```
openio 5.4.1.dev1
```
> proxy: update content/create documentation

- rawx/handler_chunk.go
- rawx/handler_info.go
- rawx/handler_stat.go
It will be usefull to see which requests uses TLS or plain IP:PORT
rawx
```
7.0.0.0a3
```
> rawx: log req.host instead of rawx.url

- oio/api/ec.py
- oio/api/object_storage.py
- oio/api/replication.py
- oio/common/utils.py
Compute average, standard deviation and relative standard deviation for
chunk operations.
- Python API
```
idc
```
> Python API: compute extra perfdata

- core/lb.c
- tests/functional/content/test_plain.py
Check the count of known targets to avoid segfault
- oioproxy
```
openio 5.5.2.dev1
```
> Check the count of known targets to avoid segfault

- tests/functional/content/test_content_perfectible.py
Try to get rid of one of the many flaky tests.
All.
```
openio 5.5.1.dev5
```
> Fix one flaky test

- oio/account/server.py
- proxy/m2_actions.c
- rdir/rdir.c
Fix several warnings raised during the extraction of oio-sds APIs documentations.
- oioproxy
- rdir
```
openio 7.0.0.0b2.dev7
```
> Fix warnings raised by the documentation extractor

- oio/api/ec.py
- oio/api/replication.py
- oio/blob/client.py
- oio/blob/mover.py
- oio/content/factory.py
- tests/functional/blob/test_mover.py
Check size of all uploaded chunks
- Python API
- `blob-mover`
- `blob-rebuilder`
```
openio 5.5.3.dev5
```
> Check size of all uploaded chunks

- oio/cli/admin/service_check.py
The previous version of `openio-admin meta0 check` didn't show
valuable information when a mismatch between ZK and conscience occurs.
The new command list emit Warn for meta0 down and Error when a
mismatch occurs.
The return code is also set when Error is emitted
CLI
```
7.0.0-dev1
```
Before
```
```
With this PR:
```
```
> Admin CLI: Enhance meta0 check

- cluster/module/server.c
Add more logs
- multi-conscience
```
openio 5.5.4.dev1
```
> multi-conscience: Add more logs

- oio/cli/container/container.py
- tests/functional/cli/container/test_container.py
Add option to show versioning status for `bucket list` command.
CLI
```
5.5.5.4.dev1
```
> Enhance bucket listing with versioning status

- Variables.md
- conf.json
- sqliterepo/cache.c
- sqlx/sqlx_service.c
- Replace mallinfo by getrusage
- Allow sqliterepo_max_rss to be disabled y configuration
sqliterepo
```
5.5.4.dev8
```
> Replace mallinfo by getrusage

- oio/api/io.py
Pass the request ID when linking
- Python API
```
openio 5.5.5.dev1
```
> Python API: Pass the request ID when linking

- oio/blob/client.py
Properly pass the connection and write timeout when linking
- Python API
```
openio 5.5.5.dev3
```
> Properly pass the connection and write timeout when linking

- all-requirements.txt
- core/oiocfg.h
- oio/api/object_storage.py
- proxy/m2_actions.c
- tests/functional/content/test_content_versioning.py
Improve versioning management:
- set a content type on delete markers;
- set an `is_latest` boolean on each item when listing container objects.
- oio-proxy
- Python API
```
openio 7.0.1.dev26
```
> Improve versioning management

- oio/common/logger.py
Add time in console logs
- Python API
```
openio 5.5.6.dev12
```
> Python API: Add time in console logs

- tools/benchmark/oio-bench-account-container-update.py
Implement a basic benchmark for the account service which will send account/container/update requests as fast as possible for 60s.
- account
- tools
```
openio 7.0.1.dev24
```
> tools: implement a basic benchmark for the account service

- rawx/main.go
- rawx/rawx.go
- rawx/utils.go
- sqlx/sqlx_service.c
Check rawx repository with probe (as for metaX)
- `rawx` (Golang)
```
openio 5.7.1.dev2
```
> rawx: Check repository with probe

- cluster/lib/gridcluster.c
- cluster/module/server.c
- metautils/lib/metatype_srvinfo.h
- metautils/lib/metatypes.h
- metautils/lib/utils_service_info.c
- proxy/cs_actions.c
- tests/functional/conscience/test_conscience.py
Keep the service locks when restarting conscience with multi-conscience.
- multi-conscience
```
openio 5.6.2.dev1
```
> multi-conscience: Keep the service locks when restarting conscience

- oio/conscience/agent.py
If several services are configured on the same endpoint, log an error,
and do not report them to the conscience.
Jira: OBSTO-192
- conscience-agent
```
openio 7.1.1.dev2
```
> conscience-agent: check for service endpoint conflicts

- meta2v2/meta2_utils.c
Don't ignore database errors and fix some memory leaks
- `meta2`
```
openio 5.7.1.dev8
```
> meta2: Don't ignore database errors

- oio/account/backend.py
- proxy/m2_actions.c
Update the last valid Unicode character
- `meta2`
- `account`
```
openio 5.7.1.dev9
```
> Update the last valid Unicode character

- oio/xcute/common/backend.py
- oio/xcute/common/job.py
- oio/xcute/orchestrator.py
Adapt the speed of job according to the processing speed 
This speed adaptation must avoid accumulating delays in unprocessed tasks,
and therefore avoid unnecessarily filling queues.
- `xcute`
```
openio 5.7.1.dev28
```
> xcute: Adapt the speed of job according to the processing speed 

- core/internals.h
- oio/account/server.py
- oio/api/base.py
- oio/common/constants.py
- proxy/cache_actions.c
- proxy/common.h
- proxy/cs_actions.c
- proxy/metacd_http.c
- proxy/reply.c
- proxy/transport_http.c
- rdir/rdir.c
- tools/event-benchmark/fake_service.c
Decode JSON only if the content type is `application/json`.
- Python API
- `account`
- `proxy`
```
openio 4.4.2.dev30
```
> Decode JSON only if the content type is 'application/json'

- tests/functional/api/test_objectstorage.py
Implement new tests to check Python API behavior when errors occur during EC downloads.
- Python API
```
openio 6.0.0.0a1
```
> tests: failures during EC downloads
